### ISSUE TITLE
Some tests are locale-specific

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#10018]
### Describe the bug

My system locale is `ru_RU.UTF-8`. When I run `cargo test --workspace`, one test fails:
```
failures:

---- conversions::into::string::test::test_examples stdout ----
thread 'conversions::into::string::test::test_examples' panicked at 'assertion failed: `(left == right)`
  left: `String { val: "5,000", span: Span { start: 0, end: 0 } }`,
 right: `String { val: "5.000", span: Span { start: 0, end: 0 } }`: The example result differs from the expected value', crates/nu-cmd-lang/src/example_support.rs:145:9
```
The separator is comma in the russian locale, and period in the english (or posix) locale: https://en.wikipedia.org/wiki/Decimal_separator. As the locale-specific representation is not related to the responsibility of the code being tested, I think it's better to always reset the locale when running the tests, i.e. `LANG= cargo test --workspace`. This line can be added to the documentation or directly into toolkit.nu

### How to reproduce

---

### Expected behavior

---

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by Jeans1984** [comment]
Same happens at tests/repl/tests.rs:72:5 

Cannot build '/nix/store/7iidrdp5ilk4wf7jg438shdbhjsgj28i-nushell-0.104.1.drv'.
       Reason: builder failed with exit code 101.
       Output paths:
         /nix/store/ws4236zab95qi8v5j9a29k2z35b72bk6-nushell-0.104.1
       Last 25 log lines:
       >
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       > ---- repl::test_parser::filesize_with_underscores_2 stdout ----
       > stdout: 1,0 MB
       >
       > stderr:
       >
       > thread 'repl::test_parser::filesize_with_underscores_2' panicked at tests/repl/tests.rs:72:5:
       > assertion failed: `(left == right)`
       >
       > Diff < left / right > :
       > <1,0 MB
       > >1.0 MB
       >
       >
       >
       >
       > failures:
       >     repl::test_parser::filesize_with_underscores_1
       >     repl::test_parser::filesize_with_underscores_2
       >
       > test result: FAILED(B. 1457 passed; 2 failed; 25 ignored; 0 measured; 4 filtered out; finished in 40.42s
       >
       > error: test failed, to rerun pass `--test main`

**Comment by mikerockett** [comment]
Same issue here, on en-ZA (with 1,234.00 formatting, although it does not matter which formatting I use (macOS)).

**Comment by ealap** [comment]
I have submitted a [PR](https://github.com/NixOS/nixpkgs/pull/422200) on nixpkgs side to mitigate this issue - the solution is to set env variable `NU_TEST_LOCALE_OVERRIDE` to `en_US.utf8`. It wasn't failing before because tests were disabled on darwin systems but was later re-enabled in https://github.com/NixOS/nixpkgs/pull/400302.

**Comment by cptpiepmatz** [comment]
Since i'm regularly testing on a german system and I fixed such issues, I guess this can be closed.
