### ISSUE TITLE
"glob /" crashes on windows

### ISSUE THREAD

**Issue by St0wy** [nushell/nushell#10156]
### Describe the bug

Using the `glob` command with a "linux" root as the parametter crashes Nu.

(Not sure why the env variable does nothing here)
```nushell
RUST_BACKTRACE=1 glob /         
08/30/2023 08:23:14 PMthread 'main' panicked at 'path is not in tree: StripPrefixError(())', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wax-0.5.0\src\walk.rs:694:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101 (0x00000065)]
```

### How to reproduce

Write `glob /` in Nushell on Windows.

### Expected behavior

I expected Nushell to give an error explaining that linux absolute paths don't work on windows. Maybe also forbid it in general to have the same behaviour on linux and windows as to avoid problems. It wouldn't too much of an issue I think since glob is mostly used with relative paths.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.0                                   |
| branch             |                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-22 21:20:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by ChrisDenton** [comment]
On Windows `/` is equivalent to `\` which is a relative path that means "the root of the current directory". For example, if the current directory is `C:\Users\Chris` then `/` is interpreted as `C:\`. Tbh, I'm not sure how useful it is to preserve this behaviour but it does date back to DOS.

But yes, it shouldn't crash nu. It would be good to provide the crash message, if any.

**Comment by amtoine** [comment]
@St0wy 
i'm not sure i get what "crash" here means :thinking: 
do you have a message or an error?

**Comment by St0wy** [comment]
Yes sorry I updated my message with the panic message (I can't seem to make RUST_BACKTRACE work for some reason though)

**Comment by amtoine** [comment]
> Yes sorry I updated my message with the panic message
>
thanks :pray: 

> I can't seem to make RUST_BACKTRACE work for some reason though
>
i think you need to run `glob /` from inside `RUST_BACKTRACE=1 nu` rather than run `RUST_BACKTRACE=1 glob /` from inside regular `nu` :yum:

**Comment by horasal** [comment]
Crash comes from `/` expansion.  `/` is expanded as relative-path instead of full path, e.g. run `ls /` in `E:/nushell` gives:

```
│  9 │ ..\nushell                            │ dir  │      0 B │ 19 minutes ago │
```

`wax` doesn't suppose this type of input and still try to `strip_prefix` with `/` so it crashes [here](https://github.com/olson-sean-k/wax/blob/master/src/walk.rs#L140).

run `glob /` in root dir like `E:/` does not crash.

Trace info on my machine:

```
thread 'main' panicked at 'path is not in tree: StripPrefixError(())', wax-0.5.0\src\walk.rs:694:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: enum2$<core::result::Result<ref$<std::path::Path>,std::path::StripPrefixError> >::expect<ref$<std::path::Path>,std::path::StripPrefixError>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\result.rs:1046
   4: wax::walk::impl$13::next
             at wax-0.5.0\src\walk.rs:694
   5: core::ops::function::FnOnce::call_once<enum2$<core::option::Option<enum2$<core::result::Result<wax::walk::WalkEntry,wax::walk::WalkError> > > > (*)(ref_mut$<wax::walk::Walk>),tuple$<ref_mut$<wax::walk::Walk> > >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\ops\function.rs:250
   6: core::iter::adapters::fuse::and_then_or_clear<wax::walk::Walk,enum2$<core::result::Result<wax::walk::WalkEntry,wax::walk::WalkError> >,enum2$<core::option::Option<enum2$<core::result::Result<wax::walk::WalkEntry,wax::walk::WalkError> > > > (*)(ref_mut$<wa
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\fuse.rs:423
   7: core::iter::adapters::fuse::impl$9::next<wax::walk::Walk>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\fuse.rs:272
   8: core::iter::adapters::fuse::impl$2::next
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\fuse.rs:43
   9: core::iter::adapters::flatten::impl$20::next<wax::walk::Walk,core::result::IntoIter<wax::walk::WalkEntry> >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\flatten.rs:493
  10: core::iter::adapters::flatten::impl$12::next<wax::walk::Walk,core::result::IntoIter<wax::walk::WalkEntry> >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\iter\adapters\flatten.rs:213
  11: nu_command::filesystem::glob::glob_to_value<core::iter::adapters::flatten::Flatten<wax::walk::Walk> >
             at .\crates\nu-command\src\filesystem\glob.rs:253
  12: nu_command::filesystem::glob::impl$0::run
             at .\crates\nu-command\src\filesystem\glob.rs:221
  13: nu_engine::eval::eval_call
             at .\crates\nu-engine\src\eval.rs:173
  14: nu_engine::eval::eval_expression_with_input
             at .\crates\nu-engine\src\eval.rs:712
  15: nu_engine::eval::eval_element_with_input
             at .\crates\nu-engine\src\eval.rs:787
  16: nu_engine::eval::eval_block
             at .\crates\nu-engine\src\eval.rs:1101
  17: nu_cli::util::eval_source
             at .\crates\nu-cli\src\util.rs:244
  18: nu_cli::repl::evaluate_repl
             at .\crates\nu-cli\src\repl.rs:588
  19: nu::run::run_repl
             at .\src\run.rs:243
  20: nu::main
             at .\src\main.rs:296
  21: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > (*)(),tuple$<> >
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by 132ikl** [comment]
Unable to reproduce on 0.105.1, I think this has been resolved. If you're still having this issue let us know and we can re-open it.
