### ISSUE TITLE
`save` closed pipe before stream end

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell#10454]
### Describe the bug

I ran a rust program that prints to stdout, piping that output to `save -f output.txt`. The program crashed with the following error:
```
thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', library\std\src\io\stdio.rs:1019:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I suspect that the fault is with `nu` and not with my program or executing environment, but I am unsure, and have only seen this issue very rarely.

### How to reproduce

1. `my_rust_program | save -f $output_file`

### Expected behavior

Write my output to file, closing the stream when writing has finished.

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.85.1                                    |
| branch             | main                                      |
| commit_hash        | 7cfd4d2cfabca8f26e8bd1f84125bc256b650787  |
| build_os           | windows-x86                               |
| build_target       | i686-pc-windows-msvc                      |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)       |
| rust_channel       | 1.70.0-i686-pc-windows-msvc               |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)       |
| build_time         | 2023-09-21 09:48:44 +08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

### Additional context

if it's relevant, I'm running on windows 10 without `WSL`.

**Comment by amtoine** [comment]
@Zoybean 
do you have the program in question around so that people can try? :yum: 

or maybe another command to run?

**Comment by Zoybean** [comment]
I must have forgotten to mention in the original post: I can't share the program itself, but I'll try to make a representative program that still exhibits the issue.

**Comment by amtoine** [comment]
> I must have forgotten to mention in the original post: I can't share the program itself
>
no worries :+1: 

> but I'll try to make a representative program that still exhibits the issue.
>
yeah that would be perfect, e.g. if you can strip everything useless to the bug repro from the original program, that might be ok to share :yum:

**Comment by AucaCoyan** [comment]
I have the same output with
```bash
$ nu --ide-check 10 C:\Users\aucac\repos\nu_scripts\custom-completions\auto-generate\completions\zef.nu | describe
raw input
thread 'main' panicked at library\std\src\io\stdio.rs:1019:9:
failed printing to stdout: The pipe is being closed. (os error 232)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Zoybean** [comment]
Have you been able to get that output repeatedly on that file (`zef.nu`)? If so, can you share its contents? What version of `nu` is this?

Unfortunately I have only ever encountered this when I am not expecting it, so I am eager for a reproducible example.

**Comment by AucaCoyan** [comment]
> Have you been able to get that output repeatedly on that file (zef.nu)? If so, can you share its contents? What version of nu is this?

Yep, every time. That file `zef.nu` is the file from `nu_scrips` repo, another repo from this nushell org 😄 . I'm using nu 0.89.0
