### ISSUE TITLE
panicked nu shell. ls \\.\pipe\\  No such local time 

### ISSUE THREAD

**Issue by davehorner** [nushell/nushell#10464]
### Listing windows pipes crashes nu
nu -e "ls \\.\pipe\\"

```
 ls \\.\pipe\\                                                              09/21/23 23:39:23 PM
Failed to read metadata for '\\.\pipe\uv\0000000000000000-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000000-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000003-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000003-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000004-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000004-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000005-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000005-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000006-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000A-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000A-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000B-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000B-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000C-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000C-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000D-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000E-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000010-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000011-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000012-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000013-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000014-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000015-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000015-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000016-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000016-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000017-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000017-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000018-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000019-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001A-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001B-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001C-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001D-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001D-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001E-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001F-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000021-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000021-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000022-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000022-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000023-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000023-36912'. It may have an illegal filename
thread 'main' panicked at C:\Users\dhorner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chrono-0.4.31\src\offset\local\mod.rs:176:46:
No such local time
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\nu.exe` (exit code: 101)
```

### How to reproduce

1. start a nu shell on windows; ls \\.\pipe\\  

### Expected behavior

should get the same results as: dir /b \\.\pipe\\

I will note that the /b is nice to use because even dir has trouble listing the contents of this folder.
```
The parameter is incorrect.
◄♂                   1 ConEmuSrv13408
The parameter is incorrect.
☻►                   1 ConEmuHk37048
The parameter is incorrect.
☻♫                   1 ConEmuSrv224
The parameter is incorrect.
☻♫                   1 ConEmuHk15152
The parameter is incorrect.
☻♫                   1 ConEmuSrv38244
The parameter is incorrect.
☻♫                   1 ConEmuSrvRead224
The parameter is incorrect.
☻♫                   1 ConEmuSrv34036
The parameter is incorrect.
☻♫                   1 ConEmuSrvInput224
The parameter is incorrect.
◄♣                   1 ConEmuSrvInput13408
The parameter is incorrect.
◄                          1 ConEmuSrvRead13408
The parameter is incorrect.
◄                   1 ConEmuHk14908
The parameter is incorrect.
☻♫                   1 ConEmuHk29876
...and the list goes on...
```

### Configuration

c:/working/rust/nushell> version | transpose key value | to md --pretty                             09/21/23 23:45:33 PM
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.85.1                                      |
| branch             | main                                        |
| commit_hash        | 1bb953877e0c574bf28e9033210684bd82a2c820    |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.74.0-nightly (3223b0b5e 2023-09-20) |
| cargo_version      | cargo 1.74.0-nightly (b4ddf95ad 2023-09-18) |
| build_time         | 2023-09-21 18:21:53 -04:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

### Additional context

full backtrace:
```
Failed to read metadata for '\\.\pipe\uv\0000000000000000-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000000-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000003-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000003-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000004-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000004-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000005-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000005-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000006-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000A-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000A-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000B-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000B-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000C-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000C-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000D-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000E-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000010-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000011-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000012-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000013-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000014-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000015-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000015-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000016-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000016-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000017-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000017-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000018-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000019-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001A-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001B-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001C-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001D-15212'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001D-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001E-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000001F-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000020-7668'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000021-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000021-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000022-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000022-36912'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000023-10028'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000023-36912'. It may have an illegal filename
thread 'main' panicked at C:\Users\dhorner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chrono-0.4.31\src\offset\local\mod.rs:176:46:
No such local time
stack backtrace:
   0:     0x7ff76250243f - <unknown>
   1:     0x7ff7618dde8b - <unknown>
   2:     0x7ff7624fc221 - <unknown>
   3:     0x7ff7625021ba - <unknown>
   4:     0x7ff762504d29 - <unknown>
   5:     0x7ff7625049bd - <unknown>
   6:     0x7ff7625054e0 - <unknown>
   7:     0x7ff76250521b - <unknown>
   8:     0x7ff762503099 - <unknown>
   9:     0x7ff762504f94 - <unknown>
  10:     0x7ff7626e9d37 - <unknown>
  11:     0x7ff7618cb2be - <unknown>
  12:     0x7ff761bd8351 - <unknown>
  13:     0x7ff761bb81a9 - <unknown>
  14:     0x7ff761b05095 - <unknown>
  15:     0x7ff761c749b3 - <unknown>
  16:     0x7ff761e00dad - <unknown>
  17:     0x7ff76237f681 - <unknown>
  18:     0x7ff76236451d - <unknown>
  19:     0x7ff762363539 - <unknown>
  20:     0x7ff7619f8437 - <unknown>
  21:     0x7ff7619c2b22 - <unknown>
  22:     0x7ff7619a9b2d - <unknown>
  23:     0x7ff761999c15 - <unknown>
  24:     0x7ff7619a3a76 - <unknown>
  25:     0x7ff7619ad728 - <unknown>
  26:     0x7ff7624f5378 - <unknown>
  27:     0x7ff76199b9dc - <unknown>
  28:     0x7ff7626d09ac - <unknown>
  29:     0x7ffe865b7344 - BaseThreadInitThunk
  30:     0x7ffe87ba26b1 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\nu.exe` (exit code: 101)
```

**Comment by davehorner** [comment]
the problem unwrap().
chrono-0.4.31\src\offset\local\mod.rs
``` 
    fn offset_from_utc_datetime(&self, utc: &NaiveDateTime) -> FixedOffset {
        inner::offset_from_utc_datetime(utc).unwrap()
    }
```

crates\nu-command\src\filesystem\ls.rs :583
```
// TODO: can we get away from local times in `ls`? internals might be cleaner if we worked in UTC
// and left the conversion to local time to the display layer
fn try_convert_to_local_date_time(t: SystemTime) -> Option<DateTime<Local>> {
    // Adapted from https://github.com/chronotope/chrono/blob/v0.4.19/src/datetime.rs#L755-L767.
    let (sec, nsec) = match t.duration_since(UNIX_EPOCH) {
        Ok(dur) => (dur.as_secs() as i64, dur.subsec_nanos()),
        Err(e) => {
            // unlikely but should be handled
            let dur = e.duration();
            let (sec, nsec) = (dur.as_secs() as i64, dur.subsec_nanos());
            if nsec == 0 {
                (-sec, 0)
            } else {
                (-sec - 1, 1_000_000_000 - nsec)
            }
        }
    };

    match Utc.timestamp_opt(sec, nsec) {
        LocalResult::Single(t) => Some(t.with_timezone(&Local)),
        _ => None,
    }
}
```

We fall into the Err case and then do the t.with_timezone(&Local) which is not valid.
I made the following change that just passes a bool out to indicate if we fell into Err.
```
// TODO: can we get away from local times in `ls`? internals might be cleaner if we worked in UTC
// and left the conversion to local time to the display layer
fn try_convert_to_local_date_time(t: SystemTime) -> Option<DateTime<Local>> {
    // Adapted from https://github.com/chronotope/chrono/blob/v0.4.19/src/datetime.rs#L755-L767.
    let (sec, nsec, was_success) = match t.duration_since(UNIX_EPOCH) {
        Ok(dur) => {
            (dur.as_secs() as i64, dur.subsec_nanos(),true)
        },
        Err(e) => {
            // unlikely but should be handled
            let dur = e.duration();
            let (sec, nsec) = (dur.as_secs() as i64, dur.subsec_nanos());
            if nsec == 0 {
                (-sec, 0,false)
            } else {
                (-sec - 1, 1_000_000_000 - nsec,false)
            }
        }
    };
    if was_success {
       return match Utc.timestamp_opt(sec, nsec) {
            LocalResult::Single(t) => Some(t.with_timezone(&Local)),
            _ => None,
        }
    }
    None
}
```
That modification allows the code to complete through the dir_entry_dict
```
       record.push("modified", {
            let mut val = Value::nothing(span);
            if let Ok(m) = md.modified() {
                    if let Some(local) = try_convert_to_local_date_time(m) {
                        val = Value::date(local.with_timezone(local.offset()), span);
                    }
            }
            val
        })
```
the above is where we were crashing.

I moved past that and now I'm looking at this:
thread 'main' panicked at crates\nu-command\src\filesystem\ls.rs:729:34:
```
        let rel_to_linux_epoch = time_u64 - EPOCH_AS_FILETIME;
```
attempt to subtract with overflow.

**Comment by davehorner** [comment]
https://github.com/nushell/nushell/compare/main...davehorner:nushell:ls_pipes_nushell

it might be worth using a library that doesn't panic so much.  the chrono calls should probably be wrapped.
The fix here saves the existing panic hook and sets it back when done using chrono.

There is some other problems too with doing searches.  If I make a pipe in a folder, the folder can't be found with a glob or direct.  i.e.   \\.\pipe\xyz\somepipe   should be listed using ls \\.\pipe\xyz\*  or ls  \\.\pipe\xyz or ls  \\.\pipe\xyz\

it IS, listed in the output of "\\.\pipe\"

```
Error:   × No matches found for \\.\pipe\xyz\*
   ╭─[entry #39:1:1]
 1 │ ls \\.\pipe\xyz\*
   ·    ───────┬──────
   ·           ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

**Comment by fdncred** [comment]
Nice research. One concept you may not understand yet is that double quotes interpret escapes. So, if you're using double quotes on Windows paths, it's typically bad news because of all the backslashes being interpreted as escapes like `c:\program files` would fail for 2 reasons (1) \p isn't a valid escape and (2) spaces in file paths have to be within backtick quotes.

I'm up for a PR to fix chrono. It's a true pain that we run into often where it blows up with invalid dates/times. We can look at moving away from chrono but it's pretty ubiquitous in rust. Just about everyone/everything uses chrono.

**Comment by davehorner** [comment]
Yes chrono is popular.  I don't understand the unwraps in a library; or not having an alternate try interface.  

quick search shows two others may be affected; 
thread 'main' panicked at 'SystemTimeToFileTime failed with: The parameter is incorrect.
https://github.com/nushell/nushell/issues/6574
https://github.com/nushell/nushell/issues/9470 

whats the story on the panic_handler?  does nushell get involved in the handler? or might in the future.
just wondering if theres concern about getting and setting the handler...and then wondering if nu should ever allow exit via panic or attempt to do something about them.  it may not be needed to keep swapping in and out a default handler no one's overriding.

the output I would like to see reduced/fixed.  the pipeline is usable with the patch provided at least.
```
Failed to read metadata for '\\.\pipe\uv\0000000000000023-36912'. It may have an illegal filename
```
it's a legal filename, its a unhelpful message other than its easy to find.  Points given since dir is being broken in regard to these files so some broken output is par.

**Comment by fdncred** [comment]
I thought miette handled panics? Maybe I'm reading this wrong?

https://github.com/nushell/nushell/blob/1bb953877e0c574bf28e9033210684bd82a2c820/src/main.rs#L55-L60

Just to commiserate with you, I can repro the problem.
```
❯ ls \\.\pipe\
Failed to read metadata for '\\.\pipe\uv\0000000000000000-34064'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-34064'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000006-34064'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-34064'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-34064'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-34064'. It may have an illegal filename
thread 'main' panicked at 'No such local time', C:\Users\dschroeder\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chrono-0.4.31\src\offset\local\mod.rs:176:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We'd definitely like to see this fixed somehow.

**Comment by davehorner** [comment]
ah. cool I had not met miette before.  wrapping the panics and doing as the patch does should not break miette...does make me wonder about threading during the panic handler swaps.

I would think that there should be a solution where we could place empty values in for created/modified/accessed and test for empty.  I tried to figure out a way to test the intermediates for invalid data...I am still unsure of how or what date data is actually being seen for these "files".  more tracing time.

**Comment by ChrisDenton** [comment]
Most normal filesystem functions will either fail here or else should return default metadata (e.g. often zeroed). So the time would likely be something like a zeroed [`FILETIME`](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime). Meaning the date is January 1, 1601 (centuries before the UNIX epoc).

**Comment by davehorner** [comment]
I did not see zero'd data.  I did not know Jan 1, 1601 was such an special date.  i will take a closer look; i forget which data type it was I was looking at but it had private internal.  I tried to .0 to get the data and was scolded by rustc.

**Comment by ChrisDenton** [comment]
To be precise, it's Jan 1, 1601 00:00 UTC. So you'll need to convert to your local time.

**Comment by davehorner** [comment]
oh the fun facts you learn in a day.

chrono's got a problem with 16th century dates.  special default date.

wait, dude what's local time in in the 16th century?  nevermind, just add whatever you like and don't panic!

**Comment by ChrisDenton** [comment]
Tbh, I think it might ultimately be worth someone investigating replacing `chrono` with `time`, as that's usually less panicky. However, that might be a big job (especially figuring out interop) and perhaps more than is necessary to fix the specific issue in the OP.

**Comment by ChrisDenton** [comment]
Yeah, I'm not particularly about the crate. I just mentioned time as it's probably the most popular alternative to chrono. In any case, investigating alternatives would be worthwhile but hopefully not a blocker for fixing this.

**Comment by davehorner** [comment]
I thought I read something about cp being used from https://github.com/uutils/coreutils. might uutils 'ls' gain some sort of nu adapter to share implementation? 

I'm not sure I'm up to the task of rip out and replacement of chrono crate work by myself.  i could see me trying to get a test case and PR for chrono.   But wrapping is probably easiest for quick turn around.

**Comment by fdncred** [comment]
I'd like to replace `ls` with `uu_ls` but it's a tricky problem because we have to stream the data.

**Comment by davehorner** [comment]
tricky problems are fun.  maybe not a task for the new nu guy but I think a better solution than maintaining another ls implementation.  I assume there was a lot of thought that went into getting cp in there streaming, that work translates?

I could go further in wrapping, but the fix is sufficient for my issue.  We can prune the output; but protecting panics and an overflow would be better than present state.

the comments are a bit TODO and uncertain about things.
```
// TODO: can we get away from local times in `ls`? internals might be cleaner if we worked in UTC
// and left the conversion to local time to the display layer
fn try_convert_to_local_date_time(t: SystemTime) -> Option<DateTime<Local>> {
    // Adapted from https://github.com/chronotope/chrono/blob/v0.4.19/src/datetime.rs#L755-L767.
    let (sec, nsec, was_success) = match t.duration_since(UNIX_EPOCH) {
        Ok(dur) => {
            (dur.as_secs() as i64, dur.subsec_nanos(),true)
        },
        Err(e) => {
            // unlikely but should be handled
            let dur = e.duration();
            let (sec, nsec) = (dur.as_secs() as i64, dur.subsec_nanos());
            if nsec == 0 {
                (-sec, 0,false)
            } else {
                (-sec - 1, 1_000_000_000 - nsec,false)
            }
        }
    };
    if was_success {
        let result = std::panic::catch_unwind(|| {
            return match Utc.timestamp_opt(sec, nsec) {
                LocalResult::Single(t) => Some(t.with_timezone(&Local)),
                _ => None,
            }
        });
        return result.unwrap();
        }
    None
}
```
it was_success that I added, implements exactly what is below it but the function below is under windows platform only and would cause troubles using that as is;  it would be preferable to get rid of the above call to t.with_timezone and use this unix_time_to_local_date_time, removing the platform specific as the comments suggest this is somehow related to Clippy! 

// #[cfg(windows)] is just to make Clippy happy, remove if you ever want to use this on other platforms
#[cfg(windows)]
fn unix_time_to_local_date_time(secs: i64) -> Option<DateTime<Local>> {
    let old_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_info| {
    }));
    let result=std::panic::catch_unwind(|| {
    match Utc.timestamp_opt(secs, 0) {
        LocalResult::Single(t) => Some(t.with_timezone(&Local)),
        _ => None,
    }
    });
    std::panic::set_hook(old_hook);
    match result {
        Ok(r) => r,
        _ => None,
    }
}
```
this keeps the catch_unwind localized for now to this utility function.

I'd propose that we drop "It may have an illegal filename" from the error messages.

**Comment by davehorner** [comment]
I like to close tickets.  What do you want, something that tests for the sentinel date?

**Comment by fdncred** [comment]
@davehorner What PR #? Maybe I missed it?

**Comment by davehorner** [comment]
@fdncred I didn't formally submit a PR, would you like me to go ahead and start the PR with the current changes? 

I did share a branch
https://github.com/nushell/nushell/compare/main...davehorner:nushell:ls_pipes_nushell

**Comment by fdncred** [comment]
yes, please. a PR would be great. We'd like to have this failure of chrono's patched somehow, plus it's easier to see exactly which lines you're changing.

**Comment by davehorner** [comment]
// #[cfg(windows)] is just to make Clippy happy, remove if you ever want to use this on other platforms
#[cfg(windows)]

what are your thoughts on removing that and actually using that across platform.

**Comment by fdncred** [comment]
I'm good with whatever works.

**Comment by davehorner** [comment]
PR is pending.  Thanks
https://github.com/nushell/nushell/pull/10558

**Comment by fdncred** [comment]
I think this is fixed. Please let me know if it's not.
