### ISSUE TITLE
Using $nu.path causes panic

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1111]
**Describe the bug**
Trying to do `echo $nu.path` causes panic

**To Reproduce**
1. `echo $nu.path` in master

**Expected behavior**
This should print an error instead if this isn't valid syntax. Or if it is valid syntax error with the location to change.

**Configuration (please complete the following information):**
 - OS: Linux
 - Version `master`
 - Optional features (if any) all stable

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShellError { error: TypeError { expected: "row or table", actual: Spanned { span: Span { start: 5, end: 8 }, item: Some("nothing") } }, cause: None }', src/libcore/result.rs:1189:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1189
  14: core::result::Result<T,E>::unwrap
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libcore/result.rs:957
  15: nu::commands::command::Command::run_helper::{{closure}}
             at src/commands/command.rs:505
  16: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}::{{closure}}
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:95
  17: core::option::Option<T>::map
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libcore/option.rs:450
  18: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:95
  19: core::task::poll::Poll<T>::map
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libcore/task/poll.rs:33
  20: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  21: <futures_util::stream::flatten::Flatten<St> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/flatten.rs:96
  22: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  23: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  24: futures_util::stream::StreamExt::poll_next_unpin
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/mod.rs:1143
  25: <futures_util::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/next.rs:35
  26: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  27: nu::commands::classified::internal::run_internal_command::{{closure}}::{{closure}}
             at ./src/commands/classified/internal.rs:45
  28: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  29: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  30: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  31: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  32: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  33: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  34: <nu::stream::OutputStream as futures_core::stream::Stream>::poll_next
             at src/stream.rs:106
  35: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:193
  36: futures_util::try_stream::TryStreamExt::try_poll_next_unpin
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/mod.rs:757
  37: <futures_util::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/try_next.rs:35
  38: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  39: nu::commands::autoview::autoview::{{closure}}
             at ./<::async_stream::stream macros>:9
  40: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  41: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  43: futures_util::stream::StreamExt::poll_next_unpin
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/mod.rs:1143
  44: <futures_util::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/next.rs:35
  45: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  46: nu::commands::classified::internal::run_internal_command::{{closure}}::{{closure}}
             at ./src/commands/classified/internal.rs:45
  47: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  48: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  49: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  50: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  51: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  52: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  53: <nu::stream::OutputStream as futures_core::stream::Stream>::poll_next
             at src/stream.rs:106
  54: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:193
  55: futures_util::try_stream::TryStreamExt::try_poll_next_unpin
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/mod.rs:757
  56: <futures_util::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/try_next.rs:35
  57: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  58: nu::commands::classified::pipeline::run_pipeline::{{closure}}
             at ./src/commands/classified/pipeline.rs:57
  59: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  60: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  61: nu::cli::process_line::{{closure}}
             at ./src/cli.rs:592
  62: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  63: std::future::poll_with_tls_context
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:99
  64: nu::cli::cli::{{closure}}
             at ./src/cli.rs:424
  65: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/future.rs:43
  66: futures_executor::local_pool::block_on::{{closure}}
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  67: futures_executor::local_pool::run_executor::{{closure}}
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:68
  68: std::thread::local::LocalKey<T>::try_with
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/thread/local.rs:262
  69: std::thread::local::LocalKey<T>::with
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/thread/local.rs:239
  70: futures_executor::local_pool::run_executor
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:64
  71: futures_executor::local_pool::block_on
             at /home/jonathanturner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  72: nu::main
             at src/main.rs:68
  73: std::rt::lang_start::{{closure}}
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/rt.rs:67
  74: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  75: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  76: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  77: std::panicking::try
             at src/libstd/panicking.rs:270
  78: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  79: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  80: std::rt::lang_start
             at /rustc/ff15e9670843f8bd6b54ab1b042d2095b4c0aa6d/src/libstd/rt.rs:67
  81: main
  82: __libc_start_main
  83: _start
```

**Comment by jonathandturner** [comment]
cc @wycats
