### ISSUE TITLE
Panic on completion for aliases

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11188]
### Describe the bug

Alias completion under specific circumstances causes a panic.

### How to reproduce

1. Have a config with this completer:
    
    ```Nushell
    $env.config.completions.external.completer = {|tokens: list<string>|
    	# Do not complete if the binary is not present.
    	if (which carapace | is-empty) {
    		return
    	}
    
    	let expanded_alias = (
    		scope aliases
    		| where name == $tokens.0
    		| get --ignore-errors 0
    		| get --ignore-errors expansion
    	)
    
    	let tokens = if ($expanded_alias != null) {
    		$tokens
    		| skip 1
    		| prepend ($expanded_alias | split row " ")
    	} else {
    		$tokens
    	}
    
    	let tokens = if ($tokens.0 == "doas") {
    		$tokens | skip 1
    	} else {
    		$tokens
    	}
    
    	# Do not complete for built-in commands.
    	if (which $tokens.0 | first | $in.type == "built-in") {
    		return
    	}
    
    	carapace $tokens.0 nushell $tokens | from json | default []
    }
    ```

2. Have an alias `alias calendar = cal --week-start monday`

3. Type `calendar `, press <Tab>, Nushell crashes.

### Expected behavior

-

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.86.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-10-22 21:58:37 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by KAAtheWiseGit** [comment]
Trying to complete `^cal` causes a message `failed to eval completer block: Return used outside of function` to flash briefly (it is replaced by paths right after).

**Comment by amtoine** [comment]
i don't think it has anything to do with completions :smirk: 

when i run
```nushell
nu -n
```
and then
```nushell
alias calendar = cal --week-start monday
```
pressing tab after `calendar ` gives the same error as yours
```
thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709551610, end=9', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reedline-0.26.0/src/completion/base.rs:18:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by amtoine** [comment]
it also sounds related to / a duplicated of https://github.com/nushell/nushell/issues/8122, right?

**Comment by KAAtheWiseGit** [comment]
@amtoine huh, that's weird.  I was sure it was completions, I guess I've never used tab on this alias.  It seems this and #8122 have the same error, but different causes: alias of a built-in command and multi-word alias.

**Comment by Abdillah** [comment]
For me, I use an alias for git bare:

```
alias ws = git --work-tree=($env.HOME)/some/folder/ --git-dir=($env.HOME)/some/folder/the.git
```

<details>
<summary>A bit of backtrace for case like this.</summary>
```
$ ws add Error:
  × Main thread panicked.
  ├─▶ at /build/nushell-0.101.0-vendor.tar.gz/reedline/src/completion/base.rs:21:9
  ╰─▶ Can't create a Span whose end < start, start=18446744073709354694, end=48
         0: 0x555bb6ec953c - rust_begin_unwind
         1: 0x555bb5fa90b0 - core::panicking::panic_fmt::hce616224d24d1eda
         2: 0x555bb6dc0f22 - reedline::completion::base::Span::new::h304b82b0e41a7af0
         3: 0x555bb61fdaca - nu_cli::completions::command_completions::CommandCompletion::complete_commands::h6b37c16427e0a736
         4: 0x555bb61fed88 - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::hf98fc5296eb66ed4
         5: 0x555bb62129f4 - nu_cli::completions::completer::NuCompleter::completion_helper::ha6525c9f7290a568
         6: 0x555bb62139d2 - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::hf38d1545a166d4b4
         7: 0x555bb62113fe - reedline::completion::base::Completer::complete_with_base_ranges::hb2645521c4e20c4e
         8: 0x555bb6d99543 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::h08a2f539af93544d
         9: 0x555bb6daa272 - reedline::engine::Reedline::handle_editor_event::h13b568845b0b54ca
        10: 0x555bb6da9ed0 - reedline::engine::Reedline::handle_editor_event::h13b568845b0b54ca
        11: 0x555bb6da8c07 - reedline::engine::Reedline::read_line::hd0295cdaeb62c41d
        12: 0x555bb61b05fa - nu_cli::repl::loop_iteration::he62cefa69cbe84b1
        13: 0x555bb61aad0a - std::panic::catch_unwind::h0937c8a93743056d
        14: 0x555bb621db7a - nu_cli::repl::evaluate_repl::haa82a03e8d6071d4
        15: 0x555bb618fd25 - nu::run::run_repl::h5e66d40c8e1c0b1b
        16: 0x555bb617b5f0 - nu::main::h5a26ef50600ca330
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
</details>

**Comment by Abdillah** [comment]
In v102, the panic still exists, it is really on recent commit then?

**Comment by blindFS** [comment]
> In v102, the panic still exists, it is really on recent commit then?

Yeah, pls try the latest nightly built if you don't want to build it from scratch

**Comment by KAAtheWiseGit** [comment]
Rebuilding main, stand by

**Comment by KAAtheWiseGit** [comment]
@blindFS, yep, it works correctly!  Thanks!
