### ISSUE TITLE
`ls` fails on master when TERM is missing

### ISSUE THREAD

**Issue by ndarilek** [nushell/nushell#1129]
```
/home/nolan/src/nushell(master)> ls
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Incidentaly, how do I get backtraces?

```bash
$ RUST_BACKTRACE=1 nu
```

doesn't give me any more information, unfortunately.

Thanks.

**Comment by quebin31** [comment]
Cannot reproduce.

**Comment by ndarilek** [comment]
Either issue? (by which I mean getting backtraces via `RUST_BACKTRACE`?) 
Happy to provide one if I can get it, or to attempt a fix.

**Comment by jonathandturner** [comment]
Without a backtrace, this is tricky to track down. Also, in the issue template there's a space for nu version, operating system, etc. These also help us narrow down to what might be causing it.

**Comment by ndarilek** [comment]
Right, and again, I'm happy to provide the backtrace, I just can't get 
it. Should `ENV_BACKTRACE=1 nu` be able to provide me that? Because it 
isn't and I'm wondering if *that* is also non-reproduceable. Sorry, I'm 
genuinely trying, but I can't get the backtrace either, and I have some 
Rust experience so am happy to roll up my sleeves and try a fix if I can.

**Comment by jonathandturner** [comment]
For RUST_BACKTRACE, I generally need to build a debug version for the best into. If you can check out nu from master, you can do: `cargo build --all --features=stable`. After that, you should be able to do: `RUST_BACKTRACE=1 target/debug/nu` from a shell like bash.

**Comment by ndarilek** [comment]
Hmm, still getting the same results. More details:


OS: Linux (Fedora 31 with all updates applied as of this morning)

Main shell: Fish, though also attempted under Bash

Architecture: AMD64

Rust versions: 1.39.0, nightly as of today


Interestingly, I found [this forum 
thread](https://users.rust-lang.org/t/rust-backtrace-1-did-not-work/35811/3) 
where someone else had issues with RUST_BACKTRACE. I posted a follow-up, 
and will update if I get any additional details.


Thanks.

**Comment by jonathandturner** [comment]
Interesting. Would you be able to try the latest stable Rust compiler also? I wonder if it's an issue with nightly

**Comment by ndarilek** [comment]
Oh, sorry, I meant 1.40.0, not 1.39.0. So used to thinking of .39 as 
stable. In any case, same results with both.

**Comment by ndarilek** [comment]
OK, figured it out, at least in so far as getting a backtrace. I needed to set `RUST_BACKTRACE=1` in Nu itself, not in the shell that launched it.

Though I'm not sure how helpful this will end up being. The failure seems to be with this line:

```
        term::stdout().unwrap()
```

Not sure why that could fail, particularly as I'm getting things printed to stdout just fine.

Here's the backtrace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: core::option::Option<T>::unwrap
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15
  15: <nu::env::host::BasicHost as nu::env::host::Host>::out_terminal
             at src/env/host.rs:54
  16: <alloc::boxed::Box<dyn nu::env::host::Host> as nu::env::host::Host>::out_terminal
             at src/env/host.rs:21
  17: <nu::format::table::TableView as nu::format::RenderView>::render_view
             at src/format/table.rs:378
  18: nu::format::print_view
             at src/format.rs:17
  19: nu::commands::table::table::{{closure}}::{{closure}}
             at src/commands/table.rs:55
  20: nu::env::host::handle_unexpected
             at src/env/host.rs:92
  21: nu::commands::table::table::{{closure}}
             at ./<::async_stream::stream macros>:9
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  23: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  24: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  25: <nu::stream::OutputStream as futures_core::stream::Stream>::poll_next
             at src/stream.rs:106
  26: <futures_util::stream::collect::Collect<St,C> as core::future::future::Future>::poll
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/collect.rs:51
  27: std::future::poll_with_tls_context
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:99
  28: nu::commands::autoview::autoview::{{closure}}
             at ./<::async_stream::stream macros>:9
  29: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  30: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  31: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  32: futures_util::stream::StreamExt::poll_next_unpin
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/mod.rs:1143
  33: <futures_util::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/next.rs:35
  34: std::future::poll_with_tls_context
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:99
  35: nu::commands::classified::internal::run_internal_command::{{closure}}::{{closure}}
             at ./src/commands/classified/internal.rs:45
  36: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  37: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.1.2/src/async_stream.rs:44
  38: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  39: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  40: <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/stream/map.rs:92
  41: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:121
  42: <nu::stream::OutputStream as futures_core::stream::Stream>::poll_next
             at src/stream.rs:106
  43: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/stream.rs:193
  44: futures_util::try_stream::TryStreamExt::try_poll_next_unpin
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/mod.rs:757
  45: <futures_util::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/try_stream/try_next.rs:35
  46: std::future::poll_with_tls_context
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:99
  47: nu::commands::classified::pipeline::run_pipeline::{{closure}}
             at ./src/commands/classified/pipeline.rs:57
  48: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  49: std::future::poll_with_tls_context
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:99
  50: nu::cli::process_line::{{closure}}
             at ./src/cli.rs:592
  51: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  52: std::future::poll_with_tls_context
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:99
  53: nu::cli::cli::{{closure}}
             at ./src/cli.rs:424
  54: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/future.rs:43
  55: futures_executor::local_pool::block_on::{{closure}}
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  56: futures_executor::local_pool::run_executor::{{closure}}
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:68
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262
  58: std::thread::local::LocalKey<T>::with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239
  59: futures_executor::local_pool::run_executor
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:64
  60: futures_executor::local_pool::block_on
             at /home/nolan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.19/src/local_pool.rs:295
  61: nu::main
             at src/main.rs:68
  62: std::rt::lang_start::{{closure}}
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
  63: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  64: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  65: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  66: std::panicking::try
             at src/libstd/panicking.rs:270
  67: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  68: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  69: std::rt::lang_start
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
  70: main
  71: __libc_start_main
  72: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jonathandturner** [comment]
That *is* strange. It's almost as if Nu is being run inside of an environment that is causing our terminal support to fail.

To get a better picture of what might be happening, can you share what terminal you're running in? Also are you in Xorg, the console, or something else?

**Comment by ndarilek** [comment]
I'm in gnome-terminal running under xorg using fish as my primary shell. 
I've started Nu from Fish, Bash, and directly via gnome-terminal with it 
set as a custom command and the login shell box checked. The system is 
Fedora 31, GNOME 3.34, with all updates applied.


Happy to provide any further details.

**Comment by jonathandturner** [comment]
@ndarilek - I'm trying to see if I can get a similar environment here to test with. I built a Fedora 31 image (which is pretty cool, I haven't used Fedora in a while).

I've got GNOME 3.34.1. 64-bit. It's in a KVM virtualization (qemu). From inside of GNOME Terminal 3.34.1, I built the latest Nu from master with the latest stable Rust (1.40), and then typed `ls`:

![Screenshot from 2020-01-02 11-49-47](https://user-images.githubusercontent.com/547158/71647088-5386c500-2d56-11ea-9953-e05e10350f4c.png)

This is from the default `bash` install that Fedora came with. I also installed `fish` and ran from inside that and it also seemed to work okay.

I'm happy to try things in this image to see if we can get a repro.

**Comment by ndarilek** [comment]
Think I figured it out. In config.toml, an `[env]` section without a 
`TERM` variable defined triggers it for me.

**Comment by jonathandturner** [comment]
Thanks for letting us know. That would be a good thing for us to detect in the future so people can avoid the same issue

**Comment by ndarilek** [comment]
What should I even set TERM to? I've rarely needed to explicitly set it, 
and then only to deal with a misbehaving program or to remove unwanted 
escape sequences from stdout/stderr. I'm not currently setting it in 
Fish, nor do I see anything in /etc/skel that sets it. I'd assume that 
whatever logic gives TERM a default value in other shells would be true 
in Nu as well, since nothing I explicitly set will be universally true.


Thanks.

**Comment by jonathandturner** [comment]
@ndarilek - if you remove `env` from config, and then do `echo $nu.env | get TERM` you should see what is available from outside of nu.

Here's what I see:
```
echo $nu.env | get TERM
xterm-256color
```

**Comment by ndarilek** [comment]
Right, I have that value, but would that be accurate on a plain console 
not running in an X session?


It seems like something, somewhere, is able to autodetect a sane TERM 
value based on arbitrary factors of some sort. Nowhere is it ever set 
manually, unless I'm missing something. Seems to me like Nu should 
either incorporate or leverage this logic somewhere. Otherwise, with it 
as my login shell, how can I correctly set a single value that works 
across gnome-terminal, console logins, SSH logins from arbitrary hosts, 
etc.? Maybe this value works just fine, but I think it's odd that I have 
to explicitly set it in Nu and nowhere else, particularly if Nu is 
claiming to be a more usable shell than its competition.

**Comment by jonathandturner** [comment]
Yes, that's a very good point. There are probably a set of environment variables we should receive from the host and/or calculate ourselves before giving the user control.

I found this: https://en.wikipedia.org/wiki/Environment_variable which lists TERM, but I'm also looking for a more standard list.

**Comment by thegedge** [comment]
`ls` can work in other shells without having `TERM` set, so perhaps we could too? If not, we should at least warn, as @jonathandturner already mentioned.
