### ISSUE TITLE
`nu --lsp` crash with "Byte index out of bounds" error

### ISSUE THREAD

**Issue by fredericgiquel** [nushell/nushell#11530]
### Describe the bug

Thanks for fixing the issue so quickly yesterday (https://github.com/nushell/nushell/issues/11522).

But I found another crash that occurs with both 0.89.0 version and last commit in main branch. It can be reliably reproduced.

### How to reproduce

Analyze the following file with LSP server:
```nu
#!/usr/bin/env nu

def mycommand []:
```
The crash occurs when entering the colon to define the type of input and output of the command. If we enter the first letter of the type of pipeline input ("s" for "string" for example), the server doesn't crash anymore.

### Expected behavior

No crash.

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.89.1                                    |
| branch             | main                                      |
| commit_hash        | 387c5462e9945d8d9188067c555c6b033ad573e2  |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)       |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu           |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)       |
| build_time         | 2024-01-12 19:12:04 +01:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

### Additional context

Backtrace obtained with "RUST_BACKTRACE=full"

```
thread 'main' panicked at /home/fred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.1/src/rope.rs:654:41:
called `Result::unwrap()` on an `Err` value: Byte index out of bounds: byte index 18446744073709452591, Rope/RopeSlice byte length 32
stack backtrace:
   0:     0x562a97997361 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
   1:     0x562a96d4375c - core::fmt::write::hb8eaf5a8e45a738e
   2:     0x562a97991bae - std::io::Write::write_fmt::h9663fe36b2ee08f9
   3:     0x562a97997144 - std::sys_common::backtrace::print::h1360e9450e4f922a
   4:     0x562a9799e3a3 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
   5:     0x562a9799e0ef - std::panicking::default_hook::h6d75f5747cab6e8d
   6:     0x562a9799ea0a - std::panicking::rust_panic_with_hook::h57e78470c47c84de
   7:     0x562a9799e7b4 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
   8:     0x562a9799cf96 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
   9:     0x562a9799e532 - rust_begin_unwind
  10:     0x562a96ca6fc3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
  11:     0x562a96ca73aa - core::result::unwrap_failed::hccb456d39e9c31fc
  12:     0x562a97358dc4 - ropey::rope::Rope::byte_to_line::hfe78e3895fe0c25d
  13:     0x562a9735fa8d - nu_lsp::LanguageServer::span_to_range::h443134df9fef7105
  14:     0x562a9735cfec - nu_lsp::LanguageServer::serve_requests::h2b7418be6b71a9b3
  15:     0x562a96e29ed7 - nu::main::hc20b692e5f86cf3a
  16:     0x562a96e36cf9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd02c43dcd84d6743
  17:     0x562a96e37547 - std::rt::lang_start::{{closure}}::h318e61a12fb9dac7
  18:     0x562a97987dab - std::rt::lang_start_internal::hc0b4e50f058f62ce
  19:     0x562a96e2bc35 - main
  20:     0x7fbd133666ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7fbd13366785 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  22:     0x562a96cdc061 - _start
  23:                0x0 - <unknown>
```

**Comment by houdinihacker** [comment]
Same here. I'll post a few details from my end in case they would be useful.

```
[ERROR][2024-02-06 12:04:27] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/nu"	"stderr"	"thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.1/src/rope.rs:690:41:\ncalled `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 8018, Rope/RopeSlice char length 2757\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

LSP setup:
```
nulsp = function()
  local nvim_lsp = require "lspconfig"
  return {
    cmd = { "nu", "--lsp" },
    filetypes = { "nu" },
    root_dir = nvim_lsp.util.root_pattern("mod.nu", ".git"),
  }
end
```

**Comment by fredericgiquel** [comment]
For information, the crash still occurs with 0.90.1 version.

**Comment by Tyarel8** [comment]
I am having the same error with the helix default config (24.3 (2cadec0b)) and nu version 0.91.0
```
2024-03-30T18:25:23.063 helix_lsp::transport [ERROR] nu-lsp err <- "Error:   × Main thread panicked.\n"
2024-03-30T18:25:23.064 helix_lsp::transport [ERROR] nu-lsp err <- "  ├─▶ at C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-\n"
2024-03-30T18:25:23.064 helix_lsp::transport [ERROR] nu-lsp err <- "  │   6f17d22bba15001f\\ropey-1.6.1\\src\\rope.rs:654:41\n"
2024-03-30T18:25:23.064 helix_lsp::transport [ERROR] nu-lsp err <- "  ╰─▶ called `Result::unwrap()` on an `Err` value: Byte index out of bounds:\n"
2024-03-30T18:25:23.065 helix_lsp::transport [ERROR] nu-lsp err <- "      byte index 124995, Rope/RopeSlice byte length 15097\n"
2024-03-30T18:25:23.065 helix_lsp::transport [ERROR] nu-lsp err <- "  help: set the `RUST_BACKTRACE=1` environment variable to display a\n"
2024-03-30T18:25:23.065 helix_lsp::transport [ERROR] nu-lsp err <- "        backtrace.\n"
```
