### ISSUE TITLE
Autocompletion does not correctly handle Unicode characters.

### ISSUE THREAD

**Issue by Matheritasiv** [nushell/nushell#11916]
### Describe the bug

If there are at least two files containing Chinese characters in the current directory, autocomplete immediately after a quotation mark will cause panic.

### How to reproduce

```
> touch "汉" "字"
> "
```
then press `<TAB>`, it ends with
```
thread 'main' panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\str\mod.rs:658:13:
byte index 1 is not a char boundary; it is inside '字' (bytes 0..3) of `字`
```

### Expected behavior

it shows completion
```
字\    汉\
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:25:09 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by devurandom** [comment]
With the `test/` directory extracted from attached [test.tar.gz](https://github.com/user-attachments/files/15552049/test.tar.gz), I type `ls test/b<TAB>f<TAG>`, and get following panic:
```
❯ ls `test/behörde abcdefghijklmnopqrstuvwxzy/`fError:   × Main thread panicked.
  ├─▶ at /build/rustc-1.77.2-src/library/core/src/str/mod.rs:666:21
  ╰─▶ byte index 44 is not a char boundary; it is inside 'ü' (bytes 43..45) of ``test/behörde abcdefghijklmnopqrstuvwxzy/führung-1-abcdefghijklmnopqrstuvwxzy.txt``
```

Might be related to https://github.com/nushell/nushell/issues/12680.

**Comment by ysthakur** [comment]
Good find. Here's the full error, for anyone working on this:
```
Error:   × Main thread panicked.
  ├─▶ at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/str/mod.rs:666:21
  ╰─▶ byte index 1 is not a char boundary; it is inside '汉' (bytes 0..3) of `汉`
         0: 0x55b7cd17c844 - rust_begin_unwind
         1: 0x55b7cc3640c5 - core::panicking::panic_fmt::ha6effc2775a0749c
         2: 0x55b7cc452483 - core::str::slice_error_fail_rt::hae2b0a3e014351e1
         3: 0x55b7cc3648d7 - core::str::slice_error_fail::he2ff12236fb0c056
         4: 0x55b7cd054e13 - reedline::menu::columnar_menu::ColumnarMenu::create_string::h173ace5a253750d2
         5: 0x55b7cd053f75 - <alloc::string::String as core::iter::traits::collect::FromIterator<alloc::string::String>>::from_iter::hecf5c02b6c55ea55
         6: 0x55b7cd057074 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::menu_string::h42e4726c7b668ff1
         7: 0x55b7cd033cbd - reedline::painting::painter::Painter::print_menu::h98f9b57d24d3178d
         8: 0x55b7cd0337b2 - reedline::painting::painter::Painter::repaint_buffer::ha8023ce29fb25a29
         9: 0x55b7cd044650 - reedline::engine::Reedline::repaint::hfbea710aa5dc01b3
        10: 0x55b7cd040d39 - reedline::engine::Reedline::read_line::he0c6a485b0275b49
        11: 0x55b7cc5da19d - nu_cli::repl::loop_iteration::h2a900cdb9fda3c5d
        12: 0x55b7cc5d3bc0 - std::panicking::try::h83faea6e86ff63a6
        13: 0x55b7cc5c9e25 - nu_cli::repl::evaluate_repl::h2cbd7f94758d9363
        14: 0x55b7cc557609 - nu::run::run_repl::h7fd846557bd2b186
        15: 0x55b7cc54530f - nu::main::h4b769ded3225d7ac
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by munzirtaha** [comment]
Today I met across this bug
```
$ cd `Library/Linux & UNIX/`Error:   × Main thread panicked.
  ├─▶ at /usr/src/debug/rust/rustc-1.82.0-src/library/core/src/str/mod.rs:639:21
  ╰─▶ byte index 23 is not a char boundary; it is inside 'ع' (bytes 22..24) of ``Library/Linux & UNIX/عربي/``
         0: 0x5b26178a621a - <unresolved>
         1: 0x5b261789367c - <unresolved>
         2: 0x5b2617890c25 - <unresolved>
         3: 0x5b26177d95eb - <unresolved>
         4: 0x5b26186045c3 - <unresolved>
         5: 0x5b2618604b68 - <unresolved>
         6: 0x5b26178a6058 - <unresolved>
         7: 0x5b261860d8cd - <unresolved>
         8: 0x5b261860d5a7 - <unresolved>
         9: 0x5b261860bee9 - <unresolved>
        10: 0x5b261860d234 - <unresolved>
        11: 0x5b261770df53 - <unresolved>
        12: 0x5b26177dcc5d - <unresolved>
        13: 0x5b261770e6ea - <unresolved>
        14: 0x5b26184ce443 - <unresolved>
        15: 0x5b261850245b - <unresolved>
        16: 0x5b26184bf20d - <unresolved>
        17: 0x5b26184d0434 - <unresolved>
        18: 0x5b26184d4bae - <unresolved>
        19: 0x5b26184d4655 - <unresolved>
        20: 0x5b26184e46d6 - <unresolved>
        21: 0x5b26184e0e5a - <unresolved>
 ```

**Comment by ysthakur** [comment]
This should be fixed by https://github.com/nushell/reedline/pull/886 (prefix matching) and https://github.com/nushell/reedline/pull/918 (fuzzy matching)
