### ISSUE TITLE
'echo aa | first 2' panics

### ISSUE THREAD

**Issue by ilyash-b** [nushell/nushell#1327]
**Describe the bug**
`echo aa | first 2` causes `thread 'main' panicked at 'Expected command textview', src/libcore/option.rs:1166:5`

**To Reproduce**
1. `docker run -e RUST_BACKTRACE=full -it quay.io/nushell/nu`
2. `echo aa | first 2`

**Expected behavior**
Display any reasonable output

**Configuration (please complete the following information):**
 - OS: MacOS 
 - Version Catalina 10.15.2
(The OS version is probably irrelevant because nushell is running in docker)

**Stack trace**
```
thread 'main' panicked at 'Expected command textview', src/libcore/option.rs:1166:5
stack backtrace:
   0:     0x561c166eda82 - backtrace::backtrace::libunwind::trace::h5b672ea0408452ed
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x561c166eda82 - backtrace::backtrace::trace_unsynchronized::h15bbd54ccd30253c
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x561c166eda82 - std::sys_common::backtrace::_print::hbf32a02f9894e727
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x561c166eda82 - std::sys_common::backtrace::print::h127d55b04a8ca638
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x561c166eda82 - std::panicking::default_hook::{{closure}}::h41569aa1cabd15f2
                               at src/libstd/panicking.rs:200
   5:     0x561c166ed766 - std::panicking::default_hook::h2471d95c3baf1435
                               at src/libstd/panicking.rs:214
   6:     0x561c166ee1d5 - std::panicking::rust_panic_with_hook::hdb74b1d76abfd8b2
                               at src/libstd/panicking.rs:477
   7:     0x561c166edd72 - std::panicking::continue_panic_fmt::h7aad477695105344
                               at src/libstd/panicking.rs:384
   8:     0x561c166edc66 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x561c167103da - core::panicking::panic_fmt::h2a7634fba4671b05
                               at src/libcore/panicking.rs:85
  10:     0x561c16710447 - core::option::expect_failed::hf3504a5bad2b6853
                               at src/libcore/option.rs:1166
  11:     0x561c1630b5df - nu::commands::command::RunnableContext::expect_command::h6ba14629448c63c8
  12:     0x561c1626b391 - std::future::set_task_context::hd44e0f831b54665f
  13:     0x561c16340062 - <futures_async_stream::stream::GenStream<U,T> as futures_core::stream::Stream>::poll_next::h1161302ff2d95ef1
  14:     0x561c161ed4f1 - std::future::poll_with_tls_context::h47a8312cbb867a44
  15:     0x561c161e6058 - nu::cli::cli::{{closure}}::h375e0b35c5460c7a
  16:     0x561c1620496f - std::thread::local::LocalKey<T>::with::h776fbcc9f9a2056b
  17:     0x561c162114f9 - nu::main::h23eab4d5820ea9fb
  18:     0x561c162119f3 - std::rt::lang_start::{{closure}}::h874db1f73dcf61b6
  19:     0x561c166edc03 - std::rt::lang_start_internal::{{closure}}::h4e292f977b47ab02
                               at src/libstd/rt.rs:49
  20:     0x561c166edc03 - std::panicking::try::do_call::haf6204e4b28c6f49
                               at src/libstd/panicking.rs:296
  21:     0x561c166f7f6a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  22:     0x561c166ee78d - std::panicking::try::had9b9f600586126b
                               at src/libstd/panicking.rs:275
  23:     0x561c166ee78d - std::panic::catch_unwind::h4f34d0c32a79bb69
                               at src/libstd/panic.rs:394
  24:     0x561c166ee78d - std::rt::lang_start_internal::h95e43a3bff5764bd
                               at src/libstd/rt.rs:48
  25:     0x561c162116c2 - main
  26:     0x7f6b079da09b - __libc_start_main
  27:     0x561c161d622a - _start
  28:                0x0 - <unknown>
```

**Comment by thegedge** [comment]
Same configuration here. I see the issue in docker, but not when running directly in OSX.

**Comment by thegedge** [comment]
So this is an issue with the dockerfile, which is running 0.2.0 (which had panics everywhere!). We have automatic docker push on release, but it hasn't been working in a while. We'll definitely take care of that as soon as possible.
