### ISSUE TITLE
Exponential algorithmic complexity on parsing nested brackets

### ISSUE THREAD

**Issue by anka-213** [nushell/nushell#13944]
### Describe the bug

This is similar to https://github.com/nushell/nushell/pull/10439. Found by using the fuzzer with a timeout:

```
cargo fuzz run parse out seeds -- -timeout=20 
```

### How to reproduce

Try parsing this file

```
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
$a = { |
```

After around 30 seconds and 2GB of memory use, you should get a parse error.

### Expected behavior

Parse in linear time or at worst quadratic.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.98.1                                      |
| major              | 0                                           |
| minor              | 98                                          |
| patch              | 1                                           |
| branch             | fix-9072                                    |
| commit_hash        | 4e2e125b5b55cab5e9d9322b2a6135f5bf41c314    |
| build_os           | macos-x86_64                                |
| build_target       | x86_64-apple-darwin                         |
| rust_version       | rustc 1.83.0-nightly (2bd1e894e 2024-09-26) |
| rust_channel       | nightly-x86_64-apple-darwin                 |
| cargo_version      | cargo 1.83.0-nightly (eaee77dc1 2024-09-19) |
| build_time         | 2024-09-27 09:58:01 +02:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash                      |
| installed_plugins  |                                             |

**Comment by anka-213** [comment]
<details>
<summary>
Here's a stack trace during the timeout
</summary>

```
target/x86_64-apple-darwin/release/parse -timeout=10 /Users/anka/projekt/not-mine/nushell/crates/nu-parser/fuzz/artifacts/mine/nonsense
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 798386385
INFO: Loaded 1 modules   (894308 inline 8-bit counters): 894308 [0x10f8f0b30, 0x10f9cb094), 
INFO: Loaded 1 PC tables (894308 PCs): 894308 [0x10f9cb098,0x1107706d8), 
target/x86_64-apple-darwin/release/parse: Running 1 inputs 1 time(s) each.
Running: /Users/anka/projekt/not-mine/nushell/crates/nu-parser/fuzz/artifacts/mine/nonsense
ALARM: working on the last Unit for 11 seconds
       and the timeout value is 10 (use -timeout=N to change)
==85406== ERROR: libFuzzer: timeout after 11 seconds
    #0 0x000112d58335 in __sanitizer_print_stack_trace+0x35 (librustc-nightly_rt.asan.dylib:x86_64h+0xeb335)
    #1 0x00010ed5bc9a in fuzzer::PrintStackTrace()+0x2a (parse:x86_64+0x102947c9a)
    #2 0x00010ed4e7d2 in fuzzer::Fuzzer::AlarmCallback()+0x112 (parse:x86_64+0x10293a7d2)
    #3 0x7fff6d19d5fc in _sigtramp+0x1c (libsystem_platform.dylib:x86_64+0x35fc)
    #4 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #5 0x00010c70246b in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0x132b (parse:x86_64+0x1002ee46b)
    #6 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #7 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #8 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #9 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #10 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #11 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #12 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #13 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #14 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #15 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #16 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #17 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #18 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #19 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #20 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #21 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #22 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #23 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #24 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #25 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #26 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #27 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #28 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #29 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #30 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #31 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #32 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #33 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #34 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #35 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #36 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #37 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #38 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #39 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #40 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #41 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #42 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #43 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #44 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #45 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #46 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #47 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #48 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #49 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #50 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #51 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #52 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #53 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #54 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #55 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #56 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #57 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #58 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #59 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #60 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #61 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #62 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #63 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #64 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #65 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #66 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #67 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #68 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #69 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #70 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #71 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #72 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #73 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #74 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #75 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #76 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #77 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #78 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #79 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #80 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #81 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #82 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #83 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #84 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #85 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #86 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #87 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #88 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #89 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #90 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #91 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #92 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #93 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #94 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #95 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #96 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #97 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #98 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #99 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #100 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #101 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #102 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #103 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #104 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #105 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #106 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #107 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #108 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #109 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #110 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #111 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #112 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #113 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #114 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #115 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #116 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #117 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #118 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #119 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #120 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #121 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #122 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #123 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #124 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #125 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #126 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #127 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #128 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #129 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #130 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #131 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #132 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #133 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #134 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #135 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #136 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #137 0x00010c6fc0a0 in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0x16f0 (parse:x86_64+0x1002e80a0)
    #138 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #139 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #140 0x00010c6dd47e in nu_parser::parser::parse_signature_helper::h94530154e905a756+0x1dfe (parse:x86_64+0x1002c947e)
    #141 0x00010c6fb77a in nu_parser::parser::parse_closure_expression::hb4c8b1827e9bdd88+0xdca (parse:x86_64+0x1002e777a)
    #142 0x00010c6bc886 in nu_parser::parser::parse_brace_expr::hc8478e0ee564b2d3+0x7a6 (parse:x86_64+0x1002a8886)
    #143 0x00010c6fdd26 in nu_parser::parser::parse_value::h5a988a83085eb6aa+0xe56 (parse:x86_64+0x1002e9d26)
    #144 0x00010c70a4a3 in nu_parser::parser::parse_math_expression::h45fa0d7ee1ddec5e+0xb73 (parse:x86_64+0x1002f64a3)
    #145 0x00010c70fb7f in nu_parser::parser::parse_expression::h8f65354436f72b46+0x166f (parse:x86_64+0x1002fbb7f)
    #146 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #147 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #148 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #149 0x00010c701c9c in nu_parser::parser::parse_assignment_expression::hf3246aec3d2d96e8+0xb5c (parse:x86_64+0x1002edc9c)
    #150 0x00010c70fc4a in nu_parser::parser::parse_expression::h8f65354436f72b46+0x173a (parse:x86_64+0x1002fbc4a)
    #151 0x00010c71eb19 in nu_parser::parser::parse_pipeline_element::hd63915961aa43eaf+0x2a9 (parse:x86_64+0x10030ab19)
    #152 0x00010c7177e4 in nu_parser::parser::parse_builtin_commands::hc7d9eb60bb59c9a6+0x27c4 (parse:x86_64+0x1003037e4)
    #153 0x00010c7203ef in nu_parser::parser::parse_block::h2df2f6e629faa41a+0x9bf (parse:x86_64+0x10030c3ef)
    #154 0x00010c72c8e8 in nu_parser::parser::parse::h0f024cfdca89fdb5+0xa78 (parse:x86_64+0x1003188e8)
    #155 0x00010c47c57e in parse::_::__libfuzzer_sys_run::h7a0889523c5ace71 parse.rs:17
    #156 0x00010c47bba2 in rust_fuzzer_test_input lib.rs:297
    #157 0x00010ed473a8 in std::panicking::try::do_call::h340b1c5d50bf71f9+0xe8 (parse:x86_64+0x1029333a8)
    #158 0x00010ed4d90e in __rust_try+0xe (parse:x86_64+0x10293990e)
    #159 0x00010ed4cf5c in LLVMFuzzerTestOneInput+0x11c (parse:x86_64+0x102938f5c)
    #160 0x00010ed5031d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x12d (parse:x86_64+0x10293c31d)
    #161 0x00010ed6ddc5 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long)+0xe5 (parse:x86_64+0x102959dc5)
    #162 0x00010ed73a8d in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1eed (parse:x86_64+0x10295fa8d)
    #163 0x00010ed83772 in main+0x22 (parse:x86_64+0x10296f772)
    #164 0x7fff6cfa4cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: libFuzzer: timeout
```
</details>

From this we can see the nested loop consisting of variations this:
```
      8 parse_math_expression
      9 parse_assignment_expression
     10 parse_signature_helper
     17 parse_block
     17 parse_builtin_commands
     17 parse_expression
     17 parse_pipeline_element
     18 parse_brace_expr
     18 parse_closure_expression
     19 parse_value
```
The numbers to the left is the number of occurrences in this specific stacktrace.
There are different paths that can be taken to reach back to `parse_value`, the above stacktrace is an example of one possible such path, which is how we get the exponential growth.

**Comment by fdncred** [comment]
That's crazy!

**Comment by IanManske** [comment]
:fearful:, related to #13750.
