### ISSUE TITLE
quickcheck parse failure

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1760]
**Describe the bug**
Quickcheck on CI found the following issue:

```
---- cli::tests::quickcheck_parse stdout ----
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=62, end=61', crates\nu-source\src\meta.rs:488:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=62, end=61', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=38, end=37', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=16, end=15', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=16, end=15', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=12, end=11', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=10, end=9', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=10, end=9', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=8, end=7', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at 'Can't create a Span whose end < start, start=8, end=7', crates\nu-source\src\meta.rs:488:9
thread 'cli::tests::quickcheck_parse' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ("=\u{0} =\u{a0}\u{0} \u{0}")
Error: "Can\'t create a Span whose end < start, start=8, end=7"', <::std::macros::panic macros>:2:4
```

**Comment by thegedge** [comment]
I guess the goal is to return an error instead of panic?
