### ISSUE TITLE
Nushell crashes when using date with an invalid strftime string

### ISSUE THREAD

**Issue by reillysiemens** [nushell/nushell#2398]
**Describe the bug**
Using the [`date` built-in](https://www.nushell.sh/commands/date.html) with an invalid [`strftime(3)`](https://linux.die.net/man/3/strftime) time causes Nushell to crash.

I mistakenly used the `date` with `%N` which formats nanosecond time in [`date(1)`](https://linux.die.net/man/1/date). I now see, however, that the docs say
```
  -f, --format <string>: report datetime in supplied strftime format
```
, which I assume references [`strftime(3)`](https://linux.die.net/man/3/strftime) or similar. `%N` is not a valid format for that function, but I still wouldn't expect the shell to panic when receiving an invalid format.

**To Reproduce**
1. Install Nu on Windows with `cargo install -f nu --features=stable`.
2. Run `nu`.
3. Run `date --format '%N'` within `nu`.
4. Repeat with similar nonsense strings such as `date --format '%q'`, etc.

**Expected behavior**
I expected Nushell to report an error, not to crash.

**Screenshots**
Windows Terminal 1.1.2233.0
<img width="801" alt="nushell-date-crash" src="https://user-images.githubusercontent.com/3084059/91013150-1cdb1480-e59c-11ea-9aab-6ea442e5cf93.png">

Here's the text of that stack trace, if it helps:
```c
C:\Users\tucker> with-env [RUST_BACKTRACE 'full'] { nu -c "date --format '%N'"}
thread 'main' panicked at 'a formatting trait implementation returned an error: Error', src\liballoc\fmt.rs:586:5
stack backtrace:
   0:     0x7ff6d027680e - git_odb_object_size
   1:     0x7ff6d029909c - git_odb_object_size
   2:     0x7ff6d026fffc - git_odb_object_size
   3:     0x7ff6d027a02b - git_odb_object_size
   4:     0x7ff6d0279c78 - git_odb_object_size
   5:     0x7ff6d027a806 - git_odb_object_size
   6:     0x7ff6d027a38f - git_odb_object_size
   7:     0x7ff6d0296410 - git_odb_object_size
   8:     0x7ff6d0296253 - git_odb_object_size
   9:     0x7ff6d028ed4b - git_odb_object_size
  10:     0x7ff6cf75afd7 - <unknown>
  11:     0x7ff6cfae4c3a - <unknown>
  12:     0x7ff6cf664524 - <unknown>
  13:     0x7ff6cf666cfa - <unknown>
  14:     0x7ff6cf66a88b - <unknown>
  15:     0x7ff6cf6629c5 - <unknown>
  16:     0x7ff6cf663873 - <unknown>
  17:     0x7ff6cf67fed5 - <unknown>
  18:     0x7ff6cf62b559 - <unknown>
  19:     0x7ff6cf67d42d - <unknown>
  20:     0x7ff6cf62b76a - <unknown>
  21:     0x7ff6d027aaf6 - git_odb_object_size
  22:     0x7ff6cf67e047 - <unknown>
  23:     0x7ff6d036cda5 - git_proxy_options_init
  24:     0x7ff8ecf77bd4 - BaseThreadInitThunk
  25:     0x7ff8eecece51 - RtlUserThreadStart
C:\Users\tucker>
```

**Configuration:**
 - OS: Windows 10 Pro 1903 Build 18362.1016
 - Nu version: 0.18.1
 - Optional features: Stable

**Comment by dmeijboom** [comment]
This happens because in `date_to_value` (where the actual formatting stuff happens) we use the `format!` macro which can panic if the formatter returns an error. I'll make a PR to gracefully handle this and return an error instead. Thanks!

**Comment by bwinton** [comment]
I just ran into something that seems related…
```
🌓 🕛 bwinton@12:02/Desktop/ $ RUST_BACKTRACE=full nu -c "seq date --days 72 -o '%MM %d'"
thread 'main' panicked at 'a formatting trait implementation returned an error: Error', library/alloc/src/fmt.rs:578:28
stack backtrace:
   0:        0x10382e933 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
   1:        0x102fa67ae - core::fmt::write::h14dac7cadec1cc70
   2:        0x10382dc1a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
   3:        0x10384bbf9 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
   4:        0x10384c7ac - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
   5:        0x10382ecda - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
   6:        0x10382ec48 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
   7:        0x10384a610 - _rust_begin_unwind
   8:        0x1038fb48f - core::panicking::panic_fmt::h4f63e4f6b62b650b
   9:        0x1038fb405 - core::result::unwrap_failed::hc2a56d017349147e
  10:        0x102f2a0b1 - alloc::fmt::format::h91236501d84c8dd2
  11:        0x1031719a3 - nu_command::commands::seq_dates::seq_dates::h7a46726b786dbef3
  12:        0x10316d0ea - nu_engine::whole_stream_command::WholeStreamCommand::run::hecf27f95543f9724
  13:        0x103577a2b - nu_engine::whole_stream_command::Command::run::h306e50fd7f43cf57
  14:        0x103571bed - nu_engine::evaluation_context::EvaluationContext::run_command::h1954fb2c8b314a59
  15:        0x103574901 - nu_engine::evaluate::internal::run_internal_command::hae842a2f6fd56a5b
  16:        0x103571eb3 - nu_engine::evaluate::block::run_pipeline::h8616692742276990
  17:        0x10357089f - nu_engine::evaluate::block::run_block::hc032ae046483b5a5
  18:        0x10359e2b5 - nu_engine::script::process_script::h6e61124a3c772148
  19:        0x10359d47d - nu_engine::script::run_script_standalone::h9719cdbe4dbfda7c
  20:        0x102ffea4d - nu_cli::cli::run_script_file::h4d7cd98a6941a2e3
  21:        0x102f14492 - nu::main::hccf9e84cb2916794
  22:        0x102f07fba - std::sys_common::backtrace::__rust_begin_short_backtrace::h5db9a6ed2a0c4f31
  23:        0x102f1634b - _main
🌓 🕛 bwinton@12:02/Desktop/ $ nu --version
nushell 0.32.0
```

Does the patch need some updating? Would you like me to file a new bug?

**Comment by bwinton** [comment]
`RUST_BACKTRACE=full nu -c "seq date --days 72 -o '%MM %d'"`
still fails in Nushell 0.33.0, so we should probably leave this open, I think…

**Comment by hustcer** [comment]
`date now | date format '%N'` still doesn't work
