### ISSUE TITLE
completion hangs sometimes

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2426]
**Describe the bug**
I've noticed, by accident, that if I'm in Ubuntu 20.04/WSL2 and I do the steps below, nu hangs for 20-40 seconds.

**To Reproduce**
1. Be in Linux or WLS2
2. from any nu prompt type `..\in<tab>`
3. you should now be hung up
4. neither ctrl+\ nor ctrl+c do anything until the 20-40 seconds elapses

**Expected behavior**
since there is no file name up a dir that matches `..\in`, not to mention `\` is the wrong slash in Linux. I expected it to fail instantly.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows running WSL2
```lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
Linux 4.19.104-microsoft-standard x86_64
```

 - Nu version (you can use the `version` command to find out): 
 - Optional features (if any):

|version|commit_hash|nushell_features|
|-|-|-|
|0.18.2|a64cfb6285a84cd5cffc10e36f4a398688abe6e6|default|

** backtrace
```
thread 'main' panicked at 'expect_string assumes that the value must be a string', crates/nu-protocol/src/value.rs:123:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: std::panicking::begin_panic
  12: nu_protocol::value::UntaggedValue::expect_string
  13: nu_cli::cli::cli::{{closure}}
  14: std::thread::local::LocalKey<T>::with
  15: futures_executor::local_pool::block_on
  16: nu::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  20: std::panicking::try
             at src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by thegedge** [comment]
Okay, I can't reproduce this in an Ubuntu docker container. I'm not sure how to approach this right now. I'll try to get a Windows VM up and running with everything sometime soon, but I may not be able to get to this before the next release.

@fdncred does this happen only in WSL2, or do you see something similar happen in Windows too?

**Comment by fdncred** [comment]
in wsl2 with this version, i can't reproduce it any longer. may be another accidental fix?
```
───┬─────────┬──────────────────────────────────────────┬───────────────────────────
 # │ version │               commit_hash                │     nushell_features
───┼─────────┼──────────────────────────────────────────┼───────────────────────────
 0 │ 0.18.2  │ f078aacc25dfb9741f0c747f5e3a040cf58373cf │ default, clipboard, trash
───┴─────────┴──────────────────────────────────────────┴───────────────────────────
```

i haven't seen it hang in windows yet.

**Comment by thegedge** [comment]
ᕕ( ᐛ )ᕗ

Odd. I'll close, but reopen if you observe it again.
