### ISSUE TITLE
Thread panicked when running `ps` with `first`

### ISSUE THREAD

**Issue by jz448** [nushell/nushell#2768]
**Describe the bug**
Running `ps` with `first` causes thread 'main' to panic.

**To Reproduce**
Steps to reproduce the behaviour:

```
> ps | first 5
───┬─────┬──────────────────────┬──────────┬────────┬─────────┬──────────
 # │ pid │         name         │  status  │  cpu   │   mem   │ virtual  
───┼─────┼──────────────────────┼──────────┼────────┼─────────┼──────────
 0 │   1 │ systemd              │ Sleeping │ 0.0000 │ 13.0 MB │ 173.7 MB 
 1 │   2 │ kthreadd             │ Sleeping │ 0.0000 │     0 B │      0 B 
 2 │   3 │ rcu_gp               │ Idle     │ 0.0000 │     0 B │      0 B 
 3 │   4 │ rcu_par_gp           │ Idle     │ 0.0000 │     0 B │      0 B 
 4 │   6 │ kworker/0:0H-kblockd │ Idle     │ 0.0000 │     0 B │      0 B 
───┴─────┴──────────────────────┴──────────┴────────┴─────────┴──────────
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:993:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: std::io::stdio::print_to
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/stdio.rs:993
   3: std::io::stdio::_print
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/stdio.rs:1005
   4: nu_plugin::jsonrpc::send_response
   5: nu_plugin_core_ps::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Expected behavior**
Output the result and exit normally (i.e., without panicking).

**Configuration (please complete the following information):**
 - OS: Ubuntu 20.10
 - Nu version: 0.23.0

**Comment by bailey-layzer** [comment]
Looks like a long-standing Rust issue: https://github.com/rust-lang/rust/issues/46016. There are a couple of suggested workarounds which I couldn't get working, but look pretty simple for someone who's familiar with libc.
