### ISSUE TITLE
Crash while typing

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2933]
**Describe the bug**
panic while typing

**To Reproduce**
1. type `alias fg_blue = echo $(ansi -e '34m')`
2. type `fg_blue` and watch the crash as you type the e
3.

**Expected behavior**
not crash

**Screenshots**
```
01/13/2021 09:48:39.976 AM ¯\_(ツ)_/¯ ▶ alias fg_blue = echo $(ansi -e '34m')
01/13/2021 09:48:41.743 AM ¯\_(ツ)_/¯ ▶ fg_bluthread 'main' panicked at 'index out of bounds: the len is 7 but the index is 7', crates\nu-engine\src\shell\painter.rs:49:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101]
```

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

|key|value|
|-|-|
|version|0.25.2|
|branch|main|
|short_commit|d06f457b|
|commit_hash|'d06f457b2a7dee3acc71ecd0dc8b6a34afbfc5d8'|
|commit_date|2021-01-11 22:59:53|
|build_os|windows-x86_64|
|rust_version|rustc 1.49.0 (e1884a8e3 2020-12-29)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.49.0 (d00d64df9 2020-12-05)|
|pkg_version|0.25.2|
|build_time|2021-01-12 07:29:22|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline, term, trash, uuid, which, zip|

**Comment by jonathandturner** [comment]
I just tried this in Linux, and I don't see a repro. I wonder if it's platform related?

**Comment by kubouch** [comment]
I reproduced it on Linux, newest main built right now (ebc4694).

**Comment by jonathandturner** [comment]
I just posted a PR #2934 that should change how alias gets its coloring. After this lands, can try again to see if it still happens?

**Comment by jonathandturner** [comment]
Oops, nevermind. I don't think the fix I did for #2934 is going to work. Need to rethink it.

**Comment by jonathandturner** [comment]
I can repro now. I had misread the repro steps. So it's not the `alias` command failing, it's the running of the alias itself.

**Comment by fdncred** [comment]
@jonathandturner correct. I can type the alias and it's accepted but when i type the name of the alias, as i'm tying, it pukes. granted, my alias may not be correct, but still, it shouldn't puke like this.

**Comment by unrelentingtech** [comment]
This still happens, I've just hit this with `alias whatever = (if not true {})`

**Comment by unrelentingtech** [comment]
hm, so actually that issue came back as #6251, no longer seeing that with the fix for that one.

**Comment by icp1994** [comment]
I'm having a similar crash which seems related so putting here for now:

#### To Reproduce

"alias gs = git switch" in `config.nu`
`$ gs main;<SPACE><TAB>`

```
thread 'main' panicked at 'slice index starts at 17 but ends at 9', library/core/src/slice/index.rs:92:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
```

**Comment by merelymyself** [comment]
hrm, not sure if its linked to the same thing. It doesn't crash when I type the `e` - however, it DOES crash when I try to autocomplete it. 

```
~/CodingProjects/nushell〉alias fg_blue = echo $(ansi -e '34m')
~/CodingProjects/nushell〉fg_blue                       09/29/2022 05:37:25 PM
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #1:1:1]
 1 │ alias fg_blue = echo $(ansi -e '34m')
   ·                      ────────┬───────
   ·                              ╰── expected valid variable name
   ╰────

~/CodingProjects/nushell〉fg_bluethread 'main' panicked at 'attempt to subtract with overflow', crates/nu-cli/src/completions/variable_completions.rs:50:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: <nu_cli::completions::variable_completions::VariableCompletion as nu_cli::completions::base::Completer>::fetch
             at ./crates/nu-cli/src/completions/variable_completions.rs:50:20
   4: nu_cli::completions::completer::NuCompleter::process_completion
             at ./crates/nu-cli/src/completions/completer.rs:52:13
   5: nu_cli::completions::completer::NuCompleter::completion_helper
             at ./crates/nu-cli/src/completions/completer.rs:184:36
   6: <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete
             at ./crates/nu-cli/src/completions/completer.rs:374:9
   7: <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/menu/columnar_menu.rs:544:27
   8: <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::can_partially_complete
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/menu/columnar_menu.rs:474:13
   9: reedline::menu::ReedlineMenu::can_partially_complete
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/menu/mod.rs:165:17
  10: reedline::engine::Reedline::handle_editor_event
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/engine.rs:723:32
  11: reedline::engine::Reedline::handle_editor_event
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/engine.rs:980:27
  12: reedline::engine::Reedline::handle_event
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/engine.rs:586:13
  13: reedline::engine::Reedline::read_line_helper
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/engine.rs:563:23
  14: reedline::engine::Reedline::read_line
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.12.0/src/engine.rs:440:22
  15: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:340:21
  16: nu::main
             at ./src/main.rs:358:31
  17: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by icp1994** [comment]
@valpackett I updated to 0.70 and it works fine now.

**Comment by fdncred** [comment]
yay, it finally works!
