### ISSUE TITLE
Nu panicks in `math.round` on a large decimal value

### ISSUE THREAD

**Issue by bshashank** [nushell/nushell#3130]
**Describe the bug**
Nu panicks when asked to round a large decimal value, 40 decimal digits seem to do it.

**To Reproduce**
```
❯ RUST_BACKTRACE=1 nu
Welcome to Nushell 0.27.1 (type 'help' for more info)
> echo 18.137254478007414228992766548677201234 | math round
18
> echo 18.1372544780074142289927665486772012345 | math round
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bigdecimal-0.2.0/src/lib.rs:596:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: bigdecimal::BigDecimal::round
   4: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
   5: <futures_util::stream::stream::take_while::TakeWhile<St,Fut,F> as futures_core::stream::Stream>::poll_next
   6: nu_command::commands::autoview::command::autoview::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: nu_cli::cli::cli::{{closure}}
  10: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**
```
> echo 18.13725447800741422899276654867720123456789 | math round
18
```

**Configuration:**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                                 Column1                                                  
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.27.1                                                                                                   
  1 │ short_commit       │ 7dc1d6a3                                                                                                 
  2 │ commit_hash        │ 7dc1d6a350b7d2acf1b5786c439e39c142bc591e                                                                 
  3 │ commit_date        │ 2021-02-19 01:24:27                                                                                      
  4 │ build_os           │ linux-x86_64                                                                                             
  5 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)                                                                      
  6 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)                                                                
  7 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)                                                                      
  8 │ pkg_version        │ 0.27.1                                                                                                   
  9 │ build_time         │ 2021-02-19 04:18:34                                                                                      
 10 │ build_rust_channel │ release                                                                                                  
 11 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip 
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by jonathandturner** [comment]
@bshashank - long time, no see! 

Thanks for the report :)
