### ISSUE TITLE
Crash in diagnostic emitter

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#323]
Paste this into the prompt:

```
       | activation --service-request-channel-token=11913582771556664742 --renderer-client-id=3 --shared- 
    |       |          |       | files=v8_context_snapshot_data:100,v8_natives_data:101 
 13 | 2925  | Sleeping | 2.15  | /usr/share/code/code/usr/share/code/resources/app/out/bootstrap-fork--type=watcherService 
 14 | 11810 | Sleeping | 1.23  | /usr/lib/firefox/firefox-contentproc-childID10-isForBrowser-prefsLen8352-prefMapSize185284-parentBuildID20190706141545- 
    |       |          |       | greomni/usr/lib/firefox/omni.ja-appomni/usr/lib/firefox/browser/omni.ja-appdir/usr/lib/firefox/browser10934truetab 
 15 | 11034 | Sleeping | 1.16  | /usr/lib/firefox/firefox-contentproc-childID2-isForBrowser-prefsLen6058-prefMapSize185284-parentBuildID20190706141545- 
    |       |          |       | greomni/usr/lib/firefox/omni.ja-appomni/usr/lib/firefox/browser/omni.ja-appdir/usr/lib/firefox/browser10934truetab 
 16 | 11393 | Sleeping | 5.87  | /usr/lib/firefox/firefox-contentproc-childID4-isForBrowser-prefsLen7155-prefMapSize185284-parentBuildID20190706141545- 
    |       |          |       | greomni/usr/lib
```

The result (for me, in Linux) is a crash. I've tried to catch this crash, but wasn't able to.  It seems related to sending the error reporting:

```
  11: core::option::Option<T>::expect
             at /rustc/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libcore/option.rs:345
  12: language_reporting::models::SourceLine<Files>::after_marked
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/models.rs:113
  13: language_reporting::components::SourceCodeLine::{{closure}}
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/components.rs:96
  14: core::ops::function::FnOnce::call_once
             at /rustc/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libcore/ops/function.rs:235
  15: <render_tree::helpers::Section as render_tree::component::BlockComponent>::append
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/helpers.rs:143
  16: <render_tree::component::CurriedBlockComponent<B,Block> as render_tree::render::Render>::render
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:23
  17: language_reporting::components::SourceCodeLine
             at ./<::render_tree::macros::concat_trees macros>:5
  18: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  19: language_reporting::components::Body
             at ./<::render_tree::macros::concat_trees macros>:5
  20: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  21: language_reporting::components::Diagnostic::{{closure}}
             at ./<::render_tree::macros::concat_trees macros>:5
  22: <render_tree::helpers::Section as render_tree::component::BlockComponent>::append
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/helpers.rs:143
  23: <render_tree::component::CurriedBlockComponent<B,Block> as render_tree::render::Render>::render
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:23
  24: language_reporting::components::Diagnostic
             at ./<::render_tree::macros::concat_trees macros>:5
  25: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  26: render_tree::render::Render::into_fragment
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/render.rs:68
  27: language_reporting::emitter::DiagnosticWriter<W>::emit
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/emitter.rs:36
  28: language_reporting::emitter::emit
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/emitter.rs:20
  29: nu::cli::cli::{{closure}}::{{closure}}
             at ./src/cli.rs:267
  30: std::panicking::try::do_call
             at /rustc/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libstd/panicking.rs:296
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: std::panicking::try
             at /rustc/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libstd/panicking.rs:275
  33: std::panic::catch_unwind
             at /rustc/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libstd/panic.rs:394
  34: nu::cli::cli::{{closure}}
             at ./src/cli.rs:266
```

**Comment by androbtech** [comment]
my result on macOS:

```
thread 'main' panicked at 'begin <= end (1126 <= 106) when slicing `       | activation --service-request-channel-token=11913582771556664742 --renderer-client-id=3 --shared-
    |       |          |       | files=v8_context_snapshot_data:100,v8_natives_data:101
 13 | 2925  | Sleeping | 2.15  | /usr/share/code/code/usr/sh`[...]', src/libcore/str/mod.rs:2055:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::str::slice_error_fail
             at src/libcore/str/mod.rs:2055
  11: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libcore/str/mod.rs:1792
  12: core::option::Option<T>::unwrap_or_else
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libcore/option.rs:419
  13: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libcore/str/mod.rs:1792
  14: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libcore/str/mod.rs:1657
  15: <alloc::string::String as core::ops::index::Index<core::ops::range::Range<usize>>>::index
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/liballoc/string.rs:1965
  16: <nu::parser::parse::files::Files as language_reporting::span::ReportingFiles>::source
             at src/parser/parse/files.rs:75
  17: language_reporting::models::SourceLine<Files>::after_marked
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/models.rs:113
  18: language_reporting::components::SourceCodeLine::{{closure}}
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/components.rs:96
  19: core::ops::function::FnOnce::call_once
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libcore/ops/function.rs:235
  20: <render_tree::helpers::Section as render_tree::component::BlockComponent>::append
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/helpers.rs:143
  21: <render_tree::component::CurriedBlockComponent<B,Block> as render_tree::render::Render>::render
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:23
  22: language_reporting::components::SourceCodeLine
             at ./<::render_tree::macros::concat_trees macros>:5
  23: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  24: language_reporting::components::Body
             at ./<::render_tree::macros::concat_trees macros>:5
  25: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  26: language_reporting::components::Diagnostic::{{closure}}
             at ./<::render_tree::macros::concat_trees macros>:5
  27: <render_tree::helpers::Section as render_tree::component::BlockComponent>::append
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/helpers.rs:143
  28: <render_tree::component::CurriedBlockComponent<B,Block> as render_tree::render::Render>::render
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:23
  29: language_reporting::components::Diagnostic
             at ./<::render_tree::macros::concat_trees macros>:5
  30: <render_tree::component::CurriedInlineComponent<T> as render_tree::render::Render>::render
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/component.rs:106
  31: render_tree::render::Render::into_fragment
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/render-tree-0.1.1/src/render.rs:68
  32: language_reporting::emitter::DiagnosticWriter<W>::emit
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/emitter.rs:36
  33: language_reporting::emitter::emit
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/language-reporting-0.3.1/src/emitter.rs:20
  34: nu::cli::cli::{{closure}}
             at ./src/cli.rs:268
  35: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/future.rs:42
  36: std::future::set_task_context
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/future.rs:78
  37: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/future.rs:42
  38: futures_executor::local_pool::block_on::{{closure}}
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  39: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:68
  40: std::thread::local::LocalKey<T>::try_with
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/thread/local.rs:262
  41: std::thread::local::LocalKey<T>::with
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/thread/local.rs:239
  42: futures_executor::local_pool::run_executor
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:64
  43: futures_executor::local_pool::block_on
             at /Users/andrasMAMA/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  44: nu::main
             at src/main.rs:59
  45: std::rt::lang_start::{{closure}}
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/rt.rs:64
  46: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  47: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  48: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  49: std::panicking::try
             at src/libstd/panicking.rs:275
  50: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  51: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  52: std::rt::lang_start
             at /rustc/29a54035c77cb2ba7ea2c24b2437760d0495a2c8/src/libstd/rt.rs:64
  53: nu::main
```
