### ISSUE TITLE
panic: Expected command textview when reading JSON

### ISSUE THREAD

**Issue by bmalehorn** [nushell/nushell#358]
- built with:
```
rustup toolchain install nightly
cargo +nightly build  --features rawkey,clipboard
```
- built on cd1e16d574baf8f77e5e86bd4b2c39067d0aafaa 
- ran with `RUST_BACKTRACE=1`
- on Ubuntu 18.04
- encountered this from running through the book

```
/home/brian/tmp> cat package.json
{
  "a": "b"
}
/home/brian/tmp> open package.json | get a
thread 'main' panicked at 'Expected command textview', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1166
  11: core::option::Option<T>::expect
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libcore/option.rs:345
  12: nu::commands::command::RunnableContext::expect_command
             at src/commands/command.rs:244
  13: nu::commands::autoview::autoview::{{closure}}
             at src/commands/autoview.rs:46
  14: <futures_async_stream::stream::GenStream<U,T> as futures_core::stream::Stream>::poll_next::{{closure}}
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.2/src/stream.rs:44
  15: std::future::set_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:78
  16: <futures_async_stream::stream::GenStream<U,T> as futures_core::stream::Stream>::poll_next
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.2/src/stream.rs:44
  17: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.18/src/stream.rs:86
  18: futures_util::stream::StreamExt::poll_next_unpin
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/mod.rs:1169
  19: <futures_util::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/next.rs:35
  20: std::future::poll_with_tls_context::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  21: std::future::get_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:110
  22: std::future::poll_with_tls_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  23: nu::commands::classified::InternalCommand::run::{{closure}}
             at /home/brian/nushell/src/commands/classified.rs:132
  24: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  25: std::future::set_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:78
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  27: std::future::poll_with_tls_context::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  28: std::future::get_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:110
  29: std::future::poll_with_tls_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  30: nu::cli::process_line::{{closure}}
             at /home/brian/nushell/src/cli.rs:411
  31: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  32: std::future::set_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:78
  33: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  34: std::future::poll_with_tls_context::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  35: std::future::get_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:110
  36: std::future::poll_with_tls_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:120
  37: nu::cli::cli::{{closure}}
             at /home/brian/nushell/src/cli.rs:246
  38: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  39: std::future::set_task_context
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:78
  40: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/future.rs:42
  41: futures_executor::local_pool::block_on::{{closure}}
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  42: futures_executor::local_pool::run_executor::{{closure}}
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:68
  43: std::thread::local::LocalKey<T>::try_with
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/thread/local.rs:262
  44: std::thread::local::LocalKey<T>::with
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/thread/local.rs:239
  45: futures_executor::local_pool::run_executor
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:64
  46: futures_executor::local_pool::block_on
             at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  47: nu::main
             at src/main.rs:59
  48: std::rt::lang_start::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/rt.rs:64
  49: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  50: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  51: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  52: std::panicking::try
             at src/libstd/panicking.rs:275
  53: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  54: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  55: std::rt::lang_start
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libstd/rt.rs:64
  56: main
  57: __libc_start_main
  58: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by jonathandturner** [comment]
We should definitely fix the panic, but I was wondering about your setup, too. Is the plug-in for textview in your path? That might be another issue if so.

**Comment by bmalehorn** [comment]
Ah yep, that was the problem - it works now that I ran `cargo install` instead of `cargo build` and only copying the `nu` binary.

The reason I was compiling from the checkout was that the install instructions `cargo install nu` failed:
```
    Updating crates.io index
error: failed to download `nu v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.2.0/Cargo.toml`

Caused by:
  the `default-run` manifest key is unstable

Caused by:
  feature `default-run` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["default-run"]` to enable this feature
```

It might be worth updating the docs to be compatible with rust dummies like myself:

```
rustup toolchain install nightly
cargo +nightly install nu --features rawkey,clipboard
```
