### ISSUE TITLE
`ps` crashes while attempting to decode incorrectly formatted UTF-8

### ISSUE THREAD

**Issue by anaisbetts** [nushell/nushell#364]
This is on Windows 10 build 18963 (Fast Ring), and built from master (cd1e16d574baf)

```
C:\Users\ana\code\anaisbetts\nushell\target\release(master)> ps                                                         thread 'main' panicked at 'invalid string: FromUtf8Error { bytes: [65, 117, 115, 103, 101, 102, 252, 104, 114, 116, 101, 32, 65, 110, 119, 101, 110, 100, 117, 110, 103, 101, 110], error: Utf8Error { valid_up_to: 6, error_len: Some(1) } }', src\libcore\result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.35\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:384
   7: std::panicking::rust_begin_panic
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:311
   8: core::panicking::panic_fmt
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libcore\panicking.rs:85
   9: core::result::unwrap_failed
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libcore\result.rs:1084
  10: sysinfo::windows::tools::load_symbols
  11: <sysinfo::windows::system::System as sysinfo::traits::SystemExt>::new_with_specifics
  12: <nu::commands::ps::PS as nu::commands::command::WholeStreamCommand>::run
  13: nu::commands::command::Command::run
  14: nu::context::Context::run_command
  15: std::error::Error::type_id
  16: nu::cli::cli::{{closure}}
  17: std::thread::local::LocalKey<T>::with
  18: futures_executor::local_pool::block_on
  19: rustyline::history::History::save
  20: nu::parser::hir::<impl nu::object::meta::Tagged<nu::parser::hir::RawExpression>>::synthetic_string
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\rt.rs:49
  22: std::panicking::try::do_call<closure,i32>
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:296
  23: panic_unwind::__rust_maybe_catch_panic
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libpanic_unwind\lib.rs:80
  24: std::panicking::try
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panicking.rs:275
  25: std::panic::catch_unwind
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\panic.rs:394
  26: std::rt::lang_start_internal
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3\/src\libstd\rt.rs:48
  27: main
  28: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  29: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  30: BaseThreadInitThunk
  31: RtlUserThreadStart
```

Indeed, this UTF-8 sequence is bogus (the 252), this string appears to decode to "Ausgefhrte Anwendungen" ("Executed Applications") - this should be "Ausgeführte" which is probably where the UTF-8 bit comes in. Bizarrely, this is an en-US copy of Windows - I have a German keyboard layout but definitely running in English locale.

**Comment by anaisbetts** [comment]
Sure enough, 252 (0xFC) is ü in Windows-1252, looks like someone is taking the result from an ANSI Win32 function and trying to florp it to UTF-8

**Comment by jonathandturner** [comment]
Interesting. I wonder if it's in Windows (since you're on fast ring) or in nushell. Would it be possible to run a debug version of nu to get the line numbers it's panicking on?
