### ISSUE TITLE
crash when I use ceil or floor 

### ISSUE THREAD

**Issue by wpf999** [nushell/nushell#3760]
**Describe the bug**

nushell crash when I use ceil or floor :

`/root> 11 | math sqrt | math floor`
or
`/root> 11 | math sqrt | math ceil`

**To Reproduce**

```
/root> 11 | math sqrt | math ceil
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/bigdecimal-0.2.0/src/lib.rs:596:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
/root> 11 | math sqrt | math floor
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/bigdecimal-0.2.0/src/lib.rs:596:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
```
/root> version | pivot
───┬────────────────────┬─────────────────────────────────────────────
 # │      Column0       │                   Column1                   
───┼────────────────────┼─────────────────────────────────────────────
 0 │ version            │ 0.33.0                                      
 1 │ build_os           │ linux-x86_64                                
 2 │ rust_version       │ rustc 1.53.0 (53cb7b09b 2021-06-17)         
 3 │ cargo_version      │ cargo 1.53.0 (4369396ce 2021-04-27)         
 4 │ pkg_version        │ 0.33.0                                      
 5 │ build_time         │ 2021-07-07 00:00:05                         
 6 │ build_rust_channel │ release                                     
 7 │ features           │ ctrlc, default, rustyline, term, which, zip 
 8 │ installed_plugins  │ fetch, match, post, ps, sys                 
───┴────────────────────┴─────────────────────────────────────────────
```

**Comment by waywardmonkeys** [comment]
This is https://github.com/akubera/bigdecimal-rs/issues/69

**Comment by fdncred** [comment]
thanks @waywardmonkeys -  i was wondering how we would allow an unwrap into our code base. I guess we could switch to this fork? https://github.com/dpbriggs/bigdecimal-rs

**Comment by pwnorbitals** [comment]
It looks like https://github.com/akubera/bigdecimal-rs/ is not updated anymore, should we take a decision about switching libraries ?

**Comment by fdncred** [comment]
In the latest main branch we don't have these crashes. I suggest we close this issue.

```
> 11 | math sqrt | math floor 
3
> 11 | math sqrt | math ceil 
4
```
