### ISSUE TITLE
Panic at 'Can't create a Span whose end ...'

### ISSUE THREAD

**Issue by bugabinga** [nushell/nushell#3904]
### Describe the bug

I am unsure how to describe this bug but to simply show it.
I seems parsing `()` (which is equal to `$nothing` or vice versa, if I understand correctly) can sometimes crash nu.

### How to reproduce

```sh
∽/nu_playground
  cat -p .\print.nu
def print [
  ...rest: any
] {
  echo (build-string ($rest | flatten | into string | str collect) )
  echo (char newline)
}

print "Hello World!"
print (ansi ub) ¯\_(ツ)_/¯ (ansi reset)
print ()
print a
# the next line crashes
print a ()

∽/nu_playground
  with-env [RUST_BACKTRACE full] { nu .\print.nu }
Hello World!
¯\_(ツ)_/¯
nothing
a
thread 'main' panicked at 'Can't create a Span whose end < start, start=340, end=0', C:\Users\okr\scoop\persist\rustup\.car
go\registry\src\github.com-1ecc6299db9ec823\nu-source-0.35.0\src\meta.rs:518:9
stack backtrace:
   0:     0x7ff637715f9d - Ordinal0
   1:     0x7ff63623178a - Ordinal0
   2:     0x7ff637714997 - Ordinal0
   3:     0x7ff637715182 - Ordinal0
   4:     0x7ff6377143c2 - Ordinal0
   5:     0x7ff63771c585 - Ordinal0
   6:     0x7ff63771c4e1 - Ordinal0
   7:     0x7ff63771c47f - Ordinal0
   8:     0x7ff63796aa60 - git_oidarray_free
   9:     0x7ff6368f5f33 - Ordinal0
  10:     0x7ff6368e27da - Ordinal0
  11:     0x7ff6368e51eb - Ordinal0
  12:     0x7ff6368e31b7 - Ordinal0
  13:     0x7ff6368e0b2a - Ordinal0
  14:     0x7ff636a49dce - Ordinal0
  15:     0x7ff636a48a7b - Ordinal0
  16:     0x7ff6362caff2 - Ordinal0
  17:     0x7ff6362af0ea - Ordinal0
  18:     0x7ff635fc2066 - Ordinal0
  19:     0x7ff635fc1006 - Ordinal0
  20:     0x7ff635fc27ec - Ordinal0
  21:     0x7ff6378e9ec4 - git_oidarray_free
  22:     0x7ffd06a67034 - BaseThreadInitThunk
  23:     0x7ffd07d22651 - RtlUserThreadStart
error: External command failed
  ┌─ shell:9:34
  │
9 │ with-env [RUST_BACKTRACE full] { nu .\print.nu }
  │                                  ^^ command failed


```

### Expected behavior

`print a ()` should return `anothing`.
>Note: It is `anothing` instead of `a` because `() | into string` returns `nothing` instead of the empty string. That is however a different discussion.

### Configuration

version | pivot | to md
|Column0|Column1|
|-|-|
|version|0.35.0|
|build_os|windows-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.35.0|
|build_time|2021-08-04 10:11:37|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3,
selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by pejato** [comment]
So I took a look at why this might be happening today and have some info about it. It seems to have to do with Nu discarding the tag for some types of `Variable`s, including `$nothing` when it evaluates a reference.

When calling `print a $nothing` we pass command args to the def'd `print` command that look like this:
```
UnevaluatedCallInfo { 
  args: Call { 
    head: SpannedExpression { expr: Command, span: Span { start: 124, end: 129 } }, 
    positional: Some([
      SpannedExpression { expr: Literal(String("a")), span: Span { start: 130, end: 131 } }, 
      SpannedExpression { 
        expr: FullColumnPath(FullColumnPath { 
...
        }), 
        span: Span { start: 132, end: 134 } 
```

The second positional is our `$nothing` and has an attached span.

The `run` impl for custom commands (which are blocks) first evaluates its args.

We call `UnevaluatedCallInfo::evaluate` -> `evaluator::evaluate_args` -> `evaluator::evaluate_baseline_expr`-> `evaluator::evaluate_reference`.

While here, we discard the span for `Variable::True`, `Variable::False`, and `Variable::Nothing` like so
```
    match variable {
...
        Variable::Nothing => Ok(UntaggedValue::nothing().into_untagged_value()),
```

we eventually bubble back out into `run` again, and hit this conditional
```
if block.params.rest_positional.is_some() {
    let elements: Vec<_> = args_iter.collect();
    let start = if let Some(first) = elements.first() {
        first.tag.span.start()
    } else {
        0
    };
    let end = if let Some(last) = elements.last() {
        last.tag.span.end()
    } else {
        0
    };

    ctx.scope.add_var(
        "$rest",
        UntaggedValue::Table(elements).into_value(Span::new(start, end)),
    );
```

Because we have an element whose span start > 0 as our first element and we have our `$nothing` element with an end span of 0 as our last, the `Span::new` causes an assertion failure.

And actually, this problem can be observed when you try to pass anything of the form `expr+ $nothing|$true|$false` to any custom command where the `rest` argument is given arguments.

For instance,
```
def yuh [...rest] {}

yuh get into it $true

thread 'main' panicked at 'Can't create a Span whose end < start, start=54, end=0', crates/nu-source/src/meta.rs:518:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: nu_source::meta::Span::new
   3: <alloc::sync::Arc<nu_protocol::hir::Block> as nu_engine::whole_stream_command::WholeStreamCommand>::run
   4: nu_engine::whole_stream_command::Command::run
   5: nu_engine::evaluation_context::EvaluationContext::run_command
   6: nu_engine::evaluate::internal::run_internal_command
   7: nu_engine::evaluate::block::run_pipeline
   8: nu_engine::evaluate::block::run_block
   9: nu_engine::script::process_script
  10: nu_cli::cli::cli
  11: nu_cli::app::App::main
  12: nu_cli::app::App::run
  13: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm not really sure what the best way forward is here.
