### ISSUE TITLE
nushell crashes on errors in 'sub shells' for non-directories

### ISSUE THREAD

**Issue by p2mate** [nushell/nushell#414]
examples:

HOME\p2@sunshine:~/projects/nushell$ RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 0.19s
     Running `target/release/nu`
/home/p2/projects/nushell(master)> enter Cargo.toml
/> cd package
/package> q
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55716d933672 - backtrace::backtrace::libunwind::trace::h5b672ea0408452ed
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x55716d933672 - backtrace::backtrace::trace_unsynchronized::h15bbd54ccd30253c
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x55716d933672 - std::sys_common::backtrace::_print::hbf32a02f9894e727
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55716d933672 - std::sys_common::backtrace::print::h127d55b04a8ca638
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55716d933672 - std::panicking::default_hook::{{closure}}::h41569aa1cabd15f2
                               at src/libstd/panicking.rs:200
   5:     0x55716d933356 - std::panicking::default_hook::h2471d95c3baf1435
                               at src/libstd/panicking.rs:214
   6:     0x55716d933dc5 - std::panicking::rust_panic_with_hook::hdb74b1d76abfd8b2
                               at src/libstd/panicking.rs:477
   7:     0x55716d933962 - std::panicking::continue_panic_fmt::h7aad477695105344
                               at src/libstd/panicking.rs:384
   8:     0x55716d933856 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55716d955fca - core::panicking::panic_fmt::h2a7634fba4671b05
                               at src/libcore/panicking.rs:85
  10:     0x55716d9560c7 - core::result::unwrap_failed::h395c34a928fec133
                               at src/libcore/result.rs:1084
  11:     0x55716d48064a - std::future::poll_with_tls_context::hb63b268be46bc5c5
  12:     0x55716d475e01 - nu::cli::cli::{{closure}}::h8d6298c2de185f70
  13:     0x55716d461b9f - std::thread::local::LocalKey<T>::with::h6cd1ee8ad86f2c66
  14:     0x55716d46a9a9 - nu::main::hdafeded61c080a38
  15:     0x55716d46b063 - std::rt::lang_start::{{closure}}::h0319bb465e6f4881
  16:     0x55716d9337f3 - std::rt::lang_start_internal::{{closure}}::h4e292f977b47ab02
                               at src/libstd/rt.rs:49
  17:     0x55716d9337f3 - std::panicking::try::do_call::haf6204e4b28c6f49
                               at src/libstd/panicking.rs:296
  18:     0x55716d93db5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  19:     0x55716d93437d - std::panicking::try::had9b9f600586126b
                               at src/libstd/panicking.rs:275
  20:     0x55716d93437d - std::panic::catch_unwind::h4f34d0c32a79bb69
                               at src/libstd/panic.rs:394
  21:     0x55716d93437d - std::rt::lang_start_internal::h95e43a3bff5764bd
                               at src/libstd/rt.rs:48
  22:     0x55716d46ab72 - main
  23:     0x7f28e38b4ee3 - __libc_start_main
  24:     0x55716d4462fe - _start
  25:                0x0 - <unknown>

or

HOME\p2@sunshine:~/projects/nushell$ RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 0.18s
     Running `target/release/nu`
/home/p2/projects/nushell(master)> enter Cargo.toml
/> open bin
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShellError { error: Diagnostic(ShellDiagnostic { diagnostic: Diagnostic { severity: Error, code: None, message: "File could not be opened", labels: [Label { span: Span { start: 5, end: 8 }, message: Some("file not found"), style: Primary }] } }), cause: None }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55fab51a6672 - backtrace::backtrace::libunwind::trace::h5b672ea0408452ed
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x55fab51a6672 - backtrace::backtrace::trace_unsynchronized::h15bbd54ccd30253c
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x55fab51a6672 - std::sys_common::backtrace::_print::hbf32a02f9894e727
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55fab51a6672 - std::sys_common::backtrace::print::h127d55b04a8ca638
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55fab51a6672 - std::panicking::default_hook::{{closure}}::h41569aa1cabd15f2
                               at src/libstd/panicking.rs:200
   5:     0x55fab51a6356 - std::panicking::default_hook::h2471d95c3baf1435
                               at src/libstd/panicking.rs:214
   6:     0x55fab51a6dc5 - std::panicking::rust_panic_with_hook::hdb74b1d76abfd8b2
                               at src/libstd/panicking.rs:477
   7:     0x55fab51a6962 - std::panicking::continue_panic_fmt::h7aad477695105344
                               at src/libstd/panicking.rs:384
   8:     0x55fab51a6856 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55fab51c8fca - core::panicking::panic_fmt::h2a7634fba4671b05
                               at src/libcore/panicking.rs:85
  10:     0x55fab51c90c7 - core::result::unwrap_failed::h395c34a928fec133
                               at src/libcore/result.rs:1084
  11:     0x55fab4d72af5 - std::future::set_task_context::hd22623e650ed4b86
  12:     0x55fab4e4497e - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h3828d2aeb6600af2
  13:     0x55fab4cefc70 - std::future::poll_with_tls_context::h58b0e0a2cfef2e98
  14:     0x55fab4ce9096 - nu::cli::cli::{{closure}}::h8d6298c2de185f70
  15:     0x55fab4cd4b9f - std::thread::local::LocalKey<T>::with::h6cd1ee8ad86f2c66
  16:     0x55fab4cdd9a9 - nu::main::hdafeded61c080a38
  17:     0x55fab4cde063 - std::rt::lang_start::{{closure}}::h0319bb465e6f4881
  18:     0x55fab51a67f3 - std::rt::lang_start_internal::{{closure}}::h4e292f977b47ab02
                               at src/libstd/rt.rs:49
  19:     0x55fab51a67f3 - std::panicking::try::do_call::haf6204e4b28c6f49
                               at src/libstd/panicking.rs:296
  20:     0x55fab51b0b5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x55fab51a737d - std::panicking::try::had9b9f600586126b
                               at src/libstd/panicking.rs:275
  22:     0x55fab51a737d - std::panic::catch_unwind::h4f34d0c32a79bb69
                               at src/libstd/panic.rs:394
  23:     0x55fab51a737d - std::rt::lang_start_internal::h95e43a3bff5764bd
                               at src/libstd/rt.rs:48
  24:     0x55fab4cddb72 - main
  25:     0x7f1fdae03ee3 - __libc_start_main
  26:     0x55fab4cb92fe - _start
  27:                0x0 - <unknown>

**Comment by wycats** [comment]
#438
