### ISSUE TITLE
Panic when changing prompt

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4279]
Sourcing the following script
```
def-env try-prompt [] {
    def has-env [name: string] {
        $name in (env).name
    }
    
    # Creating the new prompt for the session
    let virtual-prompt = "(nu_foo)"

    # Back up the old prompt builder
    let old-prompt-command = if (has-env "VIRTUAL_ENV") && (has-env "_OLD_PROMPT_COMMAND") {
        $env._OLD_PROMPT_COMMAND
    } else {
        if (has-env "PROMPT_COMMAND") {
            $env.PROMPT_COMMAND
        } else {
            ""
        }
    }

    # If there is no default prompt, then only the env is printed in the prompt
    let new-prompt = if (has-env "PROMPT_COMMAND") {
        if ($old-prompt-command | describe) == "block" {
            $"echo ($virtual-prompt)(do $old-prompt-command)"
        } else {
            $"echo ($virtual-prompt)($old-prompt-command)"
        }
    } else {
        $"echo ($virtual-prompt)"
    }

    let new-env = {      
        _OLD_PROMPT_COMMAND : $old-prompt-command        
        PROMPT_COMMAND      : $new-prompt
    }

    # Activate the environment variables
    load-env $new-env
}

def-env reset [] {
    hide PROMPT_COMMAND
    hide _OLD_PROMPT_COMMAND
}

try-prompt
```
will panic with the following backtrace:
```
thread 'main' panicked at 'internal error: missing block', crates\nu-protocol\src\engine\engine_state.rs:525:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
   2: core::panicking::panic_display<str>
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:63
   3: core::option::expect_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\option.rs:1637
   4: enum$<core::option::Option<ref$<nu_protocol::ast::block::Block> >, 1, 18446744073709551615, Some>::expect<ref$<nu_protocol::ast::block::Block> >
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\option.rs:709
   5: nu_protocol::engine::engine_state::EngineState::get_block
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-protocol\src\engine\engine_state.rs:523
   6: nu_engine::eval::eval_expression
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\eval.rs:313
   7: nu_engine::eval::eval_expression
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\eval.rs:259
   8: nu_engine::call_ext::impl$0::rest<enum$<nu_protocol::value::Value> >
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\call_ext.rs:63
   9: nu_command::core_commands::echo::impl$0::run
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-command\src\core_commands\echo.rs:33
  10: nu_engine::eval::eval_call
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\eval.rs:163
  11: nu_engine::eval::eval_expression_with_input
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\eval.rs:442
  12: nu_engine::eval::eval_subexpression
             at C:\Users\kubouch\git\extern\engine-q\crates\nu-engine\src\eval.rs:632
  13: nu::prompt_update::get_prompt_string::closure$0
             at C:\Users\kubouch\git\extern\engine-q\src\prompt_update.rs:75
  14: enum$<core::option::Option<enum$<nu_protocol::value::Value> >, 0, 15, Some>::and_then<enum$<nu_protocol::value::Value>,enum$<nu_protocol::pipeline_data::PipelineData>,nu::prompt_update::get_prompt_string::closure$0>
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\option.rs:1053
  15: nu::prompt_update::get_prompt_string
             at C:\Users\kubouch\git\extern\engine-q\src\prompt_update.rs:57
  16: nu::prompt_update::update_prompt
             at C:\Users\kubouch\git\extern\engine-q\src\prompt_update.rs:123
  17: nu::repl::evaluate
             at C:\Users\kubouch\git\extern\engine-q\src\repl.rs:165
  18: nu::main
             at C:\Users\kubouch\git\extern\engine-q\src\main.rs:164
  19: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\nu.exe` (exit code: 101)
```

**Comment by kubouch** [comment]
The panic moved to `crates/nu-protocol/src/engine/engine_state.rs:574:14`

**Comment by kubouch** [comment]
I managed to trigger this error with `with-env { PROMPT_COMMAND : 'echo $"foo(char sp)"' } { nu }`

**Comment by elferherrera** [comment]
![image](https://user-images.githubusercontent.com/6942205/158686294-8c7626bb-eb73-4e29-b9d5-0e26b6d5f585.png)

**Comment by jntrnr** [comment]
@elferherrera that should be `$env.PWD`
