### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4289]
In Bash:
```
$ 'echo foo' > foo.nu

$ engine-q foo.nu
foo

$ RUST_BACKTRACE=1 engine-q foo.nu | false
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1193:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: std::io::stdio::print_to
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/stdio.rs:1193:9
   3: std::io::stdio::_print
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/stdio.rs:1205:5
   4: engine_q::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Seems like a similar issue to https://github.com/nushell/nushell/issues/4161

**Comment by kubouch** [comment]
This now fails with "Broken pipe (os error 32)" and does not panic.
