### ISSUE TITLE
Alias-related panic when tab-completion menu is open

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4303]
To reproduce:
```
> alias s = shells

> source ~/.config  # then, hit Tab
#... menu pops up

# with the menu popped up, press backspace until:
> s

# then, it will panic:
thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:439:9
stack backtrace:                                               sort                                                           sort-by                                                        sort-by
   0: rust_begin_unwind                                        source                                                         source
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: nu_protocol::engine::engine_state::EngineState::get_span_contents
             at /home/kubouch/git/extern/engine-q/crates/nu-protocol/src/engine/engine_state.rs:439:9
   3: nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents
             at /home/kubouch/git/extern/engine-q/crates/nu-protocol/src/engine/engine_state.rs:902:20
   4: nu_cli::completions::NuCompleter::complete_commands
             at ./crates/nu-cli/src/completions.rs:122:22
   5: nu_cli::completions::NuCompleter::completion_helper
             at ./crates/nu-cli/src/completions.rs:285:55
   6: <nu_cli::completions::NuCompleter as reedline::completion::base::Completer>::complete
             at ./crates/nu-cli/src/completions.rs:384:26
   7: <reedline::menu::completion_menu::CompletionMenu as reedline::menu::Menu>::update_values
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/menu/completion_menu.rs:224:23
   8: <reedline::menu::completion_menu::CompletionMenu as reedline::menu::Menu>::update_working_details
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/menu/completion_menu.rs:239:13
   9: reedline::engine::Reedline::buffer_paint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/engine.rs:1067:17
  10: reedline::engine::Reedline::repaint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/engine.rs:978:13
  11: reedline::engine::Reedline::read_line_helper
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/engine.rs:437:29
  12: reedline::engine::Reedline::read_line
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/18f5383/src/engine.rs:331:22
  13: nu::repl::evaluate
             at ./src/repl.rs:169:21
  14: nu::main
             at ./src/main.rs:164:17
  15: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I was in vi insert mode on Linux.

**Comment by lukexor** [comment]
I encountered a similar issue but didn't need to backspace.

`alias ls = ls -s`

```
~/dev/nushell on  main is 📦 v0.59.0 via 🦀 v1.58.1
[11:00] v0.59.0 ❯ ls<TAB>thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:439:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lukexor** [comment]
For me this is extremely annoying with no work-around.

Specifically it comes up most often for aliases for `cp` and `rm` which I have aliases to `cp -i` and `rm -i` for since non-interactive rm by default is a horrible default on linux and macOS. I basically have to choose between no tab-completion or no aliases.

**Comment by lukexor** [comment]
Thanks @jntrnr ! So excited to get this back
