### ISSUE TITLE
parsing git log from our documentation

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4312]
this should work but I suspect it's not working because there are empty cells.

`git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD -n 10 | lines | split column "»¦«" commit subject name email date | update date { get date | into datetime}`

this equivalent command works in nushell
`git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD -n 10 | lines | split column "»¦«" commit subject name email date | update date { get date | str to-datetime}`

related but maybe a different issue.
`git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD | lines | split column "»¦«" commit subject name email date | update date { get date | into datetime} | where date < 365day | group-by name | pivot | sort-by Column1 | rename name commits | reverse | first 10 | update commits {get commits | count } | table -n 1`

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/nu-command/src/filters/group_by.rs:98:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_bounds_check
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:75:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/slice/index.rs:184:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/vec/mod.rs:2528:9
   6: nu_command::filters::group_by::group_by
             at ./crates/nu-command/src/filters/group_by.rs:98:17
   7: <nu_command::filters::group_by::GroupBy as nu_protocol::engine::command::Command>::run
             at ./crates/nu-command/src/filters/group_by.rs:38:9
   8: nu_engine::eval::eval_call
             at ./crates/nu-engine/src/eval.rs:149:9
   9: nu_engine::eval::eval_expression_with_input
             at ./crates/nu-engine/src/eval.rs:428:21
  10: nu_engine::eval::eval_block
             at ./crates/nu-engine/src/eval.rs:465:25
  11: nu::utils::eval_source
             at ./src/utils.rs:293:11
  12: nu::repl::evaluate
             at ./src/repl.rs:235:21
  13: nu::main
             at ./src/main.rs:164:17
  14: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jntrnr** [comment]
is this the same/similar to https://github.com/nushell/nushell/issues/4312?

**Comment by jntrnr** [comment]
I think we can close this also. The crash seems to be gone, and I *think* we can switch to some variation of one of the versions in https://github.com/nushell/nushell/issues/4340 for the docs.

Good catch
