### ISSUE TITLE
git log crash

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4340]
Took this line from the contributor book to test it out in engine-q but sadly, it crashed.

`> git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD | lines | split column "»¦«" commit subject name email date | update date { get date | into datetime} | where date < 365day | group-by name | transpose | sort-by Column1 | rename name commits | reverse | first 10 | update commits {get commits | count } | table -n 1`

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/nu-command/src/filters/group_by.rs:98:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_bounds_check
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:75:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/slice/index.rs:184:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/alloc/src/vec/mod.rs:2528:9
   6: nu_command::filters::group_by::group_by
             at ./crates/nu-command/src/filters/group_by.rs:98:17
   7: <nu_command::filters::group_by::GroupBy as nu_protocol::engine::command::Command>::run
             at ./crates/nu-command/src/filters/group_by.rs:38:9
   8: nu_engine::eval::eval_call
             at ./crates/nu-engine/src/eval.rs:136:9
   9: nu_engine::eval::eval_block
             at ./crates/nu-engine/src/eval.rs:418:33
  10: engine_q::utils::eval_source
             at ./src/utils.rs:316:11
  11: engine_q::repl::evaluate
             at ./src/repl.rs:244:21
  12: engine_q::main
             at ./src/main.rs:48:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I've corrected a few things. I'm sure there are more. `rename` doesn't exist yet but it fails if you remove that command and everything after it.

**Comment by jntrnr** [comment]
I've got a few fixes to the error messages, but it looks like it doesn't crash now (even before fixes).

Here's a working version of the above:

```
git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD | lines | split column "»¦«" commit subject name email date | update date { get date | into datetime} | where ($it.date > ((date now) - 365day)) | group-by name | transpose | sort-by Column1 | rename name commits | reverse | first 10 | update commits {get commits | length } | table -n 1
```

Will PR the error improvements

**Comment by jntrnr** [comment]
This should be okay now. PR for better errors here: https://github.com/nushell/nushell/pull/4541
