### ISSUE TITLE
`error make`-related panic

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4462]
### Describe the bug

I got a longer module that produces a strange panic when the command `test bits` is run.

### How to reproduce

Have this file:
```
# bin-utils.nu
def "get bits" [x: int, bits] {
    if $x == 0 {
        $bits
    } else {
        let new-x = ($x / 2 | into int)
        let bit = if $new-x == ($x / 2 | math ceil | into int) {
            0
        } else {
            1
        }

        get bits $new-x ($bits | append $bit)
    }
}

def "get bits2" [x: int] {
    let inp = $in

    if $x != 0 {
        let new-x = ($x / 2 | into int)
        let bit = if $new-x == ($x / 2 | math ceil | into int) {
            0
        } else {
            1
        }

        $inp | append $bit | get bits2 $new-x
    } else {
        $inp
    }
}

export def "into bits" [] {
    let inp = $in
    let span = (metadata $inp).span
    let type = ($inp | describe)

    if "list" in $type {
        $inp | each {
            $it | into bits
        }
    } else if "int" in $type {
        [] | get bits2 $inp
    } else {
        error make {
            msg: "Cannot convert to bits",
            label: {
                text: "This value cannot be converted to bits"
                start: $span.start
                end: $span.end
            }
        }
    }
}

export def "bits into int" [] {
    reverse | reduce -f 0 { 2 * $it.acc + $it.item }
}

export def "test bits" [] {
    0..4 | each {
        let bits = ($it | into bits)
        let res = ($bits | bits into int)
        let span = (metadata $res).span
        if $it == 1 {
            error make {
                msg: "Test mismatch",
                label: {
                    text: $"Expected: ($it), bits: ($bits | str collect ''), result: ($res)"
                    start: $span.start
                    end: $span.end
                }
            }
        }
    } | compact
}
```

Then:
```
> use bin-utils.nu *

> test bits
Error:
  × Test mismatch
thread 'main' panicked at 'attempt to subtract with overflow', crates/nu-protocol/src/span.rs:25:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: nu_protocol::span::<impl core::convert::From<nu_protocol::span::Span> for miette::protocol::SourceSpan>::from
             at ./crates/nu-protocol/src/span.rs:25:35
   4: <T as core::convert::Into<U>>::into
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/convert/mod.rs:542:9
   5: miette::protocol::LabeledSpan::new_with_span
             at /home/kubouch/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/protocol.rs:213:19
   6: <nu_protocol::shell_error::ShellError as miette::protocol::Diagnostic>::labels
             at ./crates/nu-protocol/src/shell_error.rs:10:31
   7: <nu_cli::errors::CliError as miette::protocol::Diagnostic>::labels
             at ./crates/nu-cli/src/errors.rs:39:9
   8: miette::handlers::graphical::GraphicalReportHandler::render_snippets
             at /home/kubouch/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:251:35
   9: miette::handlers::graphical::GraphicalReportHandler::render_report
             at /home/kubouch/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:113:9
  10: <miette::handlers::graphical::GraphicalReportHandler as miette::eyreish::ReportHandler>::debug
             at /home/kubouch/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:725:9
  11: <miette::handler::MietteHandler as miette::eyreish::ReportHandler>::debug
             at /home/kubouch/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handler.rs:253:9
  12: <nu_cli::errors::CliError as core::fmt::Debug>::fmt
             at ./crates/nu-cli/src/errors.rs:16:9
  13: core::fmt::write
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
  14: std::io::Write::write_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
  15: <&std::io::stdio::Stderr as std::io::Write>::write_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1120:9
  16: <std::io::stdio::Stderr as std::io::Write>::write_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1094:9
  17: std::io::stdio::print_to
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1200:21
  18: std::io::stdio::_eprint
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1224:5
  19: nu::utils::report_error
             at ./src/utils.rs:355:5
  20: nu::utils::eval_source
             at ./src/utils.rs:305:17
  21: nu::repl::evaluate
             at ./src/repl.rs:300:21
  22: nu::main
             at ./src/main.rs:204:31
  23: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

Should not panic

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 1fd7b9ac                                 |
| commit_hash        | 1fd7b9ac38022e3157a5aa09d14db994c88283ed |
| commit_date        | 2022-02-12 11:11:54 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-12 14:03:38 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

It is possible to prevent the panic by some modifications to the `test bits` command:
* Changing `let span = (metadata $res).span` to `let span = (metadata $res).span` 
* Hard-coding `let bits = [ 1 ]` (identical result to `$it | into bits` for `$it` == 1)
* Changing the condition to `it $it == 0` (integers >= 1 seem to trigger the panic)

**Comment by jntrnr** [comment]
@kubouch can you try this with a debug build? I think that'll give us a backtrace we can use to see what's causing the crash

**Comment by kubouch** [comment]
@jntrnr I updated with debug trace but it doesn't look much better...

**Comment by jntrnr** [comment]
@kubouch - hmm, that's still not using a debug build of nu. These lines would have line numbers if it was:

```
  18: nu::utils::eval_source
  19: nu::repl::evaluate
  20: nu::main
```

Here's what I get:
```
Error: 
  × Test mismatch
thread 'main' panicked at 'attempt to subtract with overflow', crates/nu-protocol/src/span.rs:25:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:48:5
   3: nu_protocol::span::<impl core::convert::From<nu_protocol::span::Span> for miette::protocol::SourceSpan>::from
             at /home/jt/Source/nushell/crates/nu-protocol/src/span.rs:25:35
   4: <T as core::convert::Into<U>>::into
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/convert/mod.rs:542:9
   5: miette::protocol::LabeledSpan::new_with_span
             at /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/protocol.rs:213:19
   6: <nu_protocol::shell_error::ShellError as miette::protocol::Diagnostic>::labels
             at /home/jt/Source/nushell/crates/nu-protocol/src/shell_error.rs:10:31
   7: <nu_cli::errors::CliError as miette::protocol::Diagnostic>::labels
             at /home/jt/Source/nushell/crates/nu-cli/src/errors.rs:39:9
   8: miette::handlers::graphical::GraphicalReportHandler::render_snippets
             at /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:251:35
   9: miette::handlers::graphical::GraphicalReportHandler::render_report
             at /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:113:9
  10: <miette::handlers::graphical::GraphicalReportHandler as miette::eyreish::ReportHandler>::debug
             at /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handlers/graphical.rs:725:9
  11: <miette::handler::MietteHandler as miette::eyreish::ReportHandler>::debug
             at /home/jt/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-3.3.0/src/handler.rs:253:9
  12: <nu_cli::errors::CliError as core::fmt::Debug>::fmt
             at /home/jt/Source/nushell/crates/nu-cli/src/errors.rs:16:9
  13: core::fmt::write
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/fmt/mod.rs:1149:17
  14: std::io::Write::write_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/mod.rs:1697:15
  15: <&std::io::stdio::Stderr as std::io::Write>::write_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/stdio.rs:1120:9
  16: <std::io::stdio::Stderr as std::io::Write>::write_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/stdio.rs:1094:9
  17: std::io::stdio::print_to
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/stdio.rs:1200:21
  18: std::io::stdio::_eprint
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/stdio.rs:1224:5
  19: nu::utils::report_error
             at /home/jt/Source/nushell/src/utils.rs:355:5
  20: nu::utils::eval_source
             at /home/jt/Source/nushell/src/utils.rs:305:17
  21: nu::repl::evaluate
             at /home/jt/Source/nushell/src/repl.rs:300:21
  22: nu::main
             at /home/jt/Source/nushell/src/main.rs:204:31
  23: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:227:5
```

that said, it doesn't help all that much because we're past where the error is first created.

You might want to see if you can shrink the repro down to a single use of `error make` that causes the problem. I gave it a try but when I shrank it, it worked for me, so it's probably a combination of things causing it.
