### ISSUE TITLE
`enter` and `open` crash when opening a yaml file with key `true`

### ISSUE THREAD

**Issue by 13tales** [nushell/nushell#449]
Hi there.

When trying to `enter` or `open` a Yaml file, Nu crashes with the following error: 
```
thread 'main' panicked at 'not yet implemented: Unknown key type.', src/commands/from_yaml.rs:52:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:52
  10: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:50
  11: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:50
  12: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:50
  13: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:50
  14: nu::commands::from_yaml::convert_yaml_value_to_nu_value
             at src/commands/from_yaml.rs:50
  15: nu::commands::from_yaml::from_yaml_string_to_value
             at src/commands/from_yaml.rs:68
  16: nu::commands::open::parse_string_as_value
             at src/commands/open.rs:485
  17: nu::commands::classified::InternalCommand::run::{{closure}}
             at /Users/toma/Workspace/nushell/src/commands/classified.rs:179
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  19: std::future::set_task_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:78
  20: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  21: std::future::poll_with_tls_context::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:120
  22: std::future::get_task_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:110
  23: std::future::poll_with_tls_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:120
  24: nu::cli::process_line::{{closure}}
             at /Users/toma/Workspace/nushell/src/cli.rs:408
  25: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  26: std::future::set_task_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:78
  27: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  28: std::future::poll_with_tls_context::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:120
  29: std::future::get_task_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:110
  30: std::future::poll_with_tls_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:120
  31: nu::cli::cli::{{closure}}
             at /Users/toma/Workspace/nushell/src/cli.rs:250
  32: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  33: std::future::set_task_context
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:78
  34: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/future.rs:42
  35: futures_executor::local_pool::block_on::{{closure}}
             at /Users/toma/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/local_pool.rs:296
  36: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/toma/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/local_pool.rs:68
  37: std::thread::local::LocalKey<T>::try_with
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/thread/local.rs:262
  38: std::thread::local::LocalKey<T>::with
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/thread/local.rs:239
  39: futures_executor::local_pool::run_executor
             at /Users/toma/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/local_pool.rs:64
  40: futures_executor::local_pool::block_on
             at /Users/toma/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/local_pool.rs:296
  41: nu::main
             at src/main.rs:53
  42: std::rt::lang_start::{{closure}}
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/rt.rs:64
  43: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  44: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  45: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  46: std::panicking::try
             at src/libstd/panicking.rs:275
  47: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  48: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  49: std::rt::lang_start
             at /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libstd/rt.rs:64
  50: nu::main
```

The line that triggers the crash has a mapping of `true: "True"` (this file is a mapping of keys to localised language fragments, originally converted from JSON); Nu is treating the key as a bool. It's probably a dumb thing to have as a key, but I've run a couple of yaml validators/linters over it without issue, so I guess it *is* valid yaml 🤷‍♂

**Comment by jonathandturner** [comment]
@13tales - would it be possible to share the yaml file?  It might be a bug on our side or in https://github.com/dtolnay/serde-yaml

**Comment by androbtech** [comment]
@jonathandturner reproduced.

```
ls | first 1 | pick readonly | save test.yaml
open test.yaml --raw
```

test.yaml
--- 
readonly: false
```

Edit the file replace `readonly: false` with `true: "true"` and `open test.yaml` and it panics.

**Comment by 13tales** [comment]
> @13tales - would it be possible to share the yaml file? It might be a bug on our side or in https://github.com/dtolnay/serde-yaml

Probably not (because work), but as per @androbtech above, I can reproduce it with a yaml file of just `true: "True"`
