### ISSUE TITLE
Tests fail with internal error: can't find PWD

### ISSUE THREAD

**Issue by bowlofeggs** [nushell/nushell#4900]
### Describe the bug

I've been working on updating Gentoo to 0.60.0, and I see about 32 tests failing, seemingly due to `PWD` not being defined. I tried explicitly defining this variable in the [ebuild](https://github.com/gentoo/gentoo/pull/24719) but they still seem upset. There may be something unusual about the Gentoo build environment that is relevant here, but I am unsure what it may be.

Do you have any suggestions on how I might proceed?

### How to reproduce

It's difficult to give an easy reproducer here, since it may be something particular about the Gentoo ebuild environment.

### Expected behavior

Tests pass.

### Additional context

```
---- tests::test_engine::export_def_env stdout ----                                                                                                                                                                                           
stdout:                                                                                                                
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                                                 

thread 'tests::test_engine::export_def_env' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_hiding::hide_shadowed_decl stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hide_shadowed_decl' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_hiding::hide_shadowed_env stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hide_shadowed_env' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_hiding::hides_def_and_env_import_1 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_def_and_env_import_1' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_all_envs_within_scope stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_all_envs_within_scope' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_env_import_1 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_1' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_def_runs_env_import stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_def_runs_env_import' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5
---- tests::test_hiding::hides_env_import_4 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_4' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_env_import_6 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_6' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_env_import_5 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_5' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_env_import_3 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_3' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::hides_env_import_2 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::hides_env_import_2' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_hiding::use_def_import_after_hide stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::use_def_import_after_hide' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_hiding::use_env_import_after_hide stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_hiding::use_env_import_after_hide' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_and_env_imports_2 stdout ----                                                                                                                                                                  [166/1792]
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_and_env_imports_2' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_and_env_imports_1 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_and_env_imports_1' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::export_alias stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::export_alias' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_imports_3 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_imports_3' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_imports_2 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_imports_2' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_imports_1 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_imports_1' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_imports_4 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_imports_4' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_modules::module_env_import_uses_internal_command stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_import_uses_internal_command' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_import_uses_internal_command stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_import_uses_internal_command' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_env_imports_1 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_imports_1' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_def_imports_5 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_def_imports_5' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_env_imports_2 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_imports_2' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_env_imports_3 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_imports_3' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::multi_word_imports stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::multi_word_imports' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_modules::module_env_imports_4 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_imports_4' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:96:5

---- tests::test_parser::alias_recursion stdout ----
stdout:                                                    
stderr: Error:                                             
  × Current directory not found
  help: The environment variable 'PWD' was not found. It is required to
        define the current directory.

Error:                                                     
  × Current directory not found
  help: The environment variable 'PWD' was not found. It is required to
        define the current directory.


thread 'tests::test_parser::alias_recursion' panicked at 'assertion failed: output.status.success()', src/tests.rs:67:5

---- tests::test_modules::module_env_imports_5 stdout ----
stdout:                                                    
stderr: thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::test_modules::module_env_imports_5' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5

---- tests::test_table_operations::get_fuzzy stdout ----
stdout:                                                    
stderr: Error:                                             
  × Current directory not found
  help: The environment variable 'PWD' was not found. It is required to
        define the current directory.

Error:                                                     
  × Current directory not found
  help: The environment variable 'PWD' was not found. It is required to
        define the current directory.


thread 'tests::test_table_operations::get_fuzzy' panicked at 'assertion failed: output.status.success()', src/tests.rs:42:5
```

**Comment by jntrnr** [comment]
I'm trying to think through what might cause this. Looking through the code it seems that Nushell always tries to sync its environment to the parent. The code for this is in crates/nu-cli/src/utils.rs, with the logic starting at line 157.

If it's not already in the environment, it should run the Rust library logic to get `std::env::current_dir()` and then use this value as the initial PWD value.

@bowlofeggs - are you able to build it and run Nushell as a shell (even if as a secondary shell to your primary shell)? We might need to try a few things to isolate why the environment isn't being set up properly.

**Comment by bowlofeggs** [comment]
Hi @jntrnr,

If I modify the package such that it skips the tests, it does seem to work as a shell as far as I can tell. I can even see the `PWD` environment variable defined in the shell session.

I also do get passing tests when I run them inside an ordinary login shell in my environment.

It seems that there is something particular about the ebuild test environment that is causing these tests to fail. It is late so I must retire, but I'll poke some more at it in the coming days if nobody beats me to it.

**Comment by bowlofeggs** [comment]
I replaced the test block in the ebuild with this to see if that `current_dir()` function would return an `Ok` or `Err`, and it seems to work:

```
src_test() {
    rm -rf *
    cat <<- EOF > Cargo.toml
    [package]
    name = "delme2"
    version = "0.1.0"
    edition = "2021"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

    [dependencies]
    EOF
    mkdir src 
    cat <<- EOF > src/main.rs
    fn main() {
        println!("{:?}", std::env::current_dir());
    }
    EOF
    cargo run 
}
```

I see `Ok("/var/tmp/portage/app-shells/nushell-0.60.0/work/nushell-0.60.0")` in the output when I have this as the test block. So I think the Rust `current_dir()` function is able to work inside the Gentoo build environment.

**Comment by bowlofeggs** [comment]
I also tried `std::env::var("PWD")` and that gave the same output.

**Comment by ionenwks** [comment]
Interestingly, running `target/debug/nu -c pwd` gives the directory while `cargo run --bin nu -- -c pwd` fails with the same internal PWD error, not that I have any real idea of what's going on here atm because that only happens when ran through the ebuild.

**Comment by ionenwks** [comment]
Managed to reproduce outside portage by copying the environment, and by messing around, I ran into this:
```
Error: 
  × Environment variable was not captured: PORTAGE_COLORMAP='PORTAGE_COLOR_BAD=$''
```
This is the offending env var (set through bash)
`export PORTAGE_COLORMAP=$'PORTAGE_COLOR_BAD=$\'\E[31;01m\'\nPORTAGE_COLOR_BRACKET=$\'\E[34;01m\'\nPORTAGE_COLOR_ERR=$\'\E[31;01m\'\nPORTAGE_COLOR_GOOD=$\'\E[32;01m\'\nPORTAGE_COLOR_HILITE=$\'\E[36m\'\nPORTAGE_COLOR_INFO=$\'\E[32m\'\nPORTAGE_COLOR_LOG=$\'\E[32;01m\'\nPORTAGE_COLOR_NORMAL=$\'\E[0m\'\nPORTAGE_COLOR_QAWARN=$\'\E[33m\'\nPORTAGE_COLOR_WARN=$\'\E[33;01m\''`

And only triggers a failure when using cargo run, my guess is that cargo run may be modifying that in a way that confuses nu?

ebuild-wise, this lets the tests run:
```
export -n PORTAGE_COLORMAP
cargo_src_test
```

**Comment by jntrnr** [comment]
I wonder if it's related to this one at all: https://github.com/nushell/nushell/issues/4899

If so, there may be some bugs in the Nushell environment importer that can't properly handle the single quote.

**Comment by bowlofeggs** [comment]
@jntrnr It does seem like these could be the same issue, and they beat me to filing by exactly one ticket ☺ Feel free to close this if you want to track over there instead.

**Comment by hustcer** [comment]
@bowlofeggs https://github.com/nushell/nushell/issues/4899 has been fixed already, do you still have this issue?

**Comment by bowlofeggs** [comment]
@hustcer I confirmed in https://github.com/gentoo/gentoo/pull/25694 that the tests pass in 0.63.1 without our workaround, so I think we can mark this as closed/fixed. Thanks!
