### ISSUE TITLE
crash on ls -la

### ISSUE THREAD

**Issue by jonay2000** [nushell/nushell#5027]
### Describe the bug

I might be doing something wrong, I just started using nushell. However, I expected `ls -la` to give me an extended view of the current directory. Instead, it crashes nushell. Even if `ls -la` is not something you should do (I'm still quite new to the project, there might be another way to get this information) I didn't expect it to crash nu.

### How to reproduce

1. use nu v 0.60.0
2. run 'ls -la'

### Expected behavior

Not crash, ideally give me directory information

### Screenshots

![image](https://user-images.githubusercontent.com/22172241/160797256-c4fa4275-f5c0-4f53-83da-9ef9f0833ef8.png)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

### Additional context

on archlinux, installed from `community/nushell`

**Comment by kubouch** [comment]
I cannot reproduce this. Maybe it could be related to your locale setting?

**Comment by jonay2000** [comment]
hmm, anything I can run to verify this?

**Comment by jonay2000** [comment]
Both `ls -l` and `ls -a` work on their own. Only the combination breaks

**Comment by kubouch** [comment]
Can you share your locale? (run `locale`).

Also it would help if you could print the backtrace as the error message suggests, like this: `RUST_BACKTRACE=1 nu`.

And the best would be if you could compile nushell from source in a debug mode and get the backtrace from that. The pre-compiled binary won't have debug symbols so the backtrace above might not be very informative.

**Comment by fdncred** [comment]
`ls -la` works on my Mac too

**Comment by jonay2000** [comment]
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```
thread 'main' panicked at 'No such local time', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
stack backtrace:
   0:     0x557ab6ca2a44 - <unknown>
   1:     0x557ab602576c - <unknown>
   2:     0x557ab6c99c65 - <unknown>
   3:     0x557ab6ca5550 - <unknown>
   4:     0x557ab6ca51d9 - <unknown>
   5:     0x557ab6ca5b1c - <unknown>
   6:     0x557ab6c69e8f - <unknown>
   7:     0x557ab6c69e68 - <unknown>
   8:     0x557ab5c1316e - <unknown>
   9:     0x557ab600c6d2 - <unknown>
  10:     0x557ab600c46e - <unknown>
  11:     0x557ab635d3d5 - <unknown>
  12:     0x557ab6361844 - <unknown>
  13:     0x557ab6556392 - <unknown>
  14:     0x557ab6184bfd - <unknown>
  15:     0x557ab6556392 - <unknown>
  16:     0x557ab63a9259 - <unknown>
  17:     0x557ab6555d04 - <unknown>
  18:     0x557ab656007c - <unknown>
  19:     0x557ab611baa4 - <unknown>
  20:     0x557ab611deaf - <unknown>
  21:     0x557ab61237d6 - <unknown>
  22:     0x557ab60f01ad - <unknown>
  23:     0x557ab60fc52e - <unknown>
  24:     0x557ab60fef99 - <unknown>
  25:     0x557ab6ca2296 - <unknown>
  26:     0x557ab60f1c4c - <unknown>
  27:     0x7fa45e865310 - __libc_start_call_main
  28:     0x7fa45e8653c1 - __libc_start_main@GLIBC_2.2.5
  29:     0x557ab5c16215 - <unknown>
  30:                0x0 - <unknown>
```

**Comment by jonay2000** [comment]
what should it be set to? This is just the default locale generated while following the arch install guide, I've never seen LC_ALL set to anything different than nothing

**Comment by kubouch** [comment]
I have the same locale and don't have this error.

The backtrace is not very helpful with the stripped symbols :laughing: . It would help a lot if you could compile Nushell in a debug mode and get the backtrace from that.

**Comment by jonay2000** [comment]
I'll try, will update you soon ish, maybe tomorrow?

**Comment by fdncred** [comment]
> what should it be set to?

my understanding is that `LC_ALL` allows you to set all the `LC` items without individually setting them. so you could try setting it to `"en_US.UTF-8"` like all the rest. But if Kubouch has the same settings then that probably isn't the problem.

**Comment by uasi** [comment]
Since `-a` shows hidden files and `-l` shows more attributes, especially `created` and `accessed`, the cause might be the creation date or access date of some hidden file being corrupted.

**Comment by jonay2000** [comment]
okay, it seems that indeed, in my home directory, there's a file that's somehow corrupted. I'm not sure which, and I'm binary searching for it. I tried copying all files in home to another directory and removing them one by one and testing what breaks. However, copying the file fixes it (probably a modified timestamp is set and that's exactly the issue). I wont be deleting files from home of course. However, I still don't expect such things to crash nu.

**Comment by uasi** [comment]
`cp -a` (not nu's builtin `cp` but `/bin/cp`) can be used to copy files while preserving as many attributes as possible.

**Comment by fdncred** [comment]
I wonder how to reproduce this so we can test/fix it?

**Comment by kubouch** [comment]
It would be great to get the debug backtrace.

**Comment by jokeyrhyme** [comment]
Howdie, I noticed this issue when doing `ls -la /etc` and I've narrowed it down to specific files:

zsh:

```
% ls -la /etc/.#*
-rw------- 1 root root 1049 Mar 18 06:13 /etc/.#gshadowREDACTED
-rw------- 1 root root 1049 Jan 27 06:04 /etc/.#gshadowREDACTED
```

nushell:

```
❯ ls -la /etc/.#*
thread 'main' panicked at 'No such local time', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I checked-out and built the 0.61.0 tag 

<details>
<summary>RUST_BACKTRACE=1</summary>

```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:616:12
   1: chrono::offset::LocalResult<T>::unwrap
             at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
   2: chrono::offset::TimeZone::timestamp
             at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:325:9
   3: <chrono::datetime::DateTime<chrono::offset::utc::Utc> as core::convert::From<std::time::SystemTime>>::from
             at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:768:9
   4: <chrono::datetime::DateTime<chrono::offset::local::Local> as core::convert::From<std::time::SystemTime>>::from
             at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:775:9
   5: <T as core::convert::Into<U>>::into
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/convert/mod.rs:546:9
   6: nu_command::filesystem::ls::dir_entry_dict
             at ./crates/nu-command/src/filesystem/ls.rs:480:44
   7: <nu_command::filesystem::ls::Ls as nu_protocol::engine::command::Command>::run::{{closure}}
             at ./crates/nu-command/src/filesystem/ls.rs:187:41
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:269:13
   9: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:2603:32
  10: <core::iter::adapters::peekable::Peekable<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/peekable.rs:98:30
  11: core::iter::traits::iterator::Iterator::find_map
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:2609:9
  12: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/filter_map.rs:61:9
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  14: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  15: <nu_protocol::value::stream::ListStream as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/value/stream.rs:210:17
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  17: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  18: <nu_protocol::value::stream::ListStream as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/value/stream.rs:210:17
  19: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:3680:9
  20: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-command/src/viewers/table.rs:448:21
  21: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  22: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/value/stream.rs:88:19
  23: <nu_protocol::pipeline_data::PipelineIterator as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/pipeline_data.rs:466:18
  24: nu_cli::util::print_pipeline_data
             at ./crates/nu-cli/src/util.rs:57:25
  25: nu_cli::util::eval_source
             at ./crates/nu-cli/src/util.rs:291:31
  26: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:300:21
  27: nu::main
             at ./src/main.rs:262:21
  28: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

<details>
<summary>RUST_BACKTRACE=full</summary>

```
thread 'main' panicked at 'No such local time', /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
stack backtrace:
   0:     0x55589a48391d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55589a48391d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55589a48391d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55589a48391d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55589a4af67c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55589a47a068 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55589a4861f7 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55589a4861f7 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55589a4861f7 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55589a485ec0 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x555898ac00c3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h14ae2cd89b0df34e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1867:9
  11:     0x555898acd8da - nu::main::{{closure}}::hcc3f5de04d6111e8
                               at /home/ron/GitHub/nushell/nushell/src/main.rs:44:9
  12:     0x55589a486984 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  13:     0x55589a399f48 - std::panicking::begin_panic::{{closure}}::he25eb0af1ffe1a8e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:617:9
  14:     0x55589a39d7a9 - std::sys_common::backtrace::__rust_end_short_backtrace::h80db330d4361370a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x55589a399ec3 - std::panicking::begin_panic::hfbb86ad7dbcde0fc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:616:12
  16:     0x55589a36a5a7 - chrono::offset::LocalResult<T>::unwrap::h8e264a88701fccf4
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
  17:     0x55589a36d273 - chrono::offset::TimeZone::timestamp::h88a65f48d18fd45a
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:325:9
  18:     0x55589a36b20b - <chrono::datetime::DateTime<chrono::offset::utc::Utc> as core::convert::From<std::time::SystemTime>>::from::hd5a226a05bf43964
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:768:9
  19:     0x55589a36b2c7 - <chrono::datetime::DateTime<chrono::offset::local::Local> as core::convert::From<std::time::SystemTime>>::from::hf2daf2440c7bbbcd
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:775:9
  20:     0x555898ff2db7 - <T as core::convert::Into<U>>::into::h9d6eb2628cbd590f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/convert/mod.rs:546:9
  21:     0x555898b33b82 - nu_command::filesystem::ls::dir_entry_dict::h72569ad247879361
                               at /home/ron/GitHub/nushell/nushell/crates/nu-command/src/filesystem/ls.rs:480:44
  22:     0x555899000916 - <nu_command::filesystem::ls::Ls as nu_protocol::engine::command::Command>::run::{{closure}}::h031cfc00232d169e
                               at /home/ron/GitHub/nushell/nushell/crates/nu-command/src/filesystem/ls.rs:187:41
  23:     0x555898fffb75 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hcb6091f7d997825f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:269:13
  24:     0x55589909a2cf - core::iter::traits::iterator::Iterator::find_map::check::{{closure}}::h444196ab9d9783b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:2603:32
  25:     0x555898d64dab - <core::iter::adapters::peekable::Peekable<I> as core::iter::traits::iterator::Iterator>::try_fold::haaddab0a6eeef7d1
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/peekable.rs:98:30
  26:     0x555898d655b1 - core::iter::traits::iterator::Iterator::find_map::h07f2105d545f365b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:2609:9
  27:     0x555899058b64 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h81228e9722cb59ec
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  29:     0x55589a09049e - <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next::hb3cd557efee49289
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  30:     0x55589a0ff33d - <nu_protocol::value::stream::ListStream as core::iter::traits::iterator::Iterator>::next::h36f9451ef7e8faab
                               at /home/ron/GitHub/nushell/nushell/crates/nu-protocol/src/value/stream.rs:210:17
  31:     0x555898e2ed19 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hbdd91ce36e7f3bbb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  32:     0x55589a09049e - <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next::hb3cd557efee49289
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  33:     0x55589a0ff33d - <nu_protocol::value::stream::ListStream as core::iter::traits::iterator::Iterator>::next::h36f9451ef7e8faab
                               at /home/ron/GitHub/nushell/nushell/crates/nu-protocol/src/value/stream.rs:210:17
  34:     0x55589a092d3a - <&mut I as core::iter::traits::iterator::Iterator>::next::h2d1fc0f24746552c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/traits/iterator.rs:3680:9
  35:     0x555898c392a6 - <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next::h36fee1c4a96bb25a
                               at /home/ron/GitHub/nushell/nushell/crates/nu-command/src/viewers/table.rs:448:21
  36:     0x55589a09046e - <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next::h65e07cf5b2ceecc6
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1787:9
  37:     0x55589a0fe2ab - <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next::h409bb18bde8451fc
                               at /home/ron/GitHub/nushell/nushell/crates/nu-protocol/src/value/stream.rs:88:19
  38:     0x55589a0cff9f - <nu_protocol::pipeline_data::PipelineIterator as core::iter::traits::iterator::Iterator>::next::h9f26bd007087c58c
                               at /home/ron/GitHub/nushell/nushell/crates/nu-protocol/src/pipeline_data.rs:466:18
  39:     0x555899a6475e - nu_cli::util::print_pipeline_data::h4e100dda2da529d9
                               at /home/ron/GitHub/nushell/nushell/crates/nu-cli/src/util.rs:57:25
  40:     0x555899a67ccd - nu_cli::util::eval_source::h9c74ed37dc0b5d9a
                               at /home/ron/GitHub/nushell/nushell/crates/nu-cli/src/util.rs:291:31
  41:     0x555899abe3e1 - nu_cli::repl::evaluate_repl::h55ca4114067e8220
                               at /home/ron/GitHub/nushell/nushell/crates/nu-cli/src/repl.rs:300:21
  42:     0x555898ae6495 - nu::main::h7e47db088a77a62f
                               at /home/ron/GitHub/nushell/nushell/src/main.rs:262:21
  43:     0x555898ad23eb - core::ops::function::FnOnce::call_once::h6b130d5835a2eecb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  44:     0x555898acfcfe - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f40288334588f11
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  45:     0x555898acb9d1 - std::rt::lang_start::{{closure}}::h36d852c705b1166e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:18
  46:     0x55589a483001 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  47:     0x55589a483001 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  48:     0x55589a483001 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  49:     0x55589a483001 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  50:     0x55589a483001 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  51:     0x55589a483001 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  52:     0x55589a483001 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  53:     0x55589a483001 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  54:     0x55589a483001 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  55:     0x555898acb9a0 - std::rt::lang_start::h3524f74291679fe3
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
  56:     0x555898ae9eec - main
  57:     0x7f5067b5c310 - __libc_start_call_main
  58:     0x7f5067b5c3c1 - __libc_start_main@GLIBC_2.2.5
  59:     0x555898abd145 - _start
  60:                0x0 - <unknown>
```

</details>

**Comment by uasi** [comment]
corresponding source code:

```
thread 'main' panicked at 'No such local time', /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34

  17:     0x55589a36d273 - chrono::offset::TimeZone::timestamp::h88a65f48d18fd45a
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:325:9
  18:     0x55589a36b20b - <chrono::datetime::DateTime<chrono::offset::utc::Utc> as core::convert::From<std::time::SystemTime>>::from::hd5a226a05bf43964
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:768:9
  19:     0x55589a36b2c7 - <chrono::datetime::DateTime<chrono::offset::local::Local> as core::convert::From<std::time::SystemTime>>::from::hf2daf2440c7bbbcd
                               at /home/ron/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/datetime.rs:775:9
  20:     0x555898ff2db7 - <T as core::convert::Into<U>>::into::h9d6eb2628cbd590f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/convert/mod.rs:546:9
```

https://github.com/chronotope/chrono/blob/4eeedcfcc409f19d965f477d767d05f3418c4df1/src/offset/mod.rs#L171-L180

https://github.com/chronotope/chrono/blob/4eeedcfcc409f19d965f477d767d05f3418c4df1/src/offset/mod.rs#L324-L326

https://github.com/chronotope/chrono/blob/4eeedcfcc409f19d965f477d767d05f3418c4df1/src/datetime.rs#L755-L768

---

```
  21:     0x555898b33b82 - nu_command::filesystem::ls::dir_entry_dict::h72569ad247879361
                               at /home/ron/GitHub/nushell/nushell/crates/nu-command/src/filesystem/ls.rs:480:44
```


https://github.com/nushell/nushell/blob/3783c19d02f4a3b2f35cd26b79daabcb70b04880/crates/nu-command/src/filesystem/ls.rs#L478-L485

**Comment by uasi** [comment]
It seems that chrono is failing to convert the file creation date into `DateTime<Local>`.

@jokeyrhyme can you paste the output of `% stat /etc/.#*` ?

**Comment by jokeyrhyme** [comment]
```
❯ ls -la /etc/.#gshadowREDACTED
thread 'main' panicked at 'No such local time', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/offset/mod.rs:173:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

... (restarting shell after the panic)

❯ stat /etc/./.#gshadowREDACTED
  File: /etc/./.
  Size: 3700            Blocks: 0          IO Block: 4096   directory
Device: 0,33    Inode: 264         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-19 03:09:51.394252024 +1000
Modify: 2022-04-18 05:44:58.054916202 +1000
Change: 2022-04-18 05:44:58.054916202 +1000
 Birth: 7146772199173811201.1701340001
```

**Comment by uasi** [comment]
Thanks, that's indeed weird. We need to convert those values to `$nothing`.

**Comment by kubouch** [comment]
Thanks for investigating everybody! The code locations from @uasi are very useful. Seems like we need to check in advance the `SystemTime` we get from `creted()` before converting it to `DateTime` with `into()`. I'm not sure if the `chrono` library has any tools for that. It is a bit disappointing it just panics instead of returning a Result.
