### ISSUE TITLE
timestamp parsing error on 32 bit platforms

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#5191]
### Describe the bug

cargo test will fail on 32 bit platforms

```
failures:

---- commands::touch::create_and_change_modified_and_access_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -t 201908241230 i_will_be_created.txt
   ·          ──────┬─────
   ·                ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::create_and_change_modified_and_access_time_of_file' panicked at 'assertion failed: path.exists()', crates/nu-command/tests/commands/touch.rs:508:9

---- commands::touch::change_modified_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -m -t 201908241230.30 file.txt
   ·             ───────┬───────
   ·                    ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_modified_time_of_file' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.510902699+00:00`', crates/nu-command/tests/commands/touch.rs:51:9

---- commands::touch::change_modified_and_access_time_of_files stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -a -m -t 1908241230.30 file.txt file2.txt
   ·                ──────┬──────
   ·                      ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_modified_and_access_time_of_files' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.487569308+00:00`', crates/nu-command/tests/commands/touch.rs:585:9

---- commands::touch::change_modified_time_of_files stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -m -t 1908241230.30 file.txt file2.txt
   ·             ──────┬──────
   ·                   ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_modified_time_of_files' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.577569530+00:00`', crates/nu-command/tests/commands/touch.rs:133:9

---- commands::touch::create_and_change_modified_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -m -t 201908241230 i_will_be_created.txt
   ·             ──────┬─────
   ·                   ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::create_and_change_modified_time_of_file' panicked at 'assertion failed: path.exists()', crates/nu-command/tests/commands/touch.rs:64:9

---- commands::touch::change_access_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -a -t 201908241230.30 file.txt
   ·             ───────┬───────
   ·                    ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_access_time_of_file' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.350902300+00:00`', crates/nu-command/tests/commands/touch.rs:272:9

---- commands::touch::change_access_time_of_files stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -a -t 1908241230.30 file.txt file2.txt
   ·             ──────┬──────
   ·                   ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_access_time_of_files' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.404235766+00:00`', crates/nu-command/tests/commands/touch.rs:354:9

---- commands::touch::change_modified_and_access_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -m -a -t 201908241230.30 file.txt
   ·                ───────┬───────
   ·                       ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::change_modified_and_access_time_of_file' panicked at 'assertion failed: `(left == right)`
  left: `2019-08-24T12:30:30+00:00`,
 right: `2022-04-13T19:17:35.440902525+00:00`', crates/nu-command/tests/commands/touch.rs:494:9

---- commands::touch::create_and_change_access_time_of_file stdout ----
=== stderr
Error: nu::shell::unsupported_input (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.UnsupportedInput)

  × Unsupported input
   ╭─[source:1:1]
 1 │ touch -a -t 201908241230 i_will_be_created.txt
   ·             ──────┬─────
   ·                   ╰── input has an invalid timestamp
   ╰────


thread 'commands::touch::create_and_change_access_time_of_file' panicked at 'assertion failed: path.exists()', crates/nu-command/tests/commands/touch.rs:285:9


failures:
    commands::touch::change_access_time_of_file
    commands::touch::change_access_time_of_files
    commands::touch::change_modified_and_access_time_of_file
    commands::touch::change_modified_and_access_time_of_files
    commands::touch::change_modified_time_of_file
    commands::touch::change_modified_time_of_files
    commands::touch::create_and_change_access_time_of_file
    commands::touch::create_and_change_modified_and_access_time_of_file
    commands::touch::create_and_change_modified_time_of_file

test result: FAILED. 495 passed; 9 failed; 46 ignored; 0 measured; 0 filtered out; finished in 5.08s

error: test failed, to rerun pass '-p nu-command --test main'
```

### How to reproduce

1. cargo test

### Expected behavior

cargo test should not fail on 32 bit platform

**Comment by fdncred** [comment]
nice fix. are you going to submit that as a pr?

**Comment by fdncred** [comment]
thanks for the pr
