### ISSUE TITLE
When there's not enough space for table a panic is issued

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#5686]
### Describe the bug

Hi there

I've just noticed this issue on `main` branch.

```
ls | table -w 3
```

```
thread 'main' panicked at 'attempt to subtract with overflow', crates/nu-table/src/table.rs:754:14
```

### How to reproduce

...

### Expected behavior

...

**Comment by VergeDX** [comment]
Looks fine on my `0.63.1` version nushell, I will start investigating this on `master`.

![image](https://user-images.githubusercontent.com/25173827/171004795-9b63e858-5af9-42b6-8c3f-1b455ee514b0.png)

**Comment by VergeDX** [comment]
Update: If I drop all default environment config files, branch `0.63.1` is broken. :smiling_face_with_tear:  
`RUST_BACKTRACE=full` reports subtract with overflow, at `crates/nu-table/src/table.rs:754:14`.

**Comment by VergeDX** [comment]
I just make sure `termwidth` > 0: https://github.com/nushell/nushell/blob/0.63.1/crates/nu-table/src/table.rs#L502=  
But it seems there is some another numbers needs to be subtract: https://github.com/nushell/nushell/blob/0.63.1/crates/nu-table/src/table.rs#L754=

**Comment by elferherrera** [comment]
That needs to be a protected substraction

**Comment by VergeDX** [comment]
> That needs to be a protected subtraction

So should we do something like this?

```````patch
diff --git a/crates/nu-table/src/table.rs b/crates/nu-table/src/table.rs
index 3c0cd401..6e34e75f 100644
--- a/crates/nu-table/src/table.rs
+++ b/crates/nu-table/src/table.rs
@@ -5,6 +5,7 @@ use nu_ansi_term::Style;
 use nu_protocol::{Config, FooterMode};
 use std::collections::HashMap;
 use std::fmt::Write;
+use std::num::Wrapping;
 
 enum SeparatorPosition {
     Top,
@@ -750,10 +751,18 @@ impl ColumnSpace {
             overage_separator_sum,
         } = self;
 
-        if *num_overages > 0 {
-            (termwidth - 1 - *underage_sum - *overage_separator_sum) / *num_overages
+        let termwidth = Wrapping(termwidth);
+        let one = Wrapping(1);
+        let underage_sum = Wrapping(*underage_sum);
+        let overage_separator_sum = Wrapping(*overage_separator_sum);
+        let num_overages = Wrapping(*num_overages);
+
+        let result = if num_overages > Wrapping(0) {
+            (termwidth - one - underage_sum - overage_separator_sum) / num_overages
         } else {
-            99999
-        }
+            Wrapping(99999)
+        };
+
+        result.0
     }
 }
```````

**Comment by VergeDX** [comment]
You are right, did you mean to do something like this?

```````patch
diff --git a/crates/nu-table/src/table.rs b/crates/nu-table/src/table.rs
index 3c0cd401..ee5c3ac6 100644
--- a/crates/nu-table/src/table.rs
+++ b/crates/nu-table/src/table.rs
@@ -751,7 +751,9 @@ impl ColumnSpace {
         } = self;
 
         if *num_overages > 0 {
-            (termwidth - 1 - *underage_sum - *overage_separator_sum) / *num_overages
+            termwidth.checked_sub(*underage_sum).unwrap_or_default()
+                .checked_sub(*overage_separator_sum).unwrap_or_default()
+                .checked_div(*num_overages).unwrap_or_default()
         } else {
             99999
         }
```````

**Comment by VergeDX** [comment]
You are right, is this way acceptable? 

```````patch
diff --git a/crates/nu-table/src/table.rs b/crates/nu-table/src/table.rs
index 3c0cd401..8ff52291 100644
--- a/crates/nu-table/src/table.rs
+++ b/crates/nu-table/src/table.rs
@@ -503,6 +503,7 @@ pub fn draw_table(
         return format!("Couldn't fit table into {} columns!", termwidth);
     }
 
+    let raw_termwidth = termwidth.clone();
     let termwidth = termwidth - edges_width;
 
     let mut processed_table = process_table(table);
@@ -532,11 +533,15 @@ pub fn draw_table(
     // This gives us the max column width
     let max_column_width = column_space.max_width(termwidth);
 
+    if max_column_width.is_none() {
+        return format!("Couldn't fit table into {} columns!", raw_termwidth);
+    }
+
     // This width isn't quite right, as we're rounding off some of our space
     let column_space = column_space.fix_almost_column_width(
         &max_per_column,
         max_naive_column_width,
-        max_column_width,
+        max_column_width.unwrap(),
         headers_len,
     );
 
@@ -549,7 +554,7 @@ pub fn draw_table(
 
     let wrapped_table = wrap_cells(
         processed_table,
-        max_column_width,
+        max_column_width.unwrap(),
         color_hm,
         &re_leading,
         &re_trailing,
@@ -743,7 +748,7 @@ impl ColumnSpace {
         }
     }
 
-    fn max_width(&self, termwidth: usize) -> usize {
+    fn max_width(&self, termwidth: usize) -> Option<usize> {
         let ColumnSpace {
             num_overages,
             underage_sum,
@@ -751,9 +756,15 @@ impl ColumnSpace {
         } = self;
 
         if *num_overages > 0 {
-            (termwidth - 1 - *underage_sum - *overage_separator_sum) / *num_overages
+            // (termwidth - 1 - *underage_sum - *overage_separator_sum) / *num_overages;
+
+            termwidth
+                .checked_sub(1)?
+                .checked_sub(*underage_sum)?
+                .checked_sub(*overage_separator_sum)?
+                .checked_div(*num_overages)
         } else {
-            99999
+            Some(99999)
         }
     }
 }
```````

**Comment by elferherrera** [comment]
is there a way to remove the `unwrap`? Does it make sense to add a min default value to deal with it?

**Comment by elferherrera** [comment]
you could do something like this
```
 let column_space = match max_column_width {
   None => return format!("Couldn't fit table into {} columns!", raw_termwidth),
   Some(max_column_width) => column_space.fix_almost_column_width(
         &max_per_column,
         max_naive_column_width,
        max_column_width,
         headers_len,
     )
}
```

**Comment by elferherrera** [comment]
looks nice. Do you mind submitting a PR so we can check it better?
