### ISSUE TITLE
panic: cd, "index out of bounds" when autocompleting path with special character.

### ISSUE THREAD

**Issue by Rabjerg** [nushell/nushell#577]
**Version:**
nushell-git r944.3d912a2-1

**Issue:**

Panic.
When trying to autocomplete a Directory, and having a special characher [öäüæøåáàéè ... ] in the argument for cd, nushell crashes. 

**Expected behavior:** 
Not-crashing.

**How to reproduce:**
`$/any/path/ cd ü <tab>`

**Trace:**

```
$ RUST_BACKTRACE=full nu

/home/adam/git/nushell(Dockerfile_cleanup)> cd üthread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0:     0x55774d52c692 - <unknown>
   1:     0x55774d52c376 - <unknown>
   2:     0x55774d52cde5 - <unknown>
   3:     0x55774d52c982 - <unknown>
   4:     0x55774d52c876 - <unknown>
   5:     0x55774d54f0da - <unknown>
   6:     0x55774d54f095 - <unknown>
   7:     0x55774d0bc199 - <unknown>
   8:     0x55774d0024ad - <unknown>
   9:     0x55774d003131 - <unknown>
  10:     0x55774cf95cfa - <unknown>
  11:     0x55774cf44fec - <unknown>
  12:     0x55774cf4a65a - <unknown>
  13:     0x55774cf741c6 - <unknown>
  14:     0x55774cf861af - <unknown>
  15:     0x55774cf5fd9d - <unknown>
  16:     0x55774cf5a687 - <unknown>
  17:     0x55774d52c813 - <unknown>
  18:     0x55774d5367ba - <unknown>
  19:     0x55774d52d2dd - <unknown>
  20:     0x55774cf5ff92 - <unknown>
  21:     0x7f90c52adee3 - __libc_start_main
  22:     0x55774cf433be - <unknown>
  23:                0x0 - <unknown>
```

**Comment by jonathandturner** [comment]
Thank you for the report. I was able to repro it on a debug build. Posting the backtrace here so we can follow up:

```
> cd üthread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libcore/slice/mod.rs:2715
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libcore/slice/mod.rs:2566
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/liballoc/vec.rs:1791
  14: nu::shell::completer::NuCompleter::complete
             at src/shell/completer.rs:43
  15: <nu::shell::filesystem_shell::FilesystemShell as nu::shell::shell::Shell>::complete
             at src/shell/filesystem_shell.rs:976
  16: nu::shell::shell_manager::ShellManager::complete
             at src/shell/shell_manager.rs:75
  17: <nu::shell::helper::Helper as rustyline::completion::Completer>::complete
             at src/shell/helper.rs:32
  18: rustyline::complete_line
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-5.0.2/src/lib.rs:73
  19: rustyline::readline_edit
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-5.0.2/src/lib.rs:410
  20: rustyline::readline_raw
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-5.0.2/src/lib.rs:625
  21: rustyline::Editor<H>::readline_with
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-5.0.2/src/lib.rs:753
  22: rustyline::Editor<H>::readline
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-5.0.2/src/lib.rs:729
  23: nu::cli::cli::{{closure}}
             at ./src/cli.rs:281
  24: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/future.rs:42
  25: std::future::set_task_context
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/future.rs:78
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/future.rs:42
  27: futures_executor::local_pool::block_on::{{closure}}
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  28: futures_executor::local_pool::run_executor::{{closure}}
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:68
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/thread/local.rs:262
  30: std::thread::local::LocalKey<T>::with
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/thread/local.rs:239
  31: futures_executor::local_pool::run_executor
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:64
  32: futures_executor::local_pool::block_on
             at /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  33: nu::main
             at src/main.rs:53
  34: std::rt::lang_start::{{closure}}
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/rt.rs:64
  35: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  36: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  38: std::panicking::try
             at src/libstd/panicking.rs:275
  39: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  40: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  41: std::rt::lang_start
             at /rustc/72b2abfd65ba024e12d7fe51852a309419f494d8/src/libstd/rt.rs:64
  42: main
  43: __libc_start_main
  44: _start
```
