### ISSUE TITLE
`from nuon` panics when trying to open `$nu.plugin-path`

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#5996]
### Describe the bug

thread 'main' panicked at 'internal error: can't find PWD'

I realize that `$nu.plugin-path` isn't necessarily in nuon format since it begins with the command line to register a plugin. However, it still shouldn't panic.

### How to reproduce

```
> open $nu.plugin-path | from nuon
thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1534:14
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: nu_protocol::engine::engine_state::StateWorkingSet::get_cwd
   6: nu_parser::parse_keywords::parse_register
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  10: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
  11: nu_parser::parser::parse_block
  12: <nu_command::formats::from::nuon::FromNuon as nu_protocol::engine::command::Command>::run
  13: nu_engine::eval::eval_call
  14: nu_engine::eval::eval_expression_with_input
  15: nu_engine::eval::eval_block
  16: nu_cli::util::eval_source
  17: nu_cli::repl::evaluate_repl
  18: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

not panic

### Configuration

|key|value|
|-|-|
|version|0.65.1|
|branch|main|
|commit_hash|125e60d06a09eba0b564eca0cff4d110b8082192|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.62.0 (a8314ef7d 2022-06-27)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.62.0 (a748cf5a3 2022-06-08)|
|pkg_version|0.65.1|
|build_time|2022-07-08 09:19:13 -05:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|gstat, query, query json, query web, query xml|

**Comment by sholderbach** [comment]
Another different backtrace from `open $nu.config-path | from nuon` on `e1d5180e`

```
thread 'main' panicked at 'internal error: missing module command', crates/nu-parser/src/parse_keywords.rs:1442:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:738:21
   6: nu_parser::parse_keywords::parse_module
             at ./crates/nu-parser/src/parse_keywords.rs:1440:30
   7: nu_parser::parser::parse_builtin_commands
             at ./crates/nu-parser/src/parser.rs:4828:22
   8: nu_parser::parser::parse_block::{{closure}}
             at ./crates/nu-parser/src/parser.rs:5009:43
   9: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/adapters/map.rs:84:28
  10: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/adapters/enumerate.rs:106:27
  11: core::iter::traits::iterator::Iterator::fold
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:2370:21
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/adapters/enumerate.rs:112:9
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/adapters/map.rs:124:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:787:9
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/spec_extend.rs:40:17
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/spec_from_iter.rs:33:9
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:2645:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:1792:9
  20: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
             at ./crates/nu-protocol/src/ast/block.rs:65:24
  21: <T as core::convert::Into<U>>::into
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/convert/mod.rs:550:9
  22: nu_parser::parser::parse_block
             at ./crates/nu-parser/src/parser.rs:4968:24
  23: <nu_command::formats::from::nuon::FromNuon as nu_protocol::engine::command::Command>::run
             at ./crates/nu-command/src/formats/from/nuon.rs:93:13
  24: nu_engine::eval::eval_call
             at ./crates/nu-engine/src/eval.rs:170:9
  25: nu_engine::eval::eval_expression_with_input
             at ./crates/nu-engine/src/eval.rs:647:25
  26: nu_engine::eval::eval_block
             at ./crates/nu-engine/src/eval.rs:751:31
  27: nu_cli::util::eval_source
             at ./crates/nu-cli/src/util.rs:233:11
  28: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:458:21
  29: nu::main
             at ./src/main.rs:458:31
  30: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by kubouch** [comment]
This bug is probably my fault as it involves `module` and `$env.PWD`. I'm not sure why we're checking for PWD there.
