### ISSUE TITLE
Crash on tab completion after empty environment variable prefix

### ISSUE THREAD

**Issue by schuelermine** [nushell/nushell#6269]
### Describe the bug

If you write an empty environment variable prefix like `PATH=` and then trigger tab completion a space after, nushell crashes

### How to reproduce

1. Write `PATH= `.
2. Press <kbd>⭾ Tab</kbd>.

### Expected behavior

I expected nu to not crash

### Screenshots

https://asciinema.org/a/P0M6NFtgt1zo7Qv1IfNrzNuom

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1                                    |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by jonasohland** [comment]
Had the same thing happen to me. Here is a backtrace:

```
thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:577:9 AM
stack backtrace:
   0:     0x55c8da7c891d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c8da7c891d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c8da7c891d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55c8da7c891d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55c8da7f4acc - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55c8da7be9a8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55c8da7cb247 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55c8da7cb247 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55c8da7cb247 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55c8da7caf10 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x55c8d8877dc3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::heb96a6258f35f0c5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1867:9
  11:     0x55c8d8867e7a - nu::main::{{closure}}::hb412f10c853a588f
                               at /home/ohlano/nushell/src/main.rs:44:9
  12:     0x55c8da7cb9d4 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  13:     0x55c8da7cb649 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13
  14:     0x55c8da7c8de4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x55c8da7cb399 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  16:     0x55c8d8855eb3 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  17:     0x55c8da239a30 - nu_protocol::engine::engine_state::EngineState::get_span_contents::hdad0ccc9cb1c5077
                               at /home/ohlano/nushell/crates/nu-protocol/src/engine/engine_state.rs:577:9
  18:     0x55c8da23de23 - nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents::h8ad775523d0bce43
                               at /home/ohlano/nushell/crates/nu-protocol/src/engine/engine_state.rs:1294:20
  19:     0x55c8d99c0e60 - nu_cli::completions::completer::most_left_variable::h36f6eb5fd1ba4278
                               at /home/ohlano/nushell/crates/nu-cli/src/completions/completer.rs:354:22
  20:     0x55c8d99be3b1 - nu_cli::completions::completer::NuCompleter::completion_helper::hecdc35f4542bc4a4
                               at /home/ohlano/nushell/crates/nu-cli/src/completions/completer.rs:77:29
  21:     0x55c8d99bfab4 - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::h6ac0ff684ad191a5
                               at /home/ohlano/nushell/crates/nu-cli/src/completions/completer.rs:254:9
  22:     0x55c8d9b46200 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::hea4e573ae0469ed2
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/menu/columnar_menu.rs:543:17
  23:     0x55c8d9b9f8f0 - reedline::menu::ReedlineMenu::update_values::h8498f7228be339f1
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/menu/mod.rs:186:44
  24:     0x55c8d9b8c88f - reedline::engine::Reedline::handle_editor_event::h87275d579f932696
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:660:29
  25:     0x55c8d9b8cc18 - reedline::engine::Reedline::handle_editor_event::h87275d579f932696
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:944:27
  26:     0x55c8d9b8a95d - reedline::engine::Reedline::handle_event::h1e97f14d2fa58f86
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:533:13
  27:     0x55c8d9b8a4b5 - reedline::engine::Reedline::read_line_helper::ha00ca9af1978494f
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:510:23
  28:     0x55c8d9b89482 - reedline::engine::Reedline::read_line::h73f392c3b1edf8a7
                               at /home/ohlano/.cargo/git/checkouts/reedline-e42026a78d91c510/a406bfc/src/engine.rs:407:22
  29:     0x55c8d996858e - nu_cli::repl::evaluate_repl::h6974f438423ec20b
                               at /home/ohlano/nushell/crates/nu-cli/src/repl.rs:308:21
  30:     0x55c8d886db1f - nu::main::h44c8c36f655e2f56
                               at /home/ohlano/nushell/src/main.rs:339:31
  31:     0x55c8d887410b - core::ops::function::FnOnce::call_once::h2477cdda47169a03
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  32:     0x55c8d885bbbe - std::sys_common::backtrace::__rust_begin_short_backtrace::hf5d8283fe5e2866e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  33:     0x55c8d8876961 - std::rt::lang_start::{{closure}}::h88273305c4cb1f8e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:18
  34:     0x55c8da7c8001 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  35:     0x55c8da7c8001 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  36:     0x55c8da7c8001 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  37:     0x55c8da7c8001 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  38:     0x55c8da7c8001 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  39:     0x55c8da7c8001 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  40:     0x55c8da7c8001 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  41:     0x55c8da7c8001 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  42:     0x55c8da7c8001 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  43:     0x55c8d8876930 - std::rt::lang_start::hfe4f02c99c0cabf5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
  44:     0x55c8d887326c - main
  45:     0x7f96e3a3f2d0 - <unknown>
  46:     0x7f96e3a3f38a - __libc_start_main
  47:     0x55c8d8856735 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  48:                0x0 - <unknown>

```
