### ISSUE TITLE
Crash on tab completion when using the $in variable in a multi-line pipeline

### ISSUE THREAD

**Issue by fantasyzhjk** [nushell/nushell#6287]
### Describe the bug

Crash on tab completion when using the $in variable in a multi-line pipeline

### How to reproduce

1. input this
```
(
'any data'
| $in
)
```
2. move the shell cursor after the '(' in the first line
3. press TAB

### Expected behavior

not crash

### Screenshots

![image](https://user-images.githubusercontent.com/57699176/183905194-6e8a2588-278a-4a8a-a394-c34095e1aad8.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:20:39 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the bug report! I am able to reproduce this, here's the backtrace:

```
(thread 'main' panicked at 'slice index starts at 3 but ends at 1', library\core\src\slice\index.rs:92:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
   2: core::slice::index::slice_index_order_fail_rt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\slice\index.rs:92
   3: core::ops::function::FnOnce::call_once<never$ (*)(usize,usize),tuple$<usize,usize> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\ops\function.rs:248
   4: core::intrinsics::const_eval_select<tuple$<usize,usize>,never$ (*)(usize,usize),never$ (*)(usize,usize),never$>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\intrinsics.rs:2372
   5: core::slice::index::slice_index_order_fail
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\slice\index.rs:87
   6: core::slice::index::impl$3::index<u8>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\slice\index.rs:302
   7: core::slice::index::impl$0::index<u8,core::ops::range::Range<usize> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\slice\index.rs:18
   8: alloc::vec::impl$16::index<u8,core::ops::range::Range<usize>,alloc::alloc::Global>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\alloc\src\vec\mod.rs:2591
   9: nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents
             at .\github\nushell\crates\nu-protocol\src\engine\engine_state.rs:1278
  10: nu_cli::completions::command_completions::CommandCompletion::complete_commands
             at .\github\nushell\crates\nu-cli\src\completions\command_completions.rs:81
  11: nu_cli::completions::command_completions::impl$1::fetch
             at .\github\nushell\crates\nu-cli\src\completions\command_completions.rs:184
  12: nu_cli::completions::completer::NuCompleter::process_completion<nu_cli::completions::command_completions::CommandCompletion>
             at .\github\nushell\crates\nu-cli\src\completions\completer.rs:51
  13: nu_cli::completions::completer::NuCompleter::completion_helper
             at .\github\nushell\crates\nu-cli\src\completions\completer.rs:217
  14: nu_cli::completions::completer::impl$1::complete
             at .\github\nushell\crates\nu-cli\src\completions\completer.rs:254
  15: reedline::menu::columnar_menu::impl$4::update_values
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\menu\columnar_menu.rs:543
  16: enum$<reedline::menu::ReedlineMenu>::update_values
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\menu\mod.rs:186
  17: reedline::engine::Reedline::handle_editor_event
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\engine.rs:660
  18: reedline::engine::Reedline::handle_editor_event
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\engine.rs:944
  19: reedline::engine::Reedline::handle_event
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\engine.rs:533
  20: reedline::engine::Reedline::read_line_helper
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\engine.rs:510
  21: reedline::engine::Reedline::read_line
             at .\.cargo\git\checkouts\reedline-e42026a78d91c510\59f7144\src\engine.rs:407
  22: nu_cli::repl::evaluate_repl
             at .\github\nushell\crates\nu-cli\src\repl.rs:275
  23: nu::main
             at .\github\nushell\src\main.rs:299
  24: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fdncred** [comment]
can you confirm that this is fixed in the latest main branch please?

**Comment by fantasyzhjk** [comment]
yes it is fixed now
