### ISSUE TITLE
Nushell crashes when displaying user folder

### ISSUE THREAD

**Issue by Beidah** [nushell/nushell#6574]
### Describe the bug

On windows, Nushell crashes when I use the `ls` command on C:\\Users\\\<User>.

Displayed is the error:
```
thread 'main' panicked at 'SystemTimeToFileTime failed with: The parameter is incorrect. (os error 87)', C:\Users\Hunter\.cargo\registry\src\github.com-1ecc6299db9ec823\chrono-0.4.22\src\offset\local\windows.rs:263:9
```

### How to reproduce

1. Navigate to `C:\Users\<User>`
2. Run `ls`

### Expected behavior

Display files and sub-directories in the current directory, not crash.

### Screenshots

![image](https://user-images.githubusercontent.com/11290259/190841730-1a5db2d4-1b55-4351-a9b4-2fc77aa6415c.png)
![image](https://user-images.githubusercontent.com/11290259/190841748-1805b79c-c98e-4235-9c37-a2542d584bef.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-16 21:02:25 -05:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Beidah** [comment]
With `RUST_BACKTRACE=1`, I didn't get anything new, but it suggested to set it to `full` instead. This is the backtrace I got then: 
```
thread 'main' panicked at 'SystemTimeToFileTime failed with: The parameter is incorrect. (os error 87)', C:\Users\Hunter\.cargo\registry\src\github.com-1ecc6299db9ec823\chrono-0.4.22\src\offset\local\windows.rs:263:9
stack backtrace:
   0:     0x7ff76beb3254 - <unknown>
   1:     0x7ff76aaa6c9a - <unknown>
   2:     0x7ff76bea9b29 - <unknown>
   3:     0x7ff76beb69fb - <unknown>
   4:     0x7ff76beb6695 - <unknown>
   5:     0x7ff76beb70d2 - <unknown>
   6:     0x7ff76beb6e73 - <unknown>
   7:     0x7ff76beb47c7 - <unknown>
   8:     0x7ff76beb6b6f - <unknown>
   9:     0x7ff76c0921b5 - <unknown>
  10:     0x7ff76aa9023f - <unknown>
  11:     0x7ff76ad0e376 - <unknown>
  12:     0x7ff76afc86cf - <unknown>
  13:     0x7ff76ace8785 - <unknown>
  14:     0x7ff76ae5653f - <unknown>
  15:     0x7ff76b3d024a - <unknown>
  16:     0x7ff76ae56341 - <unknown>
  17:     0x7ff76b3d024a - <unknown>
  18:     0x7ff76b09058c - <unknown>
  19:     0x7ff76b3cfa88 - <unknown>
  20:     0x7ff76b40ef91 - <unknown>
  21:     0x7ff76b40e6b8 - <unknown>
  22:     0x7ff76b40e20f - <unknown>
  23:     0x7ff76abd0c56 - <unknown>
  24:     0x7ff76abd7924 - <unknown>
  25:     0x7ff76ab9f450 - <unknown>
  26:     0x7ff76abaefca - <unknown>
  27:     0x7ff76abaefdc - <unknown>
  28:     0x7ff76bea16b7 - <unknown>
  29:     0x7ff76aba3de7 - <unknown>
  30:     0x7ff76c08db6c - <unknown>
  31:     0x7ffb72487034 - BaseThreadInitThunk
  32:     0x7ffb734026a1 - RtlUserThreadStart
```

**Comment by cptpiepmatz** [comment]
Closing this as it seems not to be reproducible.
