### ISSUE TITLE
Panic when running 'which raw | get value' (Linux, version 0.3.0)

### ISSUE THREAD

**Issue by futile** [nushell/nushell#707]
Running `nu` on `Linux 5.3.1-arch1-1-ARCH` (archlinux).

Error is:

```
[~]$ RUST_BACKTRACE=full nu                                                                                                                                                                                         
/home/felix> version
━━━━━━━━━
 version 
─────────
 0.3.0 
━━━━━━━━━
/home/felix> which raw
━━━━━━━━━━━━━━
 value 
──────────────
 /usr/bin/raw 
━━━━━━━━━━━━━━
/home/felix> which raw | get value
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/1dd1884891636d0eb51157d137230076bcf20627/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0:     0x5637cd7092d4 - <unknown>
   1:     0x5637cd73320c - <unknown>
   2:     0x5637cd703eb7 - <unknown>
   3:     0x5637cd70be85 - <unknown>
   4:     0x5637cd70bb76 - <unknown>
   5:     0x5637cd70c585 - <unknown>
   6:     0x5637cd70c122 - <unknown>
   7:     0x5637cd70c016 - <unknown>
   8:     0x5637cd72ee5a - <unknown>
   9:     0x5637cd72ee15 - <unknown>
  10:     0x5637cd0c9c72 - <unknown>
  11:     0x5637cd22600a - <unknown>
  12:     0x5637cd1d956e - <unknown>
  13:     0x5637cd279bb5 - <unknown>
  14:     0x5637cd0a555b - <unknown>
  15:     0x5637cd0a13f6 - <unknown>
  16:     0x5637cd0765af - <unknown>
  17:     0x5637cd08338e - <unknown>
  18:     0x5637cd08c91c - <unknown>
  19:     0x5637cd08d257 - <unknown>
  20:     0x5637cd70bfb3 - <unknown>
  21:     0x5637cd715dca - <unknown>
  22:     0x5637cd70ca7d - <unknown>
  23:     0x5637cd08ca62 - <unknown>
  24:     0x7f4f000efee3 - __libc_start_main
  25:     0x5637cd06c85e - <unknown>
  26:                0x0 - <unknown>
```

(sadly no debug info in my build, but I can probably rebuild with debug info if necessary.)

Awesome shell btw!

**Comment by futile** [comment]
Here is a trace with working debug info:

```
$ RUST_BACKTRACE=full cargo run --all-features                                                                                                                                             [master] 
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/nu`
/home/felix/gits/nushell(master)> version
━━━━━━━━━
 version 
─────────
 0.3.0 
━━━━━━━━━
/home/felix/gits/nushell(master)> which raw
━━━━━━━━━━━━━━
 value 
──────────────
 /usr/bin/raw 
━━━━━━━━━━━━━━
/home/felix/gits/nushell(master)> which raw | get value
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0:     0x55bc8c7427df - backtrace::backtrace::libunwind::trace::h441c4e337211a3c6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55bc8c7427df - backtrace::backtrace::trace_unsynchronized::h9442603d0e33b1d6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55bc8c7427df - std::sys_common::backtrace::_print_fmt::h02b474af5e13681c
                               at src/libstd/sys_common/backtrace.rs:61
   3:     0x55bc8c7427df - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8b60d15e42c92fe7
                               at src/libstd/sys_common/backtrace.rs:45
   4:     0x55bc8c76c70c - core::fmt::write::h9392290131224cf6
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55bc8c73d437 - std::io::Write::write_fmt::h69513f247a796657
                               at src/libstd/io/mod.rs:1412
   6:     0x55bc8c7453c8 - std::sys_common::backtrace::_print::h7a48b9210e382046
                               at src/libstd/sys_common/backtrace.rs:48
   7:     0x55bc8c7453c8 - std::sys_common::backtrace::print::h5b7f8746dd1057f2
                               at src/libstd/sys_common/backtrace.rs:33
   8:     0x55bc8c7453c8 - std::panicking::default_hook::{{closure}}::haead9813b045d506
                               at src/libstd/panicking.rs:200
   9:     0x55bc8c7450b6 - std::panicking::default_hook::h1732881181d02f85
                               at src/libstd/panicking.rs:214
  10:     0x55bc8c745ab5 - std::panicking::rust_panic_with_hook::h64c3c49fe843bb2a
                               at src/libstd/panicking.rs:477
  11:     0x55bc8c745652 - std::panicking::continue_panic_fmt::h539a7c784c846479
                               at src/libstd/panicking.rs:384
  12:     0x55bc8c745546 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
  13:     0x55bc8c76835a - core::panicking::panic_fmt::he10f4dcd5da68021
                               at src/libcore/panicking.rs:85
  14:     0x55bc8c768315 - core::panicking::panic_bounds_check::h99d3158b5739fe7b
                               at src/libcore/panicking.rs:61
  15:     0x55bc8b4d29a1 - <usize as core::slice::SliceIndex<[T]>>::index::hd568b78eeecaebe4
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libcore/slice/mod.rs:2715
  16:     0x55bc8b897a48 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::hda5c166188e74b78
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libcore/slice/mod.rs:2566
  17:     0x55bc8b49370b - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::hbf0672cfb3122d34
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/liballoc/vec.rs:1792
  18:     0x55bc8b3ce266 - nu::commands::get::get_member::he9d5a500a83121ba
                               at src/commands/get.rs:63
  19:     0x55bc8b6ef934 - nu::commands::get::get::{{closure}}::h99b39e6342a42fad
                               at src/commands/get.rs:99
  20:     0x55bc8b46149a - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}::{{closure}}::h5ebb24708d5adfe8
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/map.rs:95
  21:     0x55bc8b315d47 - core::option::Option<T>::map::hc0b8f3a081e53fb3
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libcore/option.rs:447
  22:     0x55bc8b45efab - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}::hcf82019e438eb6e9
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/map.rs:95
  23:     0x55bc8b4bba76 - core::task::poll::Poll<T>::map::hd6df2c73a05b8b57
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libcore/task/poll.rs:35
  24:     0x55bc8b45bf89 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h53a8d46355a89a84
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/map.rs:92
  25:     0x55bc8b503a94 - <futures_util::stream::flatten::Flatten<St> as futures_core::stream::Stream>::poll_next::hef207006977f620c
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/flatten.rs:96
  26:     0x55bc8b45c6e4 - <futures_util::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h99524a92f708ef91
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/map.rs:92
  27:     0x55bc8b52fe91 - <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next::he87c2b158f696c81
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.18/src/stream.rs:86
  28:     0x55bc8b2e3348 - futures_util::stream::StreamExt::poll_next_unpin::hbec2a37eb52d0f43
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/mod.rs:1169
  29:     0x55bc8b2b99d2 - <futures_util::stream::next::Next<St> as core::future::future::Future>::poll::h50f40ef36ed14500
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/stream/next.rs:35
  30:     0x55bc8b2f6984 - std::future::poll_with_tls_context::{{closure}}::hd3aca997974b7a8c
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  31:     0x55bc8b2f5e4c - std::future::get_task_context::h60ab2a1fedb004c1
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:110
  32:     0x55bc8b2f68c4 - std::future::poll_with_tls_context::h7ce4777f06b648f7
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  33:     0x55bc8b292e05 - nu::commands::classified::InternalCommand::run::{{closure}}::h2fc96e7fdad75f1a
                               at /home/felix/gits/nushell/src/commands/classified.rs:124
  34:     0x55bc8b2f6dcb - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::h6c928178fe44508d
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  35:     0x55bc8b2f642b - std::future::set_task_context::h6e0cddac14e88951
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:78
  36:     0x55bc8b2f6a7a - <std::future::GenFuture<T> as core::future::future::Future>::poll::h3ad54bf28e7aacf8
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  37:     0x55bc8b2f69b4 - std::future::poll_with_tls_context::{{closure}}::hdca019e8e9f7e287
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  38:     0x55bc8b2f5bac - std::future::get_task_context::h4111467f95c3127c
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:110
  39:     0x55bc8b2f6894 - std::future::poll_with_tls_context::h75a370908286a9b9
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  40:     0x55bc8b2aa3f2 - nu::cli::process_line::{{closure}}::hf868039369dfbea6
                               at /home/felix/gits/nushell/src/cli.rs:543
  41:     0x55bc8b2f6f7b - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::hf8ac51d26ef19f8b
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  42:     0x55bc8b2f633b - std::future::set_task_context::h6b66ffd5af88d1bc
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:78
  43:     0x55bc8b2f6a1a - <std::future::GenFuture<T> as core::future::future::Future>::poll::h28d793a84b236bd4
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  44:     0x55bc8b2f68f4 - std::future::poll_with_tls_context::{{closure}}::h0ae859f6da7192e9
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  45:     0x55bc8b2f5f9c - std::future::get_task_context::hcf24342e4991fcef
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:110
  46:     0x55bc8b2f6864 - std::future::poll_with_tls_context::h7211b0f8bc0cc7f6
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:120
  47:     0x55bc8b2aeee5 - nu::cli::cli::{{closure}}::h43635c32b0297ffe
                               at /home/felix/gits/nushell/src/cli.rs:403
  48:     0x55bc8b2f6cd1 - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::h184ee07e01a8fb01
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  49:     0x55bc8b2f660b - std::future::set_task_context::hd2d99ad1e70fa2ab
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:78
  50:     0x55bc8b2f6b3a - <std::future::GenFuture<T> as core::future::future::Future>::poll::h7b1ee60d9f5d143e
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/future.rs:42
  51:     0x55bc8b2e20d2 - futures_executor::local_pool::block_on::{{closure}}::he7828285427cdcde
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  52:     0x55bc8b2e1ef1 - futures_executor::local_pool::run_executor::{{closure}}::hfa88d10ece6ff201
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:68
  53:     0x55bc8b2b8dad - std::thread::local::LocalKey<T>::try_with::hddc37186f1ce37e2
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/thread/local.rs:262
  54:     0x55bc8b2b83c2 - std::thread::local::LocalKey<T>::with::hec1dfd7d4b2ff5e6
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/thread/local.rs:239
  55:     0x55bc8b2e1dfc - futures_executor::local_pool::run_executor::h3a03bf71bf21edff
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:64
  56:     0x55bc8b2e200f - futures_executor::local_pool::block_on::hb4ad726b66ac578c
                               at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.18/src/local_pool.rs:296
  57:     0x55bc8b2f3ad4 - nu::main::h326bca3fb14e4335
                               at src/main.rs:53
  58:     0x55bc8b2a73a0 - std::rt::lang_start::{{closure}}::h4920a78d2d710af8
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/rt.rs:64
  59:     0x55bc8c7454e3 - std::rt::lang_start_internal::{{closure}}::h9969da47b23a9f14
                               at src/libstd/rt.rs:49
  60:     0x55bc8c7454e3 - std::panicking::try::do_call::h1375b0be74a84b29
                               at src/libstd/panicking.rs:296
  61:     0x55bc8c74f2ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  62:     0x55bc8c745fad - std::panicking::try::h27213456d5efd24a
                               at src/libstd/panicking.rs:275
  63:     0x55bc8c745fad - std::panic::catch_unwind::heb1a3baf7f3406c0
                               at src/libstd/panic.rs:394
  64:     0x55bc8c745fad - std::rt::lang_start_internal::h1945375dd082beed
                               at src/libstd/rt.rs:48
  65:     0x55bc8b2a7379 - std::rt::lang_start::hda2aa0a7463f3c31
                               at /rustc/34e82a7b793a6cdd27df762bf46bab8cdc92b14a/src/libstd/rt.rs:64
  66:     0x55bc8b2f3dea - main
  67:     0x7f4ddc6b6ee3 - __libc_start_main
  68:     0x55bc8b28465e - _start
  69:                0x0 - <unknown>
```

**Comment by jonathandturner** [comment]
Thanks for the report, the full backtrace is helpful. Looks like the get_member isn't working with plain values.
