### ISSUE TITLE
Flaky plugin tests in CI

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#7303]
We sometimes observe test failures for plugin tests that resolve by rerunning the tests on the same commit

Example:
https://github.com/nushell/nushell/actions/runs/3591888421/jobs/6046957533

```
failures:

---- plugins::core_inc::semversion_major_inc stdout ----
=== stderr
Error: nu::parser::registered_file_not_found (link)

  × File not found
   ╭─[source:1:1]
 1 │ register  /Users/runner/work/nushell/nushell/target/ci/nu_plugin_inc;open sample.toml | inc package.version -M | get package.version
   ·           ─────────────────────────────┬────────────────────────────
   ·                                        ╰── File not found: /Users/runner/work/nushell/nushell/target/ci/nu_plugin_inc
   ╰────
  help: registered files need to be available before your script is run


thread 'plugins::core_inc::semversion_major_inc' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"1.0.0"`', tests/plugins/core_inc.rs:84:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:224:17
   3: core::panicking::assert_failed
   4: main::plugins::core_inc::semversion_major_inc::{{closure}}
   5: nu_test_support::playground::play::Playground::setup
   6: main::plugins::core_inc::semversion_major_inc
   7: main::plugins::core_inc::semversion_major_inc::{{closure}}
   8: core::ops::function::FnOnce::call_once
   9: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    plugins::core_inc::semversion_major_inc

test result: FAILED. 336 passed; 1 failed; 20 ignored; 0 measured; 0 filtered out; finished in 39.06s
```

**Comment by fdncred** [comment]
I see this all too frequently. Again this morning https://github.com/nushell/nushell/actions/runs/3685256816/jobs/6235999358#step:4:742

**Comment by WindSoilder** [comment]
It's already handled by #8333 :-)
