### ISSUE TITLE
internal error: missing variable

### ISSUE THREAD

**Issue by YuriGeinishO** [nushell/nushell#7872]
### Describe the bug

Running `[{a: 1}, {a: 2}] | where $in.a = 1` leads to `thread 'main' panicked at 'internal error: missing variable'`.

### How to reproduce

```
user@WSL:~/p/nushell$ git checkout 0.74.0
HEAD is now at 9a56665c6 Commit the lockfile for 0.74 (#7719)
user@WSL:~/p/nushell$ RUST_BACKTRACE=1 cargo run
... lines deleted
    Finished dev [unoptimized + debuginfo] target(s) in 43.15s
     Running `target/debug/nu`
/home/user/p/nushell: [{a: 1}, {a: 2}] | where $in.a = 1                                                                               01/27/2023 09:10:31 AMthread 'main' panicked at 'internal error: missing variable', crates/nu-protocol/src/engine/engine_state.rs:744:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:738:21
   6: nu_protocol::engine::engine_state::EngineState::get_var
             at ./crates/nu-protocol/src/engine/engine_state.rs:742:9
   7: nu_engine::eval::eval_expression
             at ./crates/nu-engine/src/eval.rs:468:46
   8: nu_engine::eval::eval_expression_with_input
             at ./crates/nu-engine/src/eval.rs:695:21
   9: nu_engine::eval::eval_element_with_input
             at ./crates/nu-engine/src/eval.rs:716:49
  10: nu_engine::eval::eval_block
             at ./crates/nu-engine/src/eval.rs:908:31
  11: <nu_command::filters::where_::Where as nu_protocol::engine::command::Command>::run::{{closure}}
             at ./crates/nu-command/src/filters/where_.rs:109:30
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:294:13
  13: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:2732:32
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/enumerate.rs:85:27
  15: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:2238:21
  16: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/enumerate.rs:91:9
  17: core::iter::traits::iterator::Iterator::find_map
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:2738:9
  18: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/filter_map.rs:61:9
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/map.rs:103:9
  20: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1874:9
  21: <nu_protocol::value::stream::ListStream as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/value/stream.rs:224:13
  22: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:3868:9
  23: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-command/src/viewers/table.rs:1723:21
  24: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1874:9
  25: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
             at ./crates/nu-protocol/src/value/stream.rs:103:19
  26: nu_protocol::pipeline_data::print_if_stream
             at ./crates/nu-protocol/src/pipeline_data.rs:749:18
  27: nu_protocol::pipeline_data::PipelineData::print
             at ./crates/nu-protocol/src/pipeline_data.rs:635:20
  28: nu_cli::util::eval_source
             at ./crates/nu-cli/src/util.rs:249:34
  29: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:420:21
  30: nu::main
             at ./src/main.rs:441:31
  31: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

To give proper error handling.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             |                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-27 09:10:01 +01:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
That sounds like a severe regression

**Comment by merelymyself** [comment]
This seems to be happening for all instances of $in in `where`.

**Comment by sholderbach** [comment]
Mhh sounds like the (error) handling of `RowCondition`s is broken.

**Comment by merelymyself** [comment]
This also seems to be happening for all other internal variables, eg `$env`.

If anyone's trying to fix this, maybe take a look at `Operator::Assignment`: the single "=" sign means `eval.rs` evaluates this not as a comparison but as assignment and tries to access a var_id that does not exist.
