### ISSUE TITLE
Nushell crashes when tab completion removes backticks

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7885]
### Describe the bug

See below.

### How to reproduce

1. Write something like `open MODArchive.m3u8` on the command line, where `MODArchive.m3u8` can be any file existing in the CWD.
2. Press ` to add one backtick to the end.
3. Press Tab *twice*.

On the first tab, the backtick is removed. On the second tab, crash.
```
〉open MODArchive.m3u8thread 'main' panicked at 'insertion index (is 21) should be <= len (is 20)', library\alloc\src\vec\mod.rs:1445:13
stack backtrace:
   0:     0x7ff62f7eb122 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff62f7eb122 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff62f7eb122 - std::sys_common::backtrace::_print_fmt
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff62f7eb122 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff62f8130bb - core::fmt::write
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\fmt\mod.rs:1209
   5:     0x7ff62f7e165a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\io\mod.rs:1682
   6:     0x7ff62f7eae6b - std::sys_common::backtrace::_print
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff62f7eae6b - std::sys_common::backtrace::print
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff62f7ee029 - std::panicking::default_hook::closure$1
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:267
   9:     0x7ff62f7edcaa - std::panicking::default_hook
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:286
  10:     0x7ff62d133550 - alloc::boxed::impl$47::call<tuple$<ref$<core::panic::panic_info::PanicInfo> >,dyn$<core::ops::function::Fn<tuple$<ref$<core::panic::panic_info::PanicInfo> >,assoc$<Output,tuple$<> > >,core::marker::Send,core::marker::Sync>,alloc::alloc::Global> 
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\alloc\src\boxed.rs:2001
  11:     0x7ff62d148529 - nu::main::closure$0
                               at C:\Coding\nushell\src\main.rs:43
  12:     0x7ff62f7ee8e0 - alloc::boxed::impl$47::call
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\alloc\src\boxed.rs:2001
  13:     0x7ff62f7ee8e0 - std::panicking::rust_panic_with_hook
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:692
  14:     0x7ff62f7ee63d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:579
  15:     0x7ff62f7ebe2f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common\backtrace.rs:137
  16:     0x7ff62f7ee300 - std::panicking::begin_panic_handler
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:575
  17:     0x7ff62f97d5a5 - core::panicking::panic_fmt
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\panicking.rs:65
  18:     0x7ff62f97d45b - alloc::vec::impl$1::insert::assert_failed
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\alloc\src\vec\mod.rs:1445
  19:     0x7ff62f436dcb - alloc::vec::Vec<u8,alloc::alloc::Global>::insert<u8,alloc::alloc::Global>
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\alloc\src\vec\mod.rs:1467
  20:     0x7ff62e4a449a - nu_cli::completions::completer::NuCompleter::completion_helper
                               at C:\Coding\nushell\crates\nu-cli\src\completions\completer.rs:126
  21:     0x7ff62e4a6e8a - nu_cli::completions::completer::impl$1::complete
                               at C:\Coding\nushell\crates\nu-cli\src\completions\completer.rs:404
  22:     0x7ff62e6380dd - reedline::menu::columnar_menu::impl$4::update_values
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\menu\columnar_menu.rs:544
  23:     0x7ff62e5df3cc - enum2$<reedline::menu::ReedlineMenu>::update_values
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\menu\mod.rs:185
  24:     0x7ff62e5f564e - reedline::engine::Reedline::handle_editor_event
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\engine.rs:723
  25:     0x7ff62e5f5931 - reedline::engine::Reedline::handle_editor_event
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\engine.rs:1026
  26:     0x7ff62e5f37f9 - reedline::engine::Reedline::handle_event
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\engine.rs:599
  27:     0x7ff62e5f31a4 - reedline::engine::Reedline::read_line_helper
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\engine.rs:576
  28:     0x7ff62e5f2663 - reedline::engine::Reedline::read_line
                               at C:\Users\Leon\.cargo\git\checkouts\reedline-e42026a78d91c510\3d83306\src\engine.rs:453
  29:     0x7ff62e444926 - nu_cli::repl::evaluate_repl
                               at C:\Coding\nushell\crates\nu-cli\src\repl.rs:347
  30:     0x7ff62d1420b7 - nu::main
                               at C:\Coding\nushell\src\main.rs:305
  31:     0x7ff62d14a7ab - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > (*)(),tuple$<> >
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src\ops\function.rs:251
  32:     0x7ff62d15296e - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > (*)(),enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > >
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\std\src\sys_common\backtrace.rs:121
  33:     0x7ff62d13cb61 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > >
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\std\src\rt.rs:166
  34:     0x7ff62f7d90ee - core::ops::function::impls::impl$2::call_once
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\ops\function.rs:286
  35:     0x7ff62f7d90ee - std::panicking::try::do_call
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:483
  36:     0x7ff62f7d90ee - std::panicking::try
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:447
  37:     0x7ff62f7d90ee - std::panic::catch_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panic.rs:137
  38:     0x7ff62f7d90ee - std::rt::lang_start_internal::closure$2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\rt.rs:148
  39:     0x7ff62f7d90ee - std::panicking::try::do_call
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:483
  40:     0x7ff62f7d90ee - std::panicking::try
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:447
  41:     0x7ff62f7d90ee - std::panic::catch_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panic.rs:137
  42:     0x7ff62f7d90ee - std::rt::lang_start_internal
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\rt.rs:148
  43:     0x7ff62d13cb3a - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,miette::eyreish::Report> > >
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\std\src\rt.rs:165
  44:     0x7ff62d1435a9 - main
  45:     0x7ff62f964360 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  46:     0x7ff62f964360 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  47:     0x7fff24687614 - BaseThreadInitThunk
  48:     0x7fff25e226a1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\nu.exe` (exit code: 101)
```

### Expected behavior

n/a

### Configuration

Confirmed on both `main` and release 0.74

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | 36ddbfdc85a4bdd796427e80bb77cdfc221887b0 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-28 16:51:48 +10:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by merelymyself** [comment]
Maybe it's just me, but I feel like the first <tab> should never change what's on the line; it's just a means to see possible options.

**Comment by csko** [comment]
I did a git bisect, the issue starts happening after 7b9ad9d2e59149a330b779058560283d253a5657

There is also another related issue:
1. type `` open FILENAME` ``
2. press TAB (`` ` `` gets removed at the end)
3. press `` ` ``

This gives the error
```
thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\string.rs:1530:9                                                     01/30/2023 10:59:14 PMstack backtrace:
   0:     0x7ff7f025193f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7f025193f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7f025193f - std::sys_common::backtrace::_print_fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff7f025193f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff7f0278d9a - core::fmt::write
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\fmt\mod.rs:1197
   5:     0x7ff7f0247739 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\io\mod.rs:1672
   6:     0x7ff7f025486b - std::sys_common::backtrace::_print
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff7f025486b - std::sys_common::backtrace::print
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff7f025486b - std::panicking::default_hook::closure$1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:295
   9:     0x7ff7f02544eb - std::panicking::default_hook
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:314
  10:     0x7ff7edf47033 - alloc::boxed::impl$46::call<tuple$<ref$<core::panic::panic_info::PanicInfo> >,dyn$<core::ops::function::Fn<tuple$<ref$<core::panic::panic_info::PanicInfo> >,assoc$<Output,tuple$<> > >,core::marker::Send,core::marker::Sync>,alloc::alloc::Global>
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\boxed.rs:1965
  11:     0x7ff7edf56509 - nu::main::closure$0
                               at E:\dev\nushell\src\main.rs:45
  12:     0x7ff7f0254f82 - std::panicking::rust_panic_with_hook
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:702
  13:     0x7ff7f0254ce2 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:586
  14:     0x7ff7f0252577 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:138
  15:     0x7ff7f02549f9 - std::panicking::begin_panic_handler
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
  16:     0x7ff7f03e3695 - core::panicking::panic_fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
  17:     0x7ff7f03e353c - core::panicking::panic
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:48
  18:     0x7ff7ef16bf13 - alloc::string::String::insert
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\alloc\src\string.rs:1530
  19:     0x7ff7ef153835 - reedline::core_editor::line_buffer::LineBuffer::insert_char
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\core_editor\line_buffer.rs:342
  20:     0x7ff7ef1a9cb9 - reedline::core_editor::editor::Editor::run_edit_command
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\core_editor\editor.rs:57
  21:     0x7ff7ef1e8364 - reedline::engine::Reedline::run_edit_commands
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\engine.rs:1154
  22:     0x7ff7ef1e57de - reedline::engine::Reedline::handle_editor_event
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\engine.rs:896
  23:     0x7ff7ef1e3039 - reedline::engine::Reedline::handle_event
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\engine.rs:586
  24:     0x7ff7ef1e29e4 - reedline::engine::Reedline::read_line_helper
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\engine.rs:563
  25:     0x7ff7ef1e1f23 - reedline::engine::Reedline::read_line
                               at C:\Users\csko\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.12.0\src\engine.rs:440
  26:     0x7ff7eef4be6d - nu_cli::repl::evaluate_repl
                               at E:\dev\nushell\crates\nu-cli\src\repl.rs:340
  27:     0x7ff7edf40f20 - nu::main
                               at E:\dev\nushell\src\main.rs:358
  28:     0x7ff7edf4d56b - core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
  29:     0x7ff7edf3206b - std::sys_common::backtrace::__rust_begin_short_backtrace<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> (*)(),enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\sys_common\backtrace.rs:122
  30:     0x7ff7edf4b551 - std::rt::lang_start::closure$0<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\rt.rs:145
  31:     0x7ff7f023e981 - core::ops::function::impls::impl$2::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\ops\function.rs:280
  32:     0x7ff7f023e981 - std::panicking::try::do_call
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:492
  33:     0x7ff7f023e981 - std::panicking::try
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:456
  34:     0x7ff7f023e981 - std::panic::catch_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panic.rs:137
  35:     0x7ff7f023e981 - std::rt::lang_start_internal::closure$2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\rt.rs:128
  36:     0x7ff7f023e981 - std::panicking::try::do_call
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:492
  37:     0x7ff7f023e981 - std::panicking::try
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:456
  38:     0x7ff7f023e981 - std::panic::catch_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panic.rs:137
  39:     0x7ff7f023e981 - std::rt::lang_start_internal
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\rt.rs:128
  40:     0x7ff7edf4b51f - std::rt::lang_start<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\rt.rs:144
  41:     0x7ff7edf46f36 - main
  42:     0x7ff7f03c93c0 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  43:     0x7ff7f03c93c0 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  44:     0x7ffecc807614 - BaseThreadInitThunk
  45:     0x7ffece8026a1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\nu.exe` (exit code: 101)
```

This second issue starts happening after e36649f74b37ee183a2b2999b5b3ee4762cb921a

**Comment by csko** [comment]
When reedline takes the completion suggestions, it assumes that the suggestions are at least as long as what's in the editor, but that's not the case because of the removed `` ` ``.

https://github.com/nushell/reedline/blob/main/src/menu/columnar_menu.rs#L671

**Comment by csko** [comment]
https://github.com/nushell/reedline/pull/534 fixes both issues.
