### ISSUE TITLE
using tab-completion on multi-words aliases causes `nushell` to panic

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8122]
### Describe the bug

i started playing with the `zk` note manager and did the following

- define the notebook location with
```bash
let-env ZK_NOTEBOOK_DIR = ($env.XDG_DATA_HOME | path join "zk" "notes")
```
- initialize a notebook at that location with
```bash
zk init $env.ZK_NOTEBOOK_DIR
```
- add some notes in there

:heavy_check_mark: this works fine

now i want to track this notebook and all the files in there from outside the directory, with an alias
> **Note**
> one can control a `git` repo from anywhere with `git -C /path/to/repo/`

```bash
alias "zk git" = git -C $env.ZK_NOTEBOOK_DIR
```
allowing me to run things like
```bash
> zk git status
> zk git push
```

:x: this is where i get the bug when trying to autocomplete...

### :heavy_check_mark: a failing case
> **Note**
> see the full recording [here](https://asciinema.org/a/561007)

1. run `RUST_BACKTRACE=full nu`
2. define the location of the notebook with `let-env ZK_NOTEBOOK_DIR = "/tmp/notes"`
3. get my notes with `git clone https://github.com/amtoine/notes.git $env.ZK_NOTEBOOK_DIR` => i have trouble reproducing all this without a `zk` repo and its the easiest way for you to test this without installing `zk` and setuping that yourself :eyes:
4. define the problematic alias with `alias "zk git" = git -C $env.ZK_NOTEBOOK_DIR`
5. start typing `zk git add ` (with the space at the end)
6. try to autocomplete with `TAB`
7. see the error
```
thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709551601, end=11', /home/amtoine/.local/share/cargo/git/checkouts/reedline-e42026a78d91c510/03fdb00/src/completion/base.rs:18:9
stack backtrace:
   0:     0x5557f1550aa5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
   1:     0x5557f0a0a90e - core::fmt::write::h062c617411b691df
   2:     0x5557f1549345 - std::io::Write::write_fmt::hb61fdf1275c61e1c
   3:     0x5557f1550875 - std::sys_common::backtrace::print::hca896ae22beb06cb
   4:     0x5557f15525ff - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
   5:     0x5557f155236a - std::panicking::default_hook::h8932b573145a321b
   6:     0x5557f1552c90 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
   7:     0x5557f1552a24 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
   8:     0x5557f1550fbc - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
   9:     0x5557f1552772 - rust_begin_unwind
  10:     0x5557f09a1fc3 - core::panicking::panic_fmt::h8aa706a976963c88
  11:     0x5557f1409a92 - reedline::completion::base::Span::new::h3ef46a4fb9a23ed6
  12:     0x5557f0b2fad8 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h2d8ef5a70f3f1e14
  13:     0x5557f0b5f157 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::h120d4b42ea24dba6
  14:     0x5557f0b1ee0b - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hf4b6e2c7473f5154
  15:     0x5557f0b1aa0f - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h41daa9ab7ac710b4
  16:     0x5557f0b33f10 - nu_cli::completions::command_completions::CommandCompletion::complete_commands::hf862d7ecab2110fd
  17:     0x5557f0b34c5a - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::hfbc18cdf8f5d07ac
  18:     0x5557f0b5744d - nu_cli::completions::completer::NuCompleter::process_completion::h5b9173ae5eb6902d
  19:     0x5557f0b58ec5 - nu_cli::completions::completer::NuCompleter::completion_helper::h74006487c0954b3a
  20:     0x5557f0b5a6a3 - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::h7304d0962ffcd565
  21:     0x5557f1412b28 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::h957ad31630cb7291
  22:     0x5557f140dec1 - reedline::engine::Reedline::handle_editor_event::h471b4d2f3d0ae982
  23:     0x5557f140c023 - reedline::engine::Reedline::read_line::h24f5b3febb8cfbe1
  24:     0x5557f0b47022 - nu_cli::repl::evaluate_repl::h12fcbf68f26aea86
  25:     0x5557f0b07215 - nu::run::run_repl::h4a8e4d5940d5fe53
  26:     0x5557f0b148c2 - nu::main::hb81ab15bd17a3a48
  27:     0x5557f0b14fbe - std::sys_common::backtrace::__rust_begin_short_backtrace::hda4b16f4ec94ce29
  28:     0x5557f0b160de - std::rt::lang_start::{{closure}}::h3ae7a51bc1763457
  29:     0x5557f1542d1b - std::rt::lang_start_internal::hcd7e45acd25ab5ab
  30:     0x5557f0b14ec5 - main
  31:     0x7fa75d63c790 - <unknown>
  32:     0x7fa75d63c84a - __libc_start_main
  33:     0x5557f09c7635 - _start
  34:                0x0 - <unknown>
```

### :x: a case without any error 
> **Note**
> see the full recording [here](https://asciinema.org/a/561008)

the exact same thing but with
```bash
alias "zk git" = git -C /tmp/notes
```
at step 4

### Expected behavior

i expected `nu` not to panick, regardless of the `alias` being defined with `git -C <string>` or `git -C $env.<variable>` :yum: 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.75.1                                   |
| branch             | main                                     |
| commit_hash        | f3ee8b50e3da9548fe39cfb104a20d6da10a6458 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.75.1                                   |
| build_time         | 2023-02-19 11:38:06 +01:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  | gstat                                    |

**Comment by amtoine** [comment]
i can reproduce this on
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | d6141881f228889561cf360a7b4355db577478db |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-05 11:23:36 +01:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | gstat                                    |

with
```bash
alias cfg = ^git --git-dir $env.DOTFILES_GIT_DIR --work-tree $env.DOTFILES_WORKTREE
```
and almost the same as step 4, with `cfg add `
```bash
thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709383586, end=8', /home/amtoine/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.16.0/src/completion/base.rs:18:9
stack backtrace:
   0:     0x5620ed6f5a35 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
   1:     0x5620ecb8618e - core::fmt::write::h062c617411b691df
   2:     0x5620ed6ee2d5 - std::io::Write::write_fmt::hb61fdf1275c61e1c
   3:     0x5620ed6f5805 - std::sys_common::backtrace::print::hca896ae22beb06cb
   4:     0x5620ed6f758f - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
   5:     0x5620ed6f72fa - std::panicking::default_hook::h8932b573145a321b
   6:     0x5620ed6f7c20 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
   7:     0x5620ed6f79b4 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
   8:     0x5620ed6f5f4c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
   9:     0x5620ed6f7702 - rust_begin_unwind
  10:     0x5620ecb1d013 - core::panicking::panic_fmt::h8aa706a976963c88
  11:     0x5620ed5af770 - reedline::completion::base::Span::new::h81f8eee50c7135e2
  12:     0x5620ecca598e - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h8652b771659b3896
  13:     0x5620ecccfa48 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::h58180b893ab2b6ad
  14:     0x5620ecc96d22 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h87a2273df4b237c3
  15:     0x5620ecc92a6b - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h35b6a83d3b255df0
  16:     0x5620ecc9b25f - nu_cli::completions::command_completions::CommandCompletion::complete_commands::h034209aff525c34a
  17:     0x5620ecc9c0a8 - <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch::h0e1b2bc79a7269e5
  18:     0x5620ecccc738 - nu_cli::completions::completer::NuCompleter::process_completion::h0091511f4d5b9f6d
  19:     0x5620eccce256 - nu_cli::completions::completer::NuCompleter::completion_helper::h64e2ebec4c8eb5d3
  20:     0x5620ecccf9fc - <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete::h969834cd250eb0c1
  21:     0x5620ed5b8806 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values::hbdc789c928695ea9
  22:     0x5620ed5b372f - reedline::engine::Reedline::handle_editor_event::hfa9d0e5f99653d80
  23:     0x5620ed5b327d - reedline::engine::Reedline::handle_editor_event::hfa9d0e5f99653d80
  24:     0x5620ed5b1d01 - reedline::engine::Reedline::read_line::hb9b8f9da199ec90a
  25:     0x5620eccb271c - nu_cli::repl::evaluate_repl::hd1723ba4dcdc72ac
  26:     0x5620ecc7f58a - nu::run::run_repl::ha7273984109ce045
  27:     0x5620ecc8cd69 - nu::main::haece71454d83c121
  28:     0x5620ecc8db0a - std::sys_common::backtrace::__rust_begin_short_backtrace::h594cf7581652703c
  29:     0x5620ecc8dbff - std::rt::lang_start::{{closure}}::hc05863e5a5378eb9
  30:     0x5620ed6e7cab - std::rt::lang_start_internal::hcd7e45acd25ab5ab
  31:     0x5620ecc8d3c5 - main
  32:     0x7f7ca2154790 - <unknown>
  33:     0x7f7ca215484a - __libc_start_main
  34:     0x5620ecb429a5 - _start
  35:                0x0 - <unknown>
```

**Comment by amtoine** [comment]
# likely related
- #9146 
- #11028 
- #11188

**Comment by NotTheDr01ds** [comment]
I should note that, while Fish doesn't panic, it takes an *extremely* long time to return control to the user when attempting to complete filenames on a `config add`.

**Comment by galuszkak** [comment]
I couldn't reproduce this issue locally anymore with 0.111.

**Comment by Bahex** [comment]
Works as expected as of 0.112.2
