### ISSUE TITLE
Test suite dependent on system directories *not* existing

### ISSUE THREAD

**Issue by alerque** [nushell/nushell#8404]
While working on #7951 I noticed I could run tests on some systems but not others. Notably the test failures on my host desktop were different than the specific failure we were trying to track down in more limited chroot / container environments.

I just poked around a little and this *seems* to be because I have docbook and sgml-common tooling installed on my desktop but not in the clear chroot or Docker containers I was testing packaging with. This makes the difference between the directory `/usr/share/sgml` existing or not, and the test suite seems to *fail if it **does** exist* and succeed if it does not.

Here is the error I'm seeing where the parent directories of some `foo` stuff from the tests **does** exist:

```
failures:

---- tests::test_hiding::hides_alias_import_1 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_alias_import_1' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_hiding::hides_alias_import_3 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_alias_import_3' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_alias_import_2 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_alias_import_2' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_def_import_1 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_def_import_1' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_def_import_2 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_def_import_2' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_def_import_3 stdout ----
stdout:
stderr: spam:E: cannot find "foo"; tried "foo", "/usr/share/sgml/foo", "/usr/share/xml/foo"

thread 'tests::test_hiding::hides_def_import_3' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_main_import_1 stdout ----
stdout:
stderr: spam:<OSFD>0:1:0:E: end of document in prolog

thread 'tests::test_hiding::hides_main_import_1' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_main_import_4 stdout ----
stdout:
stderr: spam:<OSFD>0:1:0:E: end of document in prolog

thread 'tests::test_hiding::hides_main_import_4' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_main_import_3 stdout ----
stdout:
stderr: spam:<OSFD>0:1:0:E: end of document in prolog

thread 'tests::test_hiding::hides_main_import_3' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5

---- tests::test_hiding::hides_main_import_2 stdout ----
stdout:
stderr: spam:<OSFD>0:1:0:E: end of document in prolog

thread 'tests::test_hiding::hides_main_import_2' panicked at 'assertion failed: !stderr.is_empty() && stderr.contains(expected)', src/tests.rs:123:5


failures:
    tests::test_hiding::hides_alias_import_1
    tests::test_hiding::hides_alias_import_2
    tests::test_hiding::hides_alias_import_3
    tests::test_hiding::hides_def_import_1
    tests::test_hiding::hides_def_import_2
    tests::test_hiding::hides_def_import_3
    tests::test_hiding::hides_main_import_1
    tests::test_hiding::hides_main_import_2
    tests::test_hiding::hides_main_import_3
    tests::test_hiding::hides_main_import_4

test result: FAILED. 377 passed; 10 failed; 4 ignored; 0 measured; 0 filtered out; finished in 1.09s
```

Using Rust 1.67.1 on Arch Linux. Testing e43519695.

**Comment by alerque** [comment]
Note the diagnosis here might be incidental, the directory may not be the only system artifact throwing this off. There is potentially other tooling installed and getting executed here, but the fact that a fully fleshed development desktop is regularly failing and a slimmed down chroot / container gets past this test point does seem to suggest something.

**Comment by jntrnr** [comment]
It looks like what's happening is that there's a command on the system called `spam` which the test suite isn't expecting to find. I can rename the tests to use something a bit more unique. I'm guessing like you suggest the `spam` tool might be coming from that sgml suite.

https://linux.die.net/man/1/spam
