### ISSUE TITLE
Cargo test attempts to run benchmarks with undeclared dependencies

### ISSUE THREAD

**Issue by alerque** [nushell/nushell#8463]
Trying to follow up on #7951, compiling on my own workstation environment using stable Rust. 
``` console
$ git describe --tags --long
0.77.0-4-g61455b457
$ cargo test --frozen --workspace --features=extra,dataframe
<...snip...>
failures:

---- overlays::overlay_use_main_not_exported stdout ----
=== stderr
spam:E: error reading file descriptor 0 (Input/output error)
spam:<OSFD>0:1:0:E: end of document in prolog

thread 'overlays::overlay_use_main_not_exported' panicked at 'assertion failed: actual.err.contains(\"external_command\")', tests/overlays/mod.rs:1262:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- shell::pipeline::commands::external::command_not_found_error_suggests_typo_fix stdout ----
=== stderr
/usr/lib/ruby/3.0.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem benchmark_suite (>= 0.a) with executable benchmark (Gem::GemNotFoundException)
        from /usr/lib/ruby/3.0.0/rubygems.rb:284:in `activate_bin_path'
        from /usr/bin/benchmark:23:in `<main>'

thread 'shell::pipeline::commands::external::command_not_found_error_suggests_typo_fix' panicked at 'assertion failed: actual.err.contains(\"timeit\")', tests/shell/pipeline/commands/external.rs:120:5


failures:
    overlays::overlay_use_main_not_exported
    shell::pipeline::commands::external::command_not_found_error_suggests_typo_fix

test result: FAILED. 388 passed; 2 failed; 20 ignored; 0 measured; 0 filtered out; finished in 2.00s
```

Building this same version with the same commands & rust toolchain but in a clean does *not* result in the same error. I suspect it is finding *something* on my system (Ruby perhaps?) then deciding it must be okay to automatically run benchmarks that require even more tooling.

**Comment by fdncred** [comment]
hmmmm, `benchmark` used to be the name of our timing command. it's now called `timeit`. I wonder if that new name isn't updated somewhere?

**Comment by fdncred** [comment]
oh, ya. This test is just supposed to fail with a suggestion
```rust
#[test]
fn command_not_found_error_suggests_typo_fix() {
    let actual = nu!(cwd: ".", "benchmark { echo 'foo'}");
    assert!(actual.err.contains("timeit"));
}
```
I guess some other command is named benchmark and it's trying to find that.

**Comment by fdncred** [comment]
I think we should just remove that test.  But we are dependent on external echo in some tests. Those are the ones I didn't fix all of. I agree we should fix those too.

**Comment by sholderbach** [comment]
Similar to being selective about the environment passed to the tests (https://github.com/nushell/nushell/pull/9976) we should probably limit the `PATH`/`Path` in the test runner to the expected minimum. This would prevent such test failures.
#8209 did this locally in a few tests by overriding the path variable with `with-env`. I think the more robust solution would be to do it directly in the test launcher. For `nu!`/`nu_with_plugins!`: https://github.com/nushell/nushell/blob/d2f513da36fe3e8b2b60584e28deaa2c4253f666/crates/nu-test-support/src/macros.rs#L227-L386

And we shouldn't forget the other `nu` launching tests living in https://github.com/nushell/nushell/blob/d2f513da36fe3e8b2b60584e28deaa2c4253f666/src/tests.rs#L36-L184


The only downside to messing with the path variable (apart from the `Path` drama on Windows) is that we don't notice name clashes like this. When you run nushell you will first see the nushell symbols.

**Comment by cptpiepmatz** [comment]
Tests running via #17733 do not have a `PATH` env loaded, so this should no long happen without consideration.
