### ISSUE TITLE
Error when running `ls -la`: thread 'main' panicked at 'assertion failed

### ISSUE THREAD

**Issue by llagerlof** [nushell/nushell#8769]
### Describe the bug

Inside `nushell` (0.78.0), the error below are happening when I issue the command `ls -la`:

```
thread 'main' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:69:9
```

### How to reproduce

1. Enter `nu`
2. Run the command `ls -la`

### Expected behavior

List all files and directories inside the current directory.

### Configuration

```
| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.78.0                                                     |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (Fedora 1.68.0-1.fc36) |
| cargo_version      | cargo 1.68.0                                               |
| build_time         | 2023-04-06 08:51:34 -03:00                                 |
| build_rust_channel | release                                                    |
| features           | default, zip                                               |
| installed_plugins  |                                                            |
```

### Additional context

- Fedora 36
- Running nushell inside bash 5.2.15
- Kernel 6.2.8

**Comment by fdncred** [comment]
Looks like you have a file with an incorrect time maybe? We should handle this better though.

**Comment by fdncred** [comment]
> looks normal to me ...

LOL. I don't think bash is written in rust so it doesn't uss the same crate source code such as `library/std/src/sys/unix/time.rs`. so it's not a good comparison. The error is pretty clear that this is the error `tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64`, so whatever `tv_nsec` is in time.rs is the problem.

Someone may be able to fix this in the nushell source but it could also be an upstream problem as well, I'm not sure.

Without having a file that produces these errors, it'll be hard to fix though.

**Comment by llagerlof** [comment]
@fdncred Thanks for your insights, and sorry for my error. I thought nushell does a parsing on `ls` output and work from there. God, I am stupid.

I had an idea. Tried to run the `ls -lsa` non-interactively:
```
$ nu -c "ls -lsa"
```
And the error happened, as usual:
```
thread 'main' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:69:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
So to identify the bad file I wrote this script:
```
#!/bin/bash

for file in .* *; do
  if [[ -f "$file" ]]; then
    nu -c "ls -lsa $file"
  fi
done
```
But for my surprise all commands ran successfully for each file individually. I think I will just drop any hope and install OS/2.

**Comment by llagerlof** [comment]
After some tests I found out the problematic directory. It's the `~/.config/microsoft-edge/`.

I don't know why, but `nushell` fails when tries to read some info from this directory. This problem happens too in some files and contents of this directory.

Here is the stat of `microsoft-edge` directory, if helps:

```
  File: microsoft-edge
  Size: 1200      	Blocks: 0          IO Block: 4096   directory
Device: 0,36	Inode: 10103887    Links: 1
Access: (0700/drwx------)  Uid: ( 1000/lawrence)   Gid: ( 1000/user1)
Context: unconfined_u:object_r:config_home_t:s0
Access: 2023-04-06 19:53:14.974066209 -0300
Modify: 2023-04-06 19:53:14.944065809 -0300
Change: 2023-04-06 19:53:14.944065809 -0300
 Birth: 2023-02-15 10:27:21.725064946 -0300
```

**Comment by fdncred** [comment]
I don't think it's the directory that's causing the problems. There is probably 1 file with a messed up access, modify, change, or birth date that is funky that is causing `library/std/src/sys/unix/time.rs` to have problems.

**Comment by llagerlof** [comment]
And just for completeness, my `.config` dir has an integer as birth date too. I'ts because of this directory that listing the insides of my $HOME dir was crashing nushell.

**Comment by fdncred** [comment]
I think you've put your finger on what the issue is but it's going to take someone, like yourself, with those messed up dates, to try and make nushell's ls code behave and not panic in those situations.

**Comment by llagerlof** [comment]
Thanks. I found out rhe rust devs are already aware of this problem.

https://github.com/rust-lang/rust/issues/108277

**Comment by weirdan** [comment]
The upstream bug has been fixed in 1.78.0 (the minimum version nushell builds with now). @llagerlof would you mind testing with a fresh nushell version?

**Comment by llagerlof** [comment]
> @llagerlof would you mind testing with a fresh nushell version?

Unfortunately I don't have access to that filesystem anymore.
